// Everyday names for each entry. When any entry's text mentions one, that word is highlighted
// and can be peeked. Avoid generic words ("group", "field", "phase") — they'd light up everywhere.

export const ALIASES = {
  // ---------------------------------------------------------------- string theory & symmetry
  'monster-group': ['Monster', 'Monster group', 'Fischer–Griess Monster', 'Friendly Giant'],
  'order-of-the-monster': ['order of the Monster', 'supersingular primes'],
  'j-invariant': ['j-invariant', 'j-function', 'Klein’s j-invariant'],
  'monstrous-moonshine': ['moonshine', 'monstrous moonshine', 'Conway–Norton conjecture', 'McKay–Thompson series'],
  'example-mckay-196884': ['McKay’s observation'],
  'vertex-operator-algebra': ['vertex operator algebra', 'vertex algebra', 'VOA', 'vertex operator', 'state–field correspondence'],
  'virasoro-algebra': ['Virasoro algebra', 'Virasoro'],
  'leech-lattice': ['Leech lattice', 'Leech'],
  'bosonic-string': ['bosonic string', 'bosonic string theory', 'tachyon'],
  'critical-dimension': ['critical dimension', 'D = 26'],
  'example-zeta-regularization': ['zeta regularization', 'zeta-regularized'],
  'moonshine-module': ['Moonshine Module', 'Monster module', 'Monster CFT'],
  'classical-string': ['Nambu–Goto', 'Nambu–Goto action', 'Polyakov action', 'worldsheet', 'string tension'],
  'light-cone-quantization': ['light-cone quantization', 'light-cone gauge', 'light-cone'],
  'conformal-symmetry': ['conformal symmetry', 'conformal transformation', 'conformal map', 'Witt algebra', 'conformal invariance'],
  'conformal-field-theory': ['conformal field theory', 'CFT', 'chiral CFT', 'state–operator correspondence', 'radial quantization', 'primary field'],
  'operator-product-expansion': ['operator product expansion', 'OPE'],
  'torus-partition-function': ['torus partition function', 'modular invariance', 'modular invariant', 'modularly invariant'],
  'example-24-oscillators': ['24 oscillators'],
  anomalies: ['anomaly', 'quantum anomaly', 'central charge', 'conformal anomaly', 'Weyl anomaly'],
  'ghosts-no-ghost': ['no-ghost theorem', 'ghosts', 'BRST', 'Faddeev–Popov ghosts', 'negative-norm states'],
  compactification: ['compactification', 'compactified', 'compact dimension'],
  'lattice-voa': ['lattice VOA', 'lattice vertex algebra', 'lattice vertex operator algebra'],
  'example-leech-to-j': ['300 + 98280 + 98304'],
  orbifolds: ['orbifold', 'twisted sector'],
  'golay-m24': ['Golay code', 'Mathieu group', 'octad'],
  'borcherds-algebras': ['Borcherds algebra', 'Monster Lie algebra', 'Kac–Moody algebra', 'generalized Kac–Moody algebra', 'denominator identity'],
  superstrings: ['superstring', 'superstring theory', 'GSO projection', 'heterotic string'],
  'mathieu-umbral-moonshine': ['Mathieu moonshine', 'umbral moonshine', 'K3 surface'],
  'ads-cft': ['AdS/CFT', 'anti-de Sitter', 'holography', 'holographic duality', 'Brown–Henneaux', 'extremal CFT'],
  'question-monster-universe': [],

  // ---------------------------------------------------------------- quantum & extreme matter
  superposition: ['superposition', 'quantum superposition', 'superposed'],
  'schrodinger-equation': ['Schrödinger equation', 'Schrodinger equation'],
  'born-rule': ['Born rule', 'Born’s rule'],
  'example-qubit': [],
  'bose-einstein-statistics': ['Bose–Einstein distribution', 'Bose–Einstein statistics', 'Bose statistics'],
  'bose-einstein-condensate': ['Bose–Einstein condensate', 'Bose–Einstein condensation', 'BEC', 'condensate', 'condensation'],
  'bec-critical-temperature': ['critical temperature', 'transition temperature', 'condensate fraction'],
  'example-rb87-tc': [],
  'gross-pitaevskii': ['Gross–Pitaevskii equation', 'Gross–Pitaevskii', 'GP equation', 'mean-field'],
  superfluidity: ['superfluidity', 'superfluid', 'zero viscosity', 'lambda point', 'two-fluid model'],
  'landau-criterion': ['Landau criterion', 'critical velocity'],
  'example-landau-velocities': [],
  'bogoliubov-dispersion': ['Bogoliubov dispersion', 'Bogoliubov spectrum', 'Bogoliubov'],
  'quantized-circulation': ['quantized circulation', 'quantized vortices', 'quantum of circulation', 'vortex', 'vortices'],
  'example-he4-circulation': [],
  'wave-particle-duality': ['wave–particle duality', 'de Broglie wavelength', 'thermal de Broglie wavelength', 'matter wave', 'photon'],
  'hilbert-space': ['Hilbert space', 'Dirac notation', 'bra–ket', 'state vector'],
  'observables-operators': ['observable', 'Hermitian operator', 'commutator', 'operator'],
  'uncertainty-principle': ['uncertainty principle', 'Heisenberg uncertainty', 'uncertainty relation'],
  'quantum-harmonic-oscillator': ['harmonic oscillator', 'zero-point energy', 'ladder operator', 'creation operator', 'annihilation operator', 'raising operator'],
  'example-trap-oscillator': ['oscillator length'],
  spin: ['spin', 'Stern–Gerlach', 'angular momentum', 'spin-½'],
  'identical-particles': ['boson', 'fermion', 'identical particles', 'Pauli exclusion', 'spin–statistics'],
  entanglement: ['entanglement', 'entangled', 'Bell inequality', 'no-signalling'],
  decoherence: ['decoherence', 'density matrix', 'which-path', 'which path'],
  'second-quantization': ['second quantization', 'Fock space', 'occupation number', 'field operator'],
  'scattering-length': ['scattering length', 'Feshbach resonance', 's-wave scattering', 'contact interaction'],
  quasiparticles: ['quasiparticle', 'phonon', 'roton', 'phonon–roton', 'collective excitation'],
  'spontaneous-symmetry-breaking': ['spontaneous symmetry breaking', 'symmetry breaking', 'broken symmetry', 'Goldstone mode', 'Goldstone’s theorem', 'order parameter'],
  'laser-cooling': ['laser cooling', 'evaporative cooling', 'magneto-optical trap', 'optical molasses', 'Doppler cooling', 'Doppler limit'],
  interferometry: ['interferometry', 'interferometer', 'COW experiment', 'atom interferometer'],
  'quantum-field-theory': ['quantum field theory', 'QFT', 'quantum field'],
  regularization: ['regularization', 'renormalization', 'regularized', 'renormalize', 'counterterm'],
  'example-casimir': ['Casimir effect', 'Casimir force'],
  'example-tc-derivation': [],

  // ---------------------------------------------------------------- relativity & spacetime
  'speed-of-light': ['speed of light', 'light speed'],
  'sr-time-dilation': ['time dilation', 'Lorentz factor', 'twin paradox', 'light clock'],
  'example-muon': ['muon'],
  'gravitational-time-dilation': ['gravitational time dilation'],
  'schwarzschild-metric': ['Schwarzschild metric', 'Schwarzschild solution', 'Birkhoff’s theorem'],
  'example-schwarzschild-radii': [],
  'einstein-field-equations': ['Einstein field equations', 'Einstein’s equations', 'field equations', 'Einstein tensor', 'cosmological constant'],
  'example-gps': ['GPS'],
  'pound-rebka': ['Pound–Rebka'],
  'clocks-superposition-gravity': ['clock in superposition', 'quantum clock'],
  'principle-of-relativity': ['principle of relativity', 'inertial frame', 'Einstein’s postulates', 'postulates of relativity'],
  'lorentz-transformations': ['Lorentz transformation', 'Lorentz boost', 'length contraction', 'relativity of simultaneity', 'velocity addition', 'Lorentz invariance', 'Lorentz group'],
  'example-velocity-addition': [],
  'minkowski-spacetime': ['Minkowski spacetime', 'Minkowski space', 'spacetime interval', 'light cone', 'proper time', 'worldline'],
  'four-momentum': ['four-momentum', 'four-vector', 'mass–energy equivalence', 'rest mass', 'E = mc²'],
  'equivalence-principle': ['equivalence principle', 'free fall', 'freely falling'],
  geodesics: ['geodesic', 'geodesic equation'],
  'stress-energy-tensor': ['stress–energy tensor', 'energy–momentum tensor', 'perfect fluid'],
  'newtonian-limit': ['Newtonian limit', 'weak-field limit', 'weak field'],
  'gravitational-redshift': ['gravitational redshift', 'redshift', 'redshifted'],
  'black-holes': ['black hole', 'event horizon', 'Schwarzschild radius'],
  'atomic-clocks': ['atomic clock', 'optical clock', 'caesium clock', 'optical lattice clock'],
  'quantum-gravity-problem': ['quantum gravity', 'Planck length', 'Planck scale'],

  // ---------------------------------------------------------------- mathematical foundations
  'complex-numbers': ['complex number', 'Euler’s formula', 'imaginary unit', 'complex plane', 'complex amplitude'],
  calculus: ['calculus', 'Taylor series', 'Taylor expansion', 'derivative'],
  'infinite-series': ['geometric series', 'infinite series', 'power series', 'divergent sum', 'divergent series'],
  'generating-functions': ['generating function', 'q-series', 'q-expansion', 'graded dimension'],
  'linear-algebra': ['vector space', 'linear algebra', 'linear map', 'tensor product', 'inner product'],
  eigenvalues: ['eigenvalue', 'eigenvector', 'eigenstate', 'spectral theorem'],
  'differential-equations': ['differential equation', 'partial differential equation', 'ODE', 'PDE'],
  'vector-calculus': ['vector calculus', 'Stokes’ theorem', 'curl', 'divergence theorem'],
  'fourier-analysis': ['Fourier series', 'Fourier transform', 'Fourier analysis', 'Fourier mode'],
  probability: ['probability', 'expectation value', 'standard deviation', 'variance'],
  'complex-analysis': ['complex analysis', 'Laurent series', 'holomorphic', 'residue', 'analytic continuation', 'contour integral'],
  'riemann-zeta': ['Riemann zeta function', 'zeta function', 'ζ function'],
  'group-theory': ['group theory', 'symmetry group'],
  'normal-subgroups': ['normal subgroup', 'quotient group', 'Lagrange’s theorem', 'subgroup'],
  'finite-simple-groups': ['finite simple group', 'simple group', 'sporadic group', 'classification of finite simple groups', 'Happy Family', 'pariah'],
  'representation-theory': ['representation theory', 'representation', 'irreducible representation', 'character table', 'irreducible'],
  'example-s3-characters': [],
  'lie-algebras': ['Lie algebra', 'Lie group', 'generators of rotations'],
  lattices: ['lattice', 'theta function', 'theta series', 'unimodular', 'kissing number', 'Niemeier lattice'],
  'tori-elliptic-curves': ['torus', 'tori', 'elliptic curve', 'upper half-plane'],
  'modular-forms': ['modular form', 'modular function', 'modular group', 'cusp form'],
  'eisenstein-discriminant': ['Eisenstein series', 'Dedekind eta function', 'eta function', 'modular discriminant'],
  'example-j-from-e4': [],
  hauptmodul: ['Hauptmodul', 'Hauptmoduln', 'genus zero', 'genus-zero'],
  tensors: ['tensor', 'index notation', 'Einstein summation'],
  manifolds: ['manifold', 'tangent space'],
  'riemannian-geometry': ['curvature', 'Christoffel symbols', 'Riemann tensor', 'Ricci tensor', 'Ricci scalar', 'metric tensor', 'parallel transport'],

  // ---------------------------------------------------------------- classical & statistical physics
  'newtonian-mechanics': ['Newton’s laws', 'Newtonian mechanics', 'conservation of momentum', 'conservation of energy'],
  'newtonian-gravity': ['Newtonian gravity', 'gravitational potential', 'escape velocity', 'inverse-square law', 'Newton’s law of gravitation'],
  'waves-normal-modes': ['normal mode', 'wave equation', 'interference', 'standing wave', 'harmonics'],
  'dispersion-relations': ['dispersion relation', 'group velocity', 'phase velocity'],
  'lagrangian-mechanics': ['Lagrangian', 'least action', 'principle of least action', 'Euler–Lagrange'],
  'hamiltonian-mechanics': ['Hamiltonian', 'Poisson bracket', 'canonical quantization', 'Hamilton’s equations'],
  'noether-theorem': ['Noether’s theorem', 'conservation law', 'conserved current', 'conserved charge'],
  'maxwell-light': ['Maxwell’s equations', 'electromagnetism', 'electromagnetic wave', 'electromagnetic field'],
  thermodynamics: ['thermodynamics', 'entropy', 'chemical potential', 'absolute zero'],
  'statistical-mechanics': ['Boltzmann distribution', 'partition function', 'Boltzmann factor', 'statistical mechanics', 'grand canonical'],
  'density-of-states': ['density of states'],
  'fluid-dynamics': ['viscosity', 'viscous', 'Navier–Stokes', 'vorticity', 'Reynolds number', 'fluid dynamics'],

  // ---------------------------------------------------------------- miscellany
  'why-24': [],
  'how-to-use': [],
};
