// One-line hooks for links: why these two things are connected. Shown on "Where this leads"
// cards, in peeks and on the trail. [from, to, note] — matches a link in either direction.
// Merging only fills notes that are still empty.

export const NOTES = [
  // ---------------------------------------------------------------- string theory, core
  ['order-of-the-monster', 'monster-group', 'About 8 × 10⁵³ symmetries, factored into just 15 primes'],
  ['monstrous-moonshine', 'monster-group', 'Moonshine claims the j-function secretly counts Monster representations'],
  ['monstrous-moonshine', 'j-invariant', 'Its coefficients 196884, 21493760… are built from Monster dimensions'],
  ['example-mckay-196884', 'j-invariant', 'The number that started it: 196884 is j’s first interesting coefficient'],
  ['moonshine-module', 'leech-lattice', 'Start with 24 bosons curled up on the Leech lattice'],
  ['virasoro-algebra', 'vertex-operator-algebra', 'Every VOA contains a copy of the Virasoro algebra'],
  ['critical-dimension', 'bosonic-string', 'Why this string only works in 26 dimensions'],
  ['question-monster-universe', 'monster-group', 'Is this abstract symmetry part of real physics?'],
  ['question-monster-universe', 'moonshine-module', 'The one concrete place the Monster acts on a physical theory'],
  ['moonshine-module', 'lattice-voa', 'Its starting point: the Leech lattice VOA'],
  ['moonshine-module', 'orbifolds', 'A ℤ₂ orbifold removes 24 states and creates the Monster symmetry'],
  ['why-24', 'critical-dimension', '26 − 2 = 24 transverse directions'],
  ['why-24', 'leech-lattice', 'The Leech lattice only exists in 24 dimensions'],
  ['why-24', 'moonshine-module', 'Central charge exactly 24'],
  ['why-24', 'j-invariant', 'j = E₄³/Δ, and Δ = η²⁴'],
  ['why-24', 'torus-partition-function', 'The −c/24 vacuum energy is where 24 enters the modular story'],
  ['why-24', 'example-24-oscillators', '24 vibrating directions → the series 1/η²⁴'],
  ['why-24', 'eisenstein-discriminant', 'Δ = η²⁴ — a modular form with 24 built in'],
  ['why-24', 'example-leech-to-j', 'The 24 extra states the orbifold has to remove'],
  ['why-24', 'golay-m24', 'A perfect code on 24 bits, with a symmetry group named after 24'],
  ['question-monster-universe', 'ads-cft', 'Witten’s proposal: 3D gravity dual to the Monster CFT'],
  ['question-monster-universe', 'mathieu-umbral-moonshine', 'Newer moonshines sit closer to realistic string theory'],
  ['question-monster-universe', 'quantum-gravity-problem', 'Any real role would be inside a theory of quantum gravity'],

  // ---------------------------------------------------------------- quantum & extreme matter, core
  ['born-rule', 'superposition', 'How a superposition turns into probabilities when you look'],
  ['bose-einstein-condensate', 'bose-einstein-statistics', 'Condensation is what this distribution does when it runs out of room'],
  ['bec-critical-temperature', 'bose-einstein-statistics', 'Integrate the distribution and T_c falls out'],
  ['bec-critical-temperature', 'bose-einstein-condensate', 'When condensation starts, and how much has condensed'],
  ['gross-pitaevskii', 'bose-einstein-condensate', 'How the whole condensate moves, as one wavefunction'],
  ['superfluidity', 'bose-einstein-condensate', 'Condensates are superfluid; helium’s superfluidity comes from condensation'],
  ['landau-criterion', 'superfluidity', 'Why there is no friction below a critical speed'],
  ['bogoliubov-dispersion', 'gross-pitaevskii', 'Small ripples on the condensate: sound at long wavelengths'],
  ['quantized-circulation', 'superfluidity', 'Superfluids can only rotate by forming vortices'],
  ['sr-time-dilation', 'speed-of-light', 'Keep c the same for everyone and moving clocks must slow'],
  ['gravitational-time-dilation', 'schwarzschild-metric', 'Read it straight off the dt² term'],
  ['clocks-superposition-gravity', 'gravitational-time-dilation', 'Clocks tick differently at different heights…'],
  ['clocks-superposition-gravity', 'superposition', '…so what if one clock is at two heights at once?'],
  ['clocks-superposition-gravity', 'speed-of-light', 'The shift is gh/c² — c sets the scale'],
  ['superposition', 'hilbert-space', 'A superposition is just a vector sum in this space'],
  ['schrodinger-equation', 'observables-operators', 'The Hamiltonian operator drives time evolution'],
  ['schrodinger-equation', 'wave-particle-duality', 'A wave equation for matter waves'],
  ['schrodinger-equation', 'differential-equations', 'A linear PDE — which is why superpositions of solutions work'],
  ['born-rule', 'probability', 'Quantum mechanics predicts probabilities, nothing more'],
  ['born-rule', 'hilbert-space', 'Probability = squared length of a projection'],
  ['bose-einstein-statistics', 'statistical-mechanics', 'Sum a geometric series of Boltzmann factors'],
  ['bose-einstein-statistics', 'identical-particles', 'Only for bosons — fermions get +1 instead of −1'],
  ['bose-einstein-condensate', 'second-quantization', 'Millions of atoms in one mode: n₀ ~ N'],
  ['bec-critical-temperature', 'density-of-states', 'g(0) = 0 hides the ground state — where the condensate lives'],
  ['example-tc-derivation', 'riemann-zeta', 'The integral turns into Γ(3/2) ζ(3/2)'],
  ['gross-pitaevskii', 'scattering-length', 'One number, a_s, sets the whole nonlinearity g'],
  ['superfluidity', 'fluid-dynamics', 'Ordinary fluids have viscosity; superfluids have none'],
  ['superfluidity', 'quasiparticles', 'Friction would mean creating phonons or rotons'],
  ['superfluidity', 'spontaneous-symmetry-breaking', 'Flow is a gradient of the phase the fluid picked'],
  ['landau-criterion', 'dispersion-relations', 'v_c is the minimum of ε(p)/p — a phase velocity'],
  ['landau-criterion', 'quasiparticles', 'Helium’s roton minimum sets v_c ≈ 60 m/s'],
  ['bogoliubov-dispersion', 'quasiparticles', 'Bogoliubov’s phonons are the textbook quasiparticle'],
  ['quantized-circulation', 'fluid-dynamics', 'Ordinary vortices can have any strength; these can’t'],

  // ---------------------------------------------------------------- relativity, core
  ['speed-of-light', 'maxwell-light', 'Maxwell’s equations predict waves at exactly c'],
  ['speed-of-light', 'principle-of-relativity', 'Einstein’s second postulate'],
  ['sr-time-dilation', 'lorentz-transformations', 'Put a clock at x′ = 0 and read off t = γt′'],
  ['gravitational-time-dilation', 'equivalence-principle', 'An accelerating rocket’s top clock runs fast — so gravity does it too'],
  ['schwarzschild-metric', 'riemannian-geometry', 'A metric whose curvature is gravity'],
  ['einstein-field-equations', 'riemannian-geometry', 'The left side is pure curvature'],
  ['einstein-field-equations', 'stress-energy-tensor', 'The right side: what matter and energy are there'],
  ['einstein-field-equations', 'equivalence-principle', 'Gravity as geometry starts here'],
  ['einstein-field-equations', 'newtonian-gravity', 'Must reduce to ∇²Φ = 4πGρ'],
  ['example-gps', 'atomic-clocks', 'Every GPS satellite carries atomic clocks'],
  ['clocks-superposition-gravity', 'interferometry', 'Split a clock’s path and compare how much each branch aged'],
  ['clocks-superposition-gravity', 'atomic-clocks', 'Now precise enough to feel a 1 mm height difference'],
  ['clocks-superposition-gravity', 'quantum-gravity-problem', 'A lab-scale window onto quantum + gravity'],

  // ---------------------------------------------------------------- maths, internally
  ['infinite-series', 'calculus', 'Convergence is a limit — calculus again'],
  ['generating-functions', 'infinite-series', 'A whole sequence stored in one power series'],
  ['eigenvalues', 'linear-algebra', 'Directions a matrix only stretches'],
  ['differential-equations', 'calculus', 'Equations made of derivatives'],
  ['vector-calculus', 'calculus', 'Calculus for fields in 3D'],
  ['fourier-analysis', 'complex-numbers', 'e^{inx} makes every wave a spinning arrow'],
  ['fourier-analysis', 'infinite-series', 'A function as an infinite sum of waves'],
  ['complex-analysis', 'complex-numbers', 'Calculus where the variable is complex'],
  ['complex-analysis', 'infinite-series', 'Laurent series allow negative powers'],
  ['riemann-zeta', 'infinite-series', 'Starts as Σ 1/nˢ'],
  ['normal-subgroups', 'group-theory', 'How groups break into smaller pieces'],
  ['finite-simple-groups', 'normal-subgroups', 'Simple = no normal pieces: the atoms of symmetry'],
  ['representation-theory', 'group-theory', 'Groups acting on vector spaces'],
  ['representation-theory', 'linear-algebra', 'Each symmetry becomes a matrix'],
  ['lie-algebras', 'group-theory', 'Continuous groups, zoomed in near the identity'],
  ['lie-algebras', 'linear-algebra', 'Generators are matrices; the bracket is AB − BA'],
  ['lattices', 'linear-algebra', 'Integer combinations of basis vectors'],
  ['tori-elliptic-curves', 'lattices', 'A torus is the plane folded up by a lattice'],
  ['tori-elliptic-curves', 'complex-numbers', 'Its shape is a single complex number τ'],
  ['modular-forms', 'complex-analysis', 'Holomorphic functions with extra symmetry'],
  ['modular-forms', 'group-theory', 'SL(2,ℤ) acts on τ'],
  ['eisenstein-discriminant', 'modular-forms', 'The building blocks every modular form is made from'],
  ['eisenstein-discriminant', 'generating-functions', 'E₄ counts divisors; η counts partitions'],
  ['hauptmodul', 'modular-forms', 'When one modular function generates all the others'],
  ['tensors', 'linear-algebra', 'Multilinear algebra with coordinate rules'],
  ['tensors', 'calculus', 'Tensor fields change from point to point'],
  ['manifolds', 'calculus', 'Calculus on curved spaces'],
  ['manifolds', 'linear-algebra', 'Each point gets its own vector space of directions'],
  ['riemannian-geometry', 'manifolds', 'Add a way to measure lengths'],
  ['riemannian-geometry', 'tensors', 'Curvature is a four-index tensor'],

  // ---------------------------------------------------------------- physics, internally
  ['newtonian-mechanics', 'calculus', 'Newton invented calculus to do this'],
  ['newtonian-gravity', 'newtonian-mechanics', 'F = ma with F = GMm/r²'],
  ['waves-normal-modes', 'differential-equations', 'The wave equation'],
  ['waves-normal-modes', 'fourier-analysis', 'Any vibration is a sum of normal modes'],
  ['waves-normal-modes', 'newtonian-mechanics', 'F = ma applied to every bit of a string'],
  ['dispersion-relations', 'waves-normal-modes', 'How frequency depends on wavelength'],
  ['lagrangian-mechanics', 'newtonian-mechanics', 'Same physics, rewritten as “make the action stationary”'],
  ['hamiltonian-mechanics', 'lagrangian-mechanics', 'Swap velocities for momenta'],
  ['noether-theorem', 'lagrangian-mechanics', 'Symmetries of L give conserved quantities'],
  ['maxwell-light', 'vector-calculus', 'Written in div and curl'],
  ['maxwell-light', 'waves-normal-modes', 'Combine them and a wave equation appears'],
  ['statistical-mechanics', 'thermodynamics', 'Where temperature and entropy come from microscopically'],
  ['statistical-mechanics', 'probability', 'Each state gets probability e^{−E/kT}/Z'],
  ['statistical-mechanics', 'hamiltonian-mechanics', 'The energies E_i are the Hamiltonian’s'],
  ['density-of-states', 'statistical-mechanics', 'Turns sums over states into integrals'],
  ['fluid-dynamics', 'newtonian-mechanics', 'F = ma for a continuous blob'],
  ['fluid-dynamics', 'vector-calculus', 'Vorticity is the curl of the flow'],

  // ---------------------------------------------------------------- quantum, internally
  ['wave-particle-duality', 'waves-normal-modes', 'Matter gets a wavelength — and interferes'],
  ['hilbert-space', 'linear-algebra', 'Quantum states are vectors'],
  ['hilbert-space', 'complex-numbers', 'Amplitudes are complex — phases matter'],
  ['observables-operators', 'hilbert-space', 'Measurements are operators on the state space'],
  ['observables-operators', 'eigenvalues', 'Possible results = eigenvalues'],
  ['uncertainty-principle', 'observables-operators', 'Follows from [x, p] = iħ'],
  ['uncertainty-principle', 'probability', 'σ is a standard deviation'],
  ['quantum-harmonic-oscillator', 'observables-operators', 'Solved with ladder operators, not calculus'],
  ['quantum-harmonic-oscillator', 'differential-equations', 'Or solved as an ODE, with Hermite polynomials'],
  ['spin', 'observables-operators', 'Angular momentum operators that don’t commute'],
  ['spin', 'representation-theory', 'Spin s = the (2s+1)-dimensional representation of SU(2)'],
  ['identical-particles', 'spin', 'Integer spin → boson, half-integer → fermion'],
  ['identical-particles', 'hilbert-space', 'Only symmetric or antisymmetric states are allowed'],
  ['decoherence', 'entanglement', 'Entangling with the environment hides interference'],
  ['decoherence', 'superposition', 'Why big superpositions look classical'],
  ['second-quantization', 'quantum-harmonic-oscillator', 'Every mode is an oscillator; quanta are particles'],
  ['second-quantization', 'identical-particles', 'Counting occupations makes symmetry automatic'],
  ['scattering-length', 'schrodinger-equation', 'Low-energy scattering solutions collapse to one number'],
  ['quasiparticles', 'second-quantization', 'Collective excitations get their own creation operators'],
  ['quasiparticles', 'dispersion-relations', 'Each quasiparticle has its own ε(p)'],
  ['spontaneous-symmetry-breaking', 'noether-theorem', 'The symmetry is still there — the state just picked a side'],
  ['laser-cooling', 'maxwell-light', 'Light pushes atoms'],
  ['laser-cooling', 'thermodynamics', 'Evaporative cooling: let the hottest escape'],
  ['interferometry', 'wave-particle-duality', 'Interference only works because particles are waves'],
  ['interferometry', 'superposition', 'One particle, two paths, at once'],
  ['quantum-field-theory', 'second-quantization', 'Fock space made relativistic'],
  ['quantum-field-theory', 'lagrangian-mechanics', 'Every QFT starts from a Lagrangian'],
  ['quantum-field-theory', 'minkowski-spacetime', 'Fields must respect Lorentz symmetry'],
  ['regularization', 'infinite-series', 'Divergent sums need taming'],
  ['regularization', 'riemann-zeta', 'ζ(−1) = −1/12 is the finite part of 1 + 2 + 3 + ⋯'],

  // ---------------------------------------------------------------- relativity, internally
  ['principle-of-relativity', 'newtonian-mechanics', 'Galileo’s ship: uniform motion can’t be detected'],
  ['lorentz-transformations', 'principle-of-relativity', 'The only transformations that keep c fixed'],
  ['lorentz-transformations', 'speed-of-light', 'c is the one speed they leave unchanged'],
  ['minkowski-spacetime', 'lorentz-transformations', 'The geometry these transformations preserve'],
  ['four-momentum', 'minkowski-spacetime', 'Energy is the time component of momentum'],
  ['four-momentum', 'tensors', 'A four-vector: one upper index'],
  ['equivalence-principle', 'newtonian-gravity', 'Why everything falls at the same rate'],
  ['equivalence-principle', 'principle-of-relativity', 'Extends relativity to accelerating frames'],
  ['geodesics', 'riemannian-geometry', 'Straight lines in curved space use the Christoffel symbols'],
  ['geodesics', 'equivalence-principle', 'Free fall = following a geodesic'],
  ['stress-energy-tensor', 'tensors', 'A symmetric two-index tensor'],
  ['stress-energy-tensor', 'four-momentum', 'Four-momentum densities and their flows'],
  ['newtonian-limit', 'einstein-field-equations', 'Weak fields and slow speeds recover Newton'],
  ['newtonian-limit', 'newtonian-gravity', 'Φ hides in g₀₀'],
  ['gravitational-redshift', 'equivalence-principle', 'Einstein predicted it from the equivalence principle in 1907'],
  ['black-holes', 'schwarzschild-metric', 'Where 1 − r_s/r hits zero'],
  ['atomic-clocks', 'laser-cooling', 'The best clocks tick with laser-cooled atoms'],
  ['quantum-gravity-problem', 'einstein-field-equations', 'Classical geometry…'],
  ['quantum-gravity-problem', 'quantum-field-theory', '…meets quantum fields, and the infinities won’t cancel'],
  ['quantum-gravity-problem', 'black-holes', 'Black hole entropy hints at hidden quantum states'],

  // ---------------------------------------------------------------- strings, internally
  ['classical-string', 'lagrangian-mechanics', 'Action = area swept out by the string'],
  ['classical-string', 'minkowski-spacetime', 'A 1D object moving through 4D (or 26D) spacetime'],
  ['classical-string', 'waves-normal-modes', 'Its vibrations are normal modes — each one a particle'],
  ['light-cone-quantization', 'classical-string', 'Fix the gauge, keep only transverse wiggles'],
  ['light-cone-quantization', 'quantum-harmonic-oscillator', 'A string is an infinite tower of oscillators'],
  ['conformal-symmetry', 'complex-analysis', 'In 2D, every holomorphic map preserves angles'],
  ['conformal-symmetry', 'lie-algebras', 'Infinitely many generators: the Witt algebra'],
  ['conformal-field-theory', 'conformal-symmetry', 'A quantum theory built on that infinite symmetry'],
  ['conformal-field-theory', 'quantum-field-theory', 'A special, often exactly solvable, QFT'],
  ['operator-product-expansion', 'conformal-field-theory', 'How fields multiply when they collide'],
  ['torus-partition-function', 'conformal-field-theory', 'Put the CFT on a torus and count its states'],
  ['torus-partition-function', 'modular-forms', 'Torus shape only matters up to SL(2,ℤ) → modular invariance'],
  ['example-24-oscillators', 'critical-dimension', 'Level 1 has 24 states — a massless vector, which forces D = 26'],
  ['anomalies', 'noether-theorem', 'A classical symmetry that quantization breaks'],
  ['anomalies', 'quantum-field-theory', 'They appear when you quantize fields'],
  ['anomalies', 'regularization', 'The anomaly is the regulator’s fingerprint that won’t go away'],
  ['ghosts-no-ghost', 'virasoro-algebra', 'Virasoro constraints remove negative-norm states'],
  ['ghosts-no-ghost', 'anomalies', 'Ghosts bring c = −26 to cancel the anomaly'],
  ['compactification', 'lattices', 'A torus ℝᵈ/Λ is defined by a lattice'],
  ['compactification', 'bosonic-string', 'Curl up the string’s extra dimensions'],
  ['lattice-voa', 'vertex-operator-algebra', 'The most concrete family of VOAs'],
  ['lattice-voa', 'lattices', 'One momentum state per lattice point'],
  ['lattice-voa', 'compactification', 'Strings on a torus ℝᵈ/Λ, written as algebra'],
  ['orbifolds', 'group-theory', 'Divide out by a symmetry group'],
  ['golay-m24', 'finite-simple-groups', 'M₂₄ is one of the 26 sporadic groups'],
  ['borcherds-algebras', 'lie-algebras', 'Infinite-dimensional Lie algebras with imaginary roots'],
  ['borcherds-algebras', 'ghosts-no-ghost', 'Physical states of a 26D string form this algebra'],
  ['borcherds-algebras', 'lattices', 'Graded by the 2D Lorentzian lattice II₁,₁'],
  ['superstrings', 'bosonic-string', 'Add fermions: no tachyon, and D = 10'],
  ['mathieu-umbral-moonshine', 'monstrous-moonshine', 'The same kind of coincidence, for other groups'],
  ['mathieu-umbral-moonshine', 'golay-m24', 'M₂₄ — the Golay code’s symmetry group — shows up in K3 strings'],
  ['ads-cft', 'conformal-field-theory', 'The boundary side of the duality is a CFT'],
  ['ads-cft', 'einstein-field-equations', 'The bulk side is gravity with negative Λ'],
  ['ads-cft', 'black-holes', 'Bulk black holes = hot states of the boundary theory'],

  // ---------------------------------------------------------------- core topics → foundations
  ['monster-group', 'finite-simple-groups', 'The largest of the 26 sporadic simple groups'],
  ['monster-group', 'representation-theory', 'Its smallest representation has 196,883 dimensions'],
  ['order-of-the-monster', 'group-theory', 'The order is the number of symmetries'],
  ['j-invariant', 'modular-forms', 'The modular function every other one is built from'],
  ['monstrous-moonshine', 'hauptmodul', 'Conway–Norton: every Monster element gives a Hauptmodul'],
  ['monstrous-moonshine', 'generating-functions', 'Graded dimensions are generating functions'],
  ['vertex-operator-algebra', 'conformal-field-theory', 'The rigorous algebra behind a chiral CFT'],
  ['vertex-operator-algebra', 'operator-product-expansion', 'A VOA is a consistent set of OPEs'],
  ['virasoro-algebra', 'lie-algebras', 'An infinite-dimensional Lie algebra'],
  ['virasoro-algebra', 'anomalies', 'The c/12 term is a quantum anomaly'],
  ['leech-lattice', 'lattices', 'The most special lattice in 24 dimensions'],
  ['bosonic-string', 'classical-string', 'Quantize the Nambu–Goto string'],
  ['bosonic-string', 'light-cone-quantization', 'The cleanest way to see its spectrum'],
  ['critical-dimension', 'light-cone-quantization', 'Lorentz invariance must survive the gauge choice'],
  ['critical-dimension', 'regularization', 'Tame 1 + 2 + 3 + ⋯ and D = 26 appears'],
];
