// Links for the basics: among themselves, and from the fuller topics down to the basics they use.
// Same shape as links.js: [from, kind, to, note].

export const BASIC_LINKS = [
  // ---------------------------------------------------------------- the machine
  ['binary-numbers', 'builds-on', 'how-computers-run-code', 'What the numbers in memory actually look like'],
  ['how-computers-run-code', 'related', 'latency-numbers', 'Memory vs disk vs network: the gaps that shape every system'],
  ['how-computers-run-code', 'related', 'gpus', 'The other processor: thousands of simple cores'],
  ['operating-systems', 'builds-on', 'how-computers-run-code', 'The OS shares the CPU and memory between programs'],
  ['files-and-paths', 'builds-on', 'operating-systems', 'The OS organises storage into files and folders'],
  ['terminal', 'builds-on', 'files-and-paths', 'Every command runs from a working directory'],
  ['code-editors', 'builds-on', 'files-and-paths', 'You open a project folder, not single files'],
  ['code-editors', 'related', 'terminal', 'The editor has a terminal built in'],
  ['installing-tools', 'builds-on', 'terminal', 'Installs and checks happen in a terminal'],
  ['installing-tools', 'related', 'wsl', 'Docker Desktop installs WSL 2 along the way'],
  ['installing-tools', 'related', 'ollama', 'One of the installs'],
  ['wsl', 'builds-on', 'operating-systems', 'A real Linux running inside Windows'],
  ['ports-localhost', 'builds-on', 'operating-systems', 'Servers are processes the OS runs'],

  // ---------------------------------------------------------------- programming ideas
  ['programming-basics', 'builds-on', 'how-computers-run-code', 'Programs are instructions for the processor'],
  ['compilers-interpreters', 'builds-on', 'programming-basics', 'How your source code reaches the CPU'],
  ['variables-types', 'builds-on', 'programming-basics', 'The first idea in every language'],
  ['control-flow', 'builds-on', 'variables-types', 'Decisions and loops test and change variables'],
  ['functions-basics', 'builds-on', 'control-flow', 'A function packages a block of steps'],
  ['scope-closures', 'builds-on', 'functions-basics', 'Which names a function can see, and remember'],
  ['data-structures-basics', 'builds-on', 'variables-types', 'Collections are values that hold other values'],
  ['strings-text', 'builds-on', 'variables-types', 'Text is the type LLM apps handle most'],
  ['strings-text', 'related', 'bits-bytes-utf8', 'Characters on screen, bytes on disk'],
  ['oop', 'builds-on', 'functions-basics', 'Methods are functions attached to data'],
  ['mutability', 'builds-on', 'data-structures-basics', 'Lists and dicts can change in place; that’s where sharing bites'],
  ['errors-exceptions', 'builds-on', 'control-flow', 'An exception jumps out of the normal flow'],
  ['modules-imports', 'builds-on', 'functions-basics', 'Modules are files of functions and classes'],
  ['libraries-frameworks', 'builds-on', 'modules-imports', 'Someone else’s modules, installed'],
  ['functional-style', 'builds-on', 'functions-basics', 'Functions passed to functions'],
  ['functional-style', 'builds-on', 'mutability', 'Return new values instead of changing old ones'],
  ['algorithms-basics', 'builds-on', 'control-flow', 'Recipes built from decisions and loops'],
  ['reading-docs', 'builds-on', 'errors-exceptions', 'The error message is the first document to read'],
  ['debugging', 'builds-on', 'errors-exceptions', 'Start from the exception and its traceback'],
  ['debugging', 'related', 'reading-docs', 'Most fixes are one well-read error and one docs page away'],
  ['big-o', 'builds-on', 'algorithms-basics', 'How an algorithm’s work grows'],
  ['sorting', 'builds-on', 'algorithms-basics', 'The most studied algorithm there is'],
  ['binary-search', 'builds-on', 'sorting', 'It only works on sorted data'],
  ['recursion', 'builds-on', 'functions-basics', 'A function that calls itself'],
  ['concurrency', 'builds-on', 'operating-systems', 'Processes and threads are OS ideas'],
  ['event-loop', 'builds-on', 'data-structures-basics', 'A queue of ready tasks, first in, first out'],
  ['hash-maps', 'related', 'data-structures-basics', 'The other everyday container: lookup by key'],

  // ---------------------------------------------------------------- Python
  ['python-basics', 'builds-on', 'programming-basics', 'The same ideas, in Python’s spelling'],
  ['python-basics', 'related', 'compilers-interpreters', 'Python is interpreted, via bytecode'],
  ['python-collections', 'builds-on', 'python-basics', 'Python’s built-in containers'],
  ['python-collections', 'builds-on', 'data-structures-basics', 'Lists, and when to pick something else'],
  ['python-collections', 'related', 'hash-maps', 'A dict is a hash map'],
  ['python-collections', 'related', 'json', 'Lists and dicts map straight onto JSON'],
  ['python-files-context', 'builds-on', 'python-basics', 'Reading and writing files in Python'],
  ['python-files-context', 'builds-on', 'files-and-paths', 'Paths decide which file you open'],
  ['python-files-context', 'builds-on', 'errors-exceptions', 'Cleanup runs even when an exception flies'],
  ['python-type-hints', 'builds-on', 'variables-types', 'Types, written down for tools to check'],
  ['python-decorators', 'builds-on', 'scope-closures', 'A decorator returns a closure around your function'],
  ['python-generators', 'builds-on', 'control-flow', 'A loop that hands out one value at a time'],
  ['python-generators', 'builds-on', 'functions-basics', 'A function that pauses at each yield'],
  ['virtual-environments', 'builds-on', 'libraries-frameworks', 'A place for one project’s dependencies'],
  ['jupyter', 'builds-on', 'python-basics', 'Python, run cell by cell'],

  // ---------------------------------------------------------------- JavaScript
  ['javascript', 'builds-on', 'programming-basics', 'The same ideas, in the browser’s language'],
  ['js-values-types', 'builds-on', 'javascript', 'JavaScript’s own types and quirks'],
  ['js-values-types', 'builds-on', 'variables-types', 'Variables and types, JavaScript-flavoured'],
  ['js-functions', 'builds-on', 'js-values-types', 'Functions are values too'],
  ['js-functions', 'builds-on', 'functions-basics', 'Parameters and return values, JavaScript-style'],
  ['js-functions', 'related', 'scope-closures', 'Arrow functions close over the variables around them'],
  ['js-arrays-objects', 'builds-on', 'js-functions', 'map, filter and find take functions'],
  ['js-arrays-objects', 'builds-on', 'data-structures-basics', 'Arrays and objects are JavaScript’s containers'],
  ['js-arrays-objects', 'related', 'functional-style', 'The same style, applied to arrays'],
  ['js-arrays-objects', 'related', 'json', 'JSON is written in this syntax'],
  ['dom', 'builds-on', 'javascript', 'JavaScript is how you read and change the DOM'],
  ['dom-events', 'builds-on', 'dom', 'Events fire on DOM elements'],
  ['dom-events', 'builds-on', 'js-functions', 'Handlers are functions you hand to the browser'],
  ['event-loop', 'related', 'dom-events', 'Each event’s handler waits its turn on the loop'],
  ['modules-imports', 'related', 'npm', 'import pulls in installed packages too'],
  ['npm', 'builds-on', 'libraries-frameworks', 'The JavaScript world’s dependencies'],
  ['typescript', 'builds-on', 'compilers-interpreters', 'TypeScript is compiled to JavaScript'],
  ['typescript', 'builds-on', 'js-values-types', 'Types on top of JavaScript’s types'],

  // ---------------------------------------------------------------- web
  ['internet-basics', 'related', 'how-computers-run-code', 'Computers, connected'],
  ['tcp-ip', 'builds-on', 'internet-basics', 'IP is the internet’s addressing and delivery'],
  ['dns', 'builds-on', 'internet-basics', 'Names for internet addresses'],
  ['client-server', 'builds-on', 'internet-basics', 'Two programs talking across the network'],
  ['websites-web-apps', 'builds-on', 'client-server', 'A web app splits work between browser and server'],
  ['websites-web-apps', 'related', 'spa-vs-ssr', 'Which kind of web app to build'],
  ['project-layout', 'builds-on', 'websites-web-apps', 'The pieces of your app, as folders'],
  ['web-servers', 'builds-on', 'http', 'A server speaks HTTP'],
  ['web-servers', 'builds-on', 'ports-localhost', 'It listens on a port'],
  ['flask', 'builds-on', 'web-servers', 'Flask runs your code inside a web server'],
  ['flask', 'builds-on', 'python-basics', 'Flask is plain Python'],
  ['flask', 'builds-on', 'libraries-frameworks', 'A framework: it calls your functions when requests arrive'],
  ['react', 'builds-on', 'libraries-frameworks', 'A library that behaves like a framework'],
  ['html-forms', 'builds-on', 'html', 'Forms are HTML elements'],
  ['html-forms', 'related', 'http-methods', 'A form sends GET or POST'],
  ['react-forms', 'builds-on', 'html-forms', 'Same inputs and submit event, driven by state'],
  ['tls-https', 'builds-on', 'encryption', 'HTTPS is encryption plus certificates'],
  ['jwt', 'related', 'encryption', 'Signed with a secret or a private key'],
  ['password-hashing', 'tension', 'encryption', 'Hashing is one-way; encryption is meant to be undone'],

  // ---------------------------------------------------------------- SQL and data
  ['data-modeling', 'builds-on', 'relational-model', 'Entities become tables'],
  ['sql-select', 'builds-on', 'relational-model', 'Asking a relational database a question'],
  ['sql-joins', 'builds-on', 'sql-select', 'Queries across related tables'],
  ['sql-joins', 'builds-on', 'keys-constraints', 'Joins follow keys'],
  ['sql-aggregates', 'builds-on', 'sql-select', 'Summarise the rows a SELECT finds'],
  ['sql-ctes-windows', 'builds-on', 'sql-aggregates', 'Aggregates without collapsing rows'],
  ['sql-ctes-windows', 'builds-on', 'sql-joins', 'Big queries, in named steps'],
  ['sql-modify', 'builds-on', 'sql-select', 'Same WHERE clauses, now changing data'],
  ['normalization', 'builds-on', 'data-modeling', 'Store each fact once'],
  ['keys-constraints', 'builds-on', 'data-modeling', 'Relationships become foreign keys'],
  ['transactions-acid', 'builds-on', 'sql-modify', 'Several writes, all or nothing'],
  ['upsert-returning', 'builds-on', 'sql-modify', 'Better INSERTs and UPDATEs'],
  ['indexes', 'builds-on', 'sql-select', 'What makes a WHERE clause fast'],
  ['sql-injection', 'builds-on', 'sql-select', 'The attack rewrites your query text'],
  ['sqlalchemy', 'builds-on', 'oop', 'Tables become classes, rows become objects'],
  ['sqlalchemy', 'builds-on', 'sql-select', 'It writes SQL you should be able to read'],
  ['pandas', 'related', 'sql-aggregates', 'groupby and agg are GROUP BY, in Python'],
  ['llm-observability', 'related', 'sql-aggregates', 'Cost and latency reports are GROUP BY queries'],
  ['hybrid-search', 'related', 'sql-ctes-windows', 'Ranking two result lists and fusing them is window-function work'],

  // ---------------------------------------------------------------- maths
  ['exponents-logs', 'builds-on', 'functions-graphs', 'Two of the most important function shapes'],
  ['derivatives', 'builds-on', 'functions-graphs', 'The slope of a function’s graph'],
  ['partial-derivatives', 'builds-on', 'derivatives', 'Slopes along one input at a time'],
  ['chain-rule', 'builds-on', 'derivatives', 'Slopes of functions inside functions'],
  ['vectors-dot-product', 'builds-on', 'sigma-notation', 'A dot product is a sum of products'],
  ['linear-algebra-basics', 'builds-on', 'vectors-dot-product', 'Matrices are rows of vectors'],
  ['matrix-multiplication', 'builds-on', 'linear-algebra-basics', 'The operation, with its cost'],
  ['probability-distributions', 'builds-on', 'probability-basics', 'Probabilities over all outcomes at once'],
  ['mean-variance', 'builds-on', 'sigma-notation', 'An average is a sum divided by a count'],
  ['mean-variance', 'related', 'probability-distributions', 'μ and σ describe a distribution'],
  ['confidence-intervals', 'builds-on', 'mean-variance', 'The spread of an average'],
  ['confidence-intervals', 'builds-on', 'probability-distributions', 'The 1.96 comes from the bell curve'],
  ['entropy-information', 'builds-on', 'probability-basics', 'Surprise is measured from probabilities'],
  ['entropy-information', 'builds-on', 'exponents-logs', 'Information is a logarithm'],
  ['linear-regression', 'builds-on', 'functions-graphs', 'Fitting a straight line'],
  ['gradient-descent', 'builds-on', 'partial-derivatives', 'The gradient says which way is downhill'],
  ['backpropagation', 'builds-on', 'chain-rule', 'The chain rule, layer by layer'],
  ['softmax', 'builds-on', 'exponents-logs', 'Exponentials make every score positive'],
  ['softmax', 'builds-on', 'probability-basics', 'The outputs are probabilities that add to 1'],
  ['cross-entropy', 'builds-on', 'entropy-information', 'Average surprise at the right answer'],
  ['sampling-temperature', 'builds-on', 'probability-distributions', 'Reshaping a distribution, then sampling from it'],
  ['evals', 'builds-on', 'confidence-intervals', 'Every pass rate comes with error bars'],
  ['agents', 'related', 'probability-basics', 'Per-step success rates multiply'],
  ['activation-functions', 'related', 'functions-graphs', 'Shapes that bend straight lines'],
  ['activation-functions', 'related', 'probability-distributions', 'GELU uses the normal distribution’s CDF'],
  ['scaling-laws', 'related', 'exponents-logs', 'Power laws are straight lines on log–log plots'],
  ['big-o', 'related', 'exponents-logs', 'log n and 2ⁿ are the extremes of growth'],

  // ---------------------------------------------------------------- ML
  ['features-labels', 'builds-on', 'machine-learning', 'What supervised examples look like'],
  ['classification-regression', 'builds-on', 'features-labels', 'Is the label a category or a number?'],
  ['loss-functions', 'builds-on', 'classification-regression', 'Categories and numbers need different losses'],
  ['evaluation-metrics', 'builds-on', 'classification-regression', 'Judging a classifier beyond accuracy'],
  ['training-vs-inference', 'builds-on', 'machine-learning', 'Learning the weights vs using them'],
  ['training-loop', 'builds-on', 'gradient-descent', 'Many small steps downhill'],
  ['training-loop', 'builds-on', 'backpropagation', 'Each step needs gradients'],
  ['numpy', 'builds-on', 'linear-algebra-basics', 'Vectors and matrices as fast arrays'],
  ['numpy', 'builds-on', 'python-collections', 'Like lists of numbers, but fast'],
  ['pandas', 'builds-on', 'numpy', 'Tables built on NumPy arrays'],
  ['pytorch', 'builds-on', 'numpy', 'NumPy-like tensors, on GPUs, with gradients'],
  ['pytorch', 'builds-on', 'training-loop', 'The loop, in real code'],
  ['decision-trees-boosting', 'builds-on', 'classification-regression', 'Tree ensembles for tabular prediction'],
  ['llm-as-judge', 'builds-on', 'evaluation-metrics', 'Agreement with humans is measured like any classifier'],
  ['vector-search', 'related', 'evaluation-metrics', 'Retrieval is scored with recall@k'],
  ['fine-tuning', 'builds-on', 'training-loop', 'The same loop, on your examples'],
  ['fine-tuning', 'related', 'training-vs-inference', 'Fine-tuning is training; RAG and prompts only change inference'],
  ['next-token-prediction', 'related', 'classification-regression', 'Next-token prediction is classification over the vocabulary'],
  ['local-embeddings', 'related', 'pytorch', 'sentence-transformers runs on PyTorch'],
  ['llms', 'related', 'training-vs-inference', 'Every API call is inference; the weights never change'],

  // ---------------------------------------------------------------- CS basics
  ['bits-bytes-utf8', 'builds-on', 'binary-numbers', 'Bytes are 8 binary digits'],
  ['floating-point', 'builds-on', 'binary-numbers', 'Decimals stored as binary fractions'],
  ['quantization', 'related', 'binary-numbers', '4 bits give 16 levels'],
  ['hash-functions', 'related', 'binary-numbers', 'A 256-bit hash has 2²⁵⁶ possible values'],
  ['encryption', 'related', 'hash-functions', 'Two different tools: reversible vs one-way'],
  ['encryption', 'related', 'binary-numbers', 'Key strength doubles with every bit'],
  ['data-formats', 'related', 'json', 'JSON’s siblings'],
  ['data-formats', 'builds-on', 'strings-text', 'All of them are structured text'],
  ['fine-tuning', 'related', 'data-formats', 'Training data is usually JSON Lines'],
  // ---------------------------------------------------------------- stitching the main path together
  ['linters-formatters', 'related', 'code-editors', 'Format on save runs the formatter for you'],
  ['relational-model', 'related', 'data-formats', 'A CSV is a table without keys, types or rules'],
  ['urls', 'related', 'files-and-paths', 'A URL’s path looks like a file path — and once always was one'],
  ['html', 'related', 'websites-web-apps', 'Every web page and web app starts as an HTML document'],
  ['object-storage', 'builds-on', 'files-and-paths', 'Files, kept in a bucket instead of a folder'],
  ['functions-graphs', 'related', 'functions-basics', 'A maths function is a code function with no side effects'],
  ['sigma-notation', 'related', 'control-flow', 'Σ is a for-loop that adds'],
  ['probability-basics', 'related', 'sigma-notation', 'The probabilities of all outcomes sum to 1'],
  ['machine-learning', 'builds-on', 'functions-graphs', 'A trained model is a function fitted to examples'],
  ['tokenization', 'related', 'strings-text', 'Text, cut into model-sized pieces'],
];
