// Links for FastAPI and security, Google Cloud, web-data pipelines and the extra AI topics.
// Same shape as links.js: [from, kind, to, note].

export const EXTRA_LINKS = [
  // ---------------------------------------------------------------- FastAPI and async
  ['fastapi', 'builds-on', 'flask-vs-fastapi', 'The async, type-hinted option from that comparison'],
  ['fastapi', 'builds-on', 'input-validation', 'Pydantic validation is built in'],
  ['fastapi', 'builds-on', 'async-await', 'Routes are async functions'],
  ['fastapi', 'builds-on', 'asgi-uvicorn', 'Runs on an ASGI server'],
  ['fastapi', 'related', 'rest', 'Routers, paths and methods map onto REST'],
  ['fastapi', 'related', 'typescript', 'The OpenAPI schema can generate a typed client'],
  ['asgi-uvicorn', 'related', 'wsgi-gunicorn', 'The async successor to WSGI'],
  ['asgi-uvicorn', 'builds-on', 'event-loop', 'One event loop serves many requests'],
  ['fastapi-dependencies', 'builds-on', 'fastapi', 'FastAPI’s way to share setup between routes'],
  ['fastapi-dependencies', 'builds-on', 'python-generators', 'A yield dependency sets up and tears down'],
  ['fastapi-dependencies', 'related', 'testing', 'Override dependencies to test with fakes'],
  ['middleware', 'builds-on', 'fastapi', 'Wraps every request the app handles'],
  ['middleware', 'related', 'python-decorators', 'Both wrap a function to add behaviour around it'],
  ['middleware', 'related', 'cors', 'CORS headers are usually added by middleware'],
  ['async-sqlalchemy', 'builds-on', 'sqlalchemy', 'The same models and queries, awaited'],
  ['async-sqlalchemy', 'builds-on', 'fastapi', 'An async app needs an async database driver'],
  ['async-sqlalchemy', 'related', 'n-plus-one', 'No implicit lazy loading — load relationships up front'],
  ['async-sqlalchemy', 'related', 'connection-pooling', 'Every awaited query holds a pooled connection'],
  ['file-upload-processing', 'builds-on', 'fastapi', 'An upload endpoint'],
  ['file-upload-processing', 'related', 'background-jobs', 'Processing continues after the request returns'],
  ['file-upload-processing', 'related', 'hash-functions', 'A SHA-256 spots a file uploaded twice'],
  ['file-upload-processing', 'related', 'object-storage', 'Keep the original file'],
  ['schema-at-startup', 'builds-on', 'schema-migrations', 'The alternative it’s weighed against'],
  ['schema-at-startup', 'related', 'async-sqlalchemy', 'create_all runs from the models at start-up'],
  ['schema-at-startup', 'related', 'asgi-uvicorn', 'Start-up hooks are where it runs'],
  ['flask-vs-fastapi', 'related', 'async-sqlalchemy', 'Going async means the database layer too'],

  // ---------------------------------------------------------------- security for internal tools
  ['rbac', 'builds-on', 'authentication', 'Authorisation comes after knowing who someone is'],
  ['rbac', 'builds-on', 'middleware', 'One middleware enforces the role rules'],
  ['rbac', 'related', 'http-methods', 'Read-only roles can be defined by method: only GET'],
  ['rbac', 'related', 'owasp-top-ten', 'Broken access control is the top risk'],
  ['session-tokens', 'builds-on', 'authentication', 'How a login is remembered between requests'],
  ['session-tokens', 'related', 'jwt', 'Server-side sessions vs signed tokens'],
  ['session-tokens', 'related', 'cookies', 'Header or cookie: each needs its own defence'],
  ['session-tokens', 'related', 'hash-functions', 'Random tokens are unguessable; stored tokens can be hashed'],
  ['audit-trails', 'builds-on', 'rbac', 'Who did what, per role'],
  ['audit-trails', 'related', 'logging-monitoring', 'Audit logs are for accountability; app logs are for debugging'],
  ['audit-trails', 'related', 'sql-aggregates', 'Per-user summaries and flags are GROUP BY queries'],
  ['leak-deterrents', 'builds-on', 'rbac', 'The view-only role’s extra limits'],
  ['leak-deterrents', 'builds-on', 'audit-trails', 'Deterrence works because every view is recorded'],
  ['leak-deterrents', 'related', 'dom-events', 'Copy, print and focus events are what the page intercepts'],
  ['invite-reset-links', 'builds-on', 'password-hashing', 'Tokens are hashed at rest, like passwords'],
  ['invite-reset-links', 'related', 'session-tokens', 'Both are random, expiring secrets'],
  ['invite-reset-links', 'builds-on', 'transactional-email', 'The link arrives by email'],
  ['transactional-email', 'builds-on', 'dns', 'SPF, DKIM and DMARC are DNS records'],
  ['transactional-email', 'related', 'background-jobs', 'Send from a queue, retry failures'],
  ['least-privilege', 'builds-on', 'rbac', 'Roles are least privilege for people'],
  ['least-privilege', 'related', 'secrets', 'Scoped keys limit what a leak can do'],
  ['least-privilege', 'related', 'prompt-injection', 'Scope what a tricked model can reach'],
  ['least-privilege', 'related', 'oauth', 'Ask for read scopes only when that’s all you need'],

  // ---------------------------------------------------------------- Google Cloud
  ['google-cloud-basics', 'builds-on', 'deployment', 'A platform to deploy on'],
  ['google-cloud-basics', 'related', 'terminal', 'gcloud runs in the terminal'],
  ['google-cloud-basics', 'related', 'latency-bandwidth', 'Region choice is a latency choice'],
  ['iam-service-accounts', 'builds-on', 'google-cloud-basics', 'Access control for everything in a project'],
  ['iam-service-accounts', 'builds-on', 'least-privilege', 'Grant a service account only the roles it needs'],
  ['iam-service-accounts', 'related', 'secrets', 'Secret Manager instead of keys in .env files'],
  ['cloud-build-images', 'builds-on', 'docker', 'Builds your Dockerfile in the cloud'],
  ['cloud-build-images', 'builds-on', 'google-cloud-basics', 'A Google Cloud service'],
  ['cloud-build-images', 'related', 'hash-functions', 'An image digest is a content hash'],
  ['cloud-build-images', 'related', 'headless-browsers', 'A browser-capable base image is big but convenient'],
  ['cloud-run', 'builds-on', 'cloud-build-images', 'Runs the image a build produced'],
  ['cloud-run', 'builds-on', 'web-servers', 'Your container is the web server'],
  ['cloud-run', 'builds-on', 'iam-service-accounts', 'The service runs as a service account'],
  ['cloud-run', 'related', 'session-tokens', 'In-memory sessions pin an app to one instance'],
  ['cloud-run', 'related', 'reverse-proxy', 'Cloud Run provides the front door for you'],
  ['cloud-run-jobs', 'builds-on', 'cloud-run', 'Same containers, run to completion'],
  ['cloud-run-jobs', 'builds-on', 'background-jobs', 'Where long-running background work goes'],
  ['cloud-sql', 'builds-on', 'postgres', 'Managed PostgreSQL'],
  ['cloud-sql', 'builds-on', 'connection-pooling', 'The tier sets the connection limit your pools must fit'],
  ['cloud-sql', 'builds-on', 'iam-service-accounts', 'Connect as a service account with the Cloud SQL client role'],
  ['cloud-sql', 'related', 'backups', 'Automated backups and point-in-time recovery'],
  ['cloud-storage-gcs', 'builds-on', 'object-storage', 'Google’s object storage'],
  ['cloud-storage-gcs', 'builds-on', 'iam-service-accounts', 'Access is granted per bucket'],
  ['cloud-storage-gcs', 'related', 'json', 'Documents like JSON profiles live as objects'],

  // ---------------------------------------------------------------- web data pipelines
  ['data-pipelines', 'builds-on', 'background-jobs', 'Pipelines usually run as background work'],
  ['data-pipelines', 'related', 'idempotency', 'Idempotent stages make retries safe'],
  ['data-pipelines', 'related', 'functional-style', 'Stages are functions from one output to the next'],
  ['web-crawling', 'builds-on', 'data-pipelines', 'Fetching is the first real stage'],
  ['web-crawling', 'builds-on', 'http', 'A crawler is an HTTP client following links'],
  ['web-crawling', 'builds-on', 'calling-http-apis', 'Timeouts and client reuse matter just as much'],
  ['web-crawling', 'related', 'async-await', 'Crawl many sites concurrently while waiting on the network'],
  ['html-parsing', 'builds-on', 'web-crawling', 'What you do with a fetched page'],
  ['html-parsing', 'builds-on', 'html', 'Parsing means knowing HTML’s structure'],
  ['html-parsing', 'related', 'regex', 'Selectors for structure, regex for patterns in text'],
  ['headless-browsers', 'builds-on', 'web-crawling', 'The fallback when plain HTTP sees an empty page'],
  ['headless-browsers', 'builds-on', 'javascript', 'Needed because the page is built by JavaScript'],
  ['headless-browsers', 'related', 'spa-vs-ssr', 'Single-page apps are exactly the sites that need rendering'],
  ['headless-browsers', 'related', 'testing', 'Playwright also drives end-to-end tests'],
  ['blocked-cloud-ips', 'builds-on', 'web-crawling', 'What a crawler meets on protected sites'],
  ['blocked-cloud-ips', 'related', 'status-codes', '403s, 429s and challenge pages'],
  ['blocked-cloud-ips', 'related', 'rate-limiting', 'The other side of rate limiting'],
  ['search-apis', 'builds-on', 'calling-http-apis', 'A paid JSON API'],
  ['search-apis', 'builds-on', 'data-pipelines', 'Finding the source is a pipeline stage'],
  ['search-apis', 'related', 'token-cost', 'Metered per call, like model tokens'],
  ['scraping-responsibly', 'builds-on', 'web-crawling', 'The rules around crawling'],
  ['scraping-responsibly', 'related', 'least-privilege', 'Collect and expose only what the purpose needs'],
  ['spreadsheets-in-out', 'builds-on', 'data-formats', 'Excel and CSV in practice'],
  ['spreadsheets-in-out', 'builds-on', 'python-files-context', 'Reading and writing files in Python'],
  ['spreadsheets-in-out', 'related', 'bits-bytes-utf8', 'UTF-8 and the BOM that makes Excel behave'],
  ['spreadsheets-in-out', 'related', 'pandas', 'read_excel and DataFrames'],
  ['messy-input-files', 'builds-on', 'spreadsheets-in-out', 'What real business files look like'],
  ['messy-input-files', 'builds-on', 'strings-text', 'Cleaning is string handling'],
  ['messy-input-files', 'related', 'input-validation', 'Validate at the door, with reasons'],
  ['india-addresses-geo', 'builds-on', 'messy-input-files', 'Addresses are the messiest field of all'],
  ['india-addresses-geo', 'related', 'regex', 'A regex finds six-digit pincodes'],
  ['entity-resolution', 'builds-on', 'messy-input-files', 'Clean records before matching them'],
  ['entity-resolution', 'builds-on', 'keys-constraints', 'Strong identifiers are keys'],
  ['entity-resolution', 'related', 'trees-graphs', 'Matches form a graph of connected records'],
  ['entity-resolution', 'related', 'evaluation-metrics', 'False matches vs missed matches: precision and recall'],
  ['fuzzy-matching', 'builds-on', 'entity-resolution', 'How names are compared'],
  ['fuzzy-matching', 'builds-on', 'strings-text', 'String similarity'],
  ['fuzzy-matching', 'related', 'exponents-logs', 'IDF is a logarithm of rarity'],
  ['fuzzy-matching', 'related', 'embeddings', 'Semantic similarity, useful for descriptions, risky for names'],
  ['provenance-evidence', 'builds-on', 'data-pipelines', 'Every stage keeps where its facts came from'],
  ['provenance-evidence', 'builds-on', 'keys-constraints', 'Items point at evidence rows'],
  ['provenance-evidence', 'related', 'hallucination', 'Quotes you can check keep a model honest'],
  ['provenance-evidence', 'related', 'rag', 'Stored sources make citations free'],
  ['heuristics-flags', 'builds-on', 'entity-resolution', 'Rules decide the grey zone of matching'],
  ['heuristics-flags', 'builds-on', 'provenance-evidence', 'Reviewers need the evidence in front of them'],
  ['heuristics-flags', 'related', 'agents', 'Humans in the loop for uncertain cases'],
  ['rule-based-scoring', 'builds-on', 'provenance-evidence', 'Each signal records what fired it'],
  ['rule-based-scoring', 'related', 'linear-regression', 'Fit the weights from outcomes once you have them'],
  ['rule-based-scoring', 'related', 'sigma-notation', 'A weighted sum'],
  ['worker-pools', 'builds-on', 'background-jobs', 'Many workers draining one queue'],
  ['worker-pools', 'builds-on', 'isolation-levels', 'FOR UPDATE SKIP LOCKED makes claims safe'],
  ['worker-pools', 'related', 'littles-law', 'In flight = rate × time each takes'],
  ['stop-rules', 'builds-on', 'worker-pools', 'A shared stop flag stops every worker together'],
  ['stop-rules', 'related', 'status-codes', '429 means stop or slow down'],
  ['stop-rules', 'related', 'idempotency', 'Stop cleanly, resume safely'],
  ['stop-rules', 'related', 'calling-http-apis', 'Retry transient errors; stop on persistent ones'],
  ['snapshots-diffs', 'builds-on', 'sql-joins', 'A diff is a LEFT JOIN between snapshots'],
  ['snapshots-diffs', 'builds-on', 'file-upload-processing', 'Each upload becomes a snapshot'],
  ['snapshots-diffs', 'related', 'git', 'Versions and diffs, for data'],

  // ---------------------------------------------------------------- more AI
  ['gemini-api', 'builds-on', 'llm-api', 'The same ideas, Google’s SDK'],
  ['gemini-api', 'related', 'structured-output', 'response_schema with a Pydantic model'],
  ['gemini-api', 'related', 'embeddings', 'gemini-embedding-001 and output dimensions'],
  ['gemini-api', 'related', 'stop-rules', 'Repeated 429s should stop a run'],
  ['llm-extraction', 'builds-on', 'structured-output', 'Extraction returns schema-checked JSON'],
  ['llm-extraction', 'builds-on', 'html-parsing', 'The model reads parsed page text'],
  ['llm-extraction', 'builds-on', 'provenance-evidence', 'Every fact comes with its quote'],
  ['llm-extraction', 'related', 'context-window', 'How many pages fit decides what the model sees'],
  ['llm-extraction', 'related', 'evals', 'Measure accuracy per field on labelled examples'],
  ['semantic-search-product', 'builds-on', 'hybrid-search', 'Filters plus meaning'],
  ['semantic-search-product', 'builds-on', 'pgvector', 'Vectors next to the rows'],
  ['semantic-search-product', 'related', 'sql-ctes-windows', 'One best chunk per company with DISTINCT ON'],
  ['knowledge-graphs', 'builds-on', 'trees-graphs', 'Nodes and edges'],
  ['knowledge-graphs', 'builds-on', 'entity-resolution', 'Resolved entities become nodes; match rules propose edges'],
  ['knowledge-graphs', 'builds-on', 'recursion', 'Traversals are recursive CTEs'],
  ['knowledge-graphs', 'related', 'jsonb', 'Edge properties as JSONB'],
  ['graphrag', 'builds-on', 'knowledge-graphs', 'Communities come from the graph'],
  ['graphrag', 'builds-on', 'rag', 'Retrieval, extended with summaries of communities'],
  ['text-to-sql', 'builds-on', 'sql-select', 'The model writes SELECTs'],
  ['text-to-sql', 'builds-on', 'least-privilege', 'Run it on a read-only database user'],
  ['text-to-sql', 'builds-on', 'prompt-engineering', 'Table descriptions and examples are the prompt'],
  ['text-to-sql', 'related', 'sql-injection', 'Model-written SQL is untrusted input too'],
  ['text-to-sql', 'tension', 'rag', 'Structured facts vs text passages: route questions to the right one'],
];
