// [from, kind, to, note]. "builds-on" and "derived-from" point from a topic to what you need first;
// "A part-of B" means A comes first. Every link except "example of" says why it's interesting.

export const LINKS = [
  // ---------------------------------------------------------------- how the web works
  ['open-a-url', 'builds-on', 'dns', 'Step one: turn the name into an address'],
  ['open-a-url', 'builds-on', 'tcp-ip', 'Step two: open a connection, one round trip'],
  ['open-a-url', 'builds-on', 'tls-https', 'Step three: agree on keys and check the certificate'],
  ['open-a-url', 'builds-on', 'http', 'Step four: the request and response themselves'],
  ['open-a-url', 'builds-on', 'browser-rendering', 'Step five: bytes become pixels'],
  ['open-a-url', 'related', 'latency-bandwidth', 'Each step costs round trips, and round trips add up'],
  ['client-server', 'part-of', 'open-a-url', 'The browser is the client; your Flask app is the server'],
  ['http', 'builds-on', 'tcp-ip', 'HTTP/1.1 and HTTP/2 ride on a TCP connection'],
  ['http', 'builds-on', 'client-server', 'A request goes out, a response comes back'],
  ['http', 'builds-on', 'urls', 'Every request names its target with a URL'],
  ['http-methods', 'builds-on', 'http', 'The verb at the start of every request line'],
  ['status-codes', 'builds-on', 'http', 'The three digits at the start of every response'],
  ['http-methods', 'related', 'idempotency', 'Safe to retry or not — the property that separates PUT from POST'],
  ['tls-https', 'builds-on', 'tcp-ip', 'TLS wraps a TCP connection in encryption'],
  ['tls-https', 'related', 'hash-functions', 'Certificates are signatures over hashes'],
  ['dns', 'related', 'web-caching-cdn', 'CDNs use DNS to send each user to the nearest copy'],
  ['html', 'part-of', 'browser-rendering', 'The first thing parsed, into the DOM'],
  ['css', 'part-of', 'browser-rendering', 'Render-blocking: nothing paints until it arrives'],
  ['dom', 'builds-on', 'html', 'The DOM is the HTML, parsed into live objects'],
  ['dom', 'builds-on', 'trees-graphs', 'It is literally a tree of nodes'],
  ['css', 'builds-on', 'html', 'Selectors pick HTML elements to style'],
  ['javascript', 'related', 'event-loop', 'Single-threaded, so everything waits its turn on the loop'],
  ['json', 'related', 'javascript', 'Its syntax is JavaScript’s object literal syntax'],
  ['json', 'related', 'hash-maps', 'A JSON object is a hash map on the wire'],
  ['apis', 'builds-on', 'http', 'Web APIs are HTTP endpoints'],
  ['apis', 'builds-on', 'json', 'The usual payload format'],
  ['rest', 'builds-on', 'http-methods', 'REST maps create/read/update/delete onto the methods'],
  ['rest', 'special-case-of', 'apis', 'The most common style of web API'],
  ['rest', 'builds-on', 'urls', 'Resources live at paths like /api/notes/42'],
  ['cookies', 'builds-on', 'http', 'Set-Cookie and Cookie are just HTTP headers'],
  ['cookies', 'explains', 'authentication', 'How a login survives stateless HTTP'],
  ['cors', 'builds-on', 'urls', 'An origin is scheme + host + port from the URL'],
  ['cors', 'builds-on', 'http', 'Enforced through response headers and preflight requests'],
  ['cors', 'related', 'cookies', 'Without it, other sites could read responses sent with your cookies'],
  ['web-caching-cdn', 'builds-on', 'http', 'Cache-Control, ETag and 304 are HTTP features'],
  ['web-caching-cdn', 'special-case-of', 'caching', 'The web’s caches, from browser to CDN'],
  ['web-caching-cdn', 'related', 'hash-functions', 'Content-hashed filenames make “cache forever” safe'],
  ['sse-websockets', 'builds-on', 'http', 'SSE is an HTTP response that never quite ends'],
  ['browser-rendering', 'builds-on', 'dom', 'Layout and paint work on the DOM tree'],
  ['latency-bandwidth', 'builds-on', 'tcp-ip', 'Handshakes and slow start are why round trips dominate'],
  ['latency-bandwidth', 'related', 'latency-numbers', 'The same table, from the network’s side'],
  ['xss', 'builds-on', 'javascript', 'The attack is getting your page to run someone else’s script'],
  ['xss', 'builds-on', 'dom', 'Untrusted text inserted into the DOM as HTML'],
  ['xss', 'related', 'cookies', 'HttpOnly cookies are the reason a successful XSS can’t steal the session'],
  ['csrf', 'builds-on', 'cookies', 'Works because browsers attach cookies automatically'],
  ['csrf', 'related', 'cors', 'CORS stops reading responses; CSRF is about side effects, which CORS doesn’t stop'],
  ['owasp-top-ten', 'related', 'xss', 'Injection in the browser'],
  ['owasp-top-ten', 'related', 'sql-injection', 'Injection in the database'],
  ['owasp-top-ten', 'related', 'authentication', 'Broken access control and authentication failures top the list'],
  ['owasp-top-ten', 'related', 'prompt-injection', 'The newest member of the injection family'],

  // ---------------------------------------------------------------- React & the frontend
  ['react', 'builds-on', 'javascript', 'React is a JavaScript library'],
  ['react', 'builds-on', 'dom', 'It exists to keep the DOM in sync with your data'],
  ['jsx', 'builds-on', 'react', 'The syntax React components are written in'],
  ['jsx', 'builds-on', 'html', 'HTML-shaped, with JavaScript in curly braces'],
  ['components-props', 'builds-on', 'react', 'React apps are built from components'],
  ['components-props', 'builds-on', 'jsx', 'A component is a function returning JSX'],
  ['react-state', 'builds-on', 'components-props', 'Props come from outside; state is remembered inside'],
  ['react-state', 'builds-on', 'react', 'UI = f(state): state is the “state” part'],
  ['react-rendering', 'builds-on', 'react-state', 'State changes trigger renders'],
  ['react-rendering', 'builds-on', 'trees-graphs', 'Reconciliation diffs two trees'],
  ['react-rendering', 'related', 'big-o', 'Keys and type rules turn O(n³) tree diffing into O(n)'],
  ['lists-keys', 'builds-on', 'react-rendering', 'Keys tell reconciliation which item is which'],
  ['use-effect', 'builds-on', 'react-state', 'Effects run after renders and often set state'],
  ['react-hooks', 'builds-on', 'react-state', 'useState is the first hook everyone meets'],
  ['react-hooks', 'builds-on', 'use-effect', 'useEffect is the other'],
  ['react-hooks', 'related', 'caching', 'useMemo and useCallback are memoisation'],
  ['react-forms', 'builds-on', 'react-state', 'A controlled input’s value lives in state'],
  ['react-forms', 'related', 'input-validation', 'Client checks for convenience, server checks for security'],
  ['fetching-data', 'builds-on', 'use-effect', 'The naive version fetches in an effect'],
  ['fetching-data', 'builds-on', 'apis', 'It calls your Flask API'],
  ['fetching-data', 'builds-on', 'async-await', 'fetch returns a Promise'],
  ['fetching-data', 'related', 'n-plus-one', 'Request waterfalls are the frontend’s N+1'],
  ['fetching-data', 'related', 'caching', 'TanStack Query is a cache keyed by query'],
  ['sharing-state', 'builds-on', 'react-state', 'Where state lives decides who can see it'],
  ['sharing-state', 'builds-on', 'components-props', 'Lifting state up means passing it down as props'],
  ['client-routing', 'builds-on', 'urls', 'Routes are URL paths mapped to components'],
  ['client-routing', 'related', 'flask-routes', 'Same idea on each side — and the server must hand unknown paths to the SPA'],
  ['typescript', 'builds-on', 'javascript', 'JavaScript plus types, compiled away'],
  ['typescript', 'same-idea', 'python-type-hints', 'Annotations checked by a tool, invisible at runtime'],
  ['vite', 'builds-on', 'npm', 'Installed and run through npm scripts'],
  ['vite', 'related', 'cors', 'Its dev proxy makes CORS problems disappear'],
  ['vite', 'related', 'web-caching-cdn', 'Hashed filenames in every build'],
  ['vite', 'related', 'env-vars', 'VITE_ variables are public — never secrets'],
  ['npm', 'same-idea', 'virtual-environments', 'package.json + lockfile ≈ pyproject.toml + uv.lock'],
  ['styling', 'builds-on', 'css', 'Every approach is CSS underneath'],
  ['styling', 'related', 'accessibility', 'Component libraries earn their keep with accessible widgets'],
  ['spa-vs-ssr', 'builds-on', 'client-routing', 'An SPA routes in the browser'],
  ['spa-vs-ssr', 'builds-on', 'browser-rendering', 'The trade is about when HTML appears'],
  ['streaming-chat-ui', 'builds-on', 'sse-websockets', 'Reads a Server-Sent Events stream'],
  ['streaming-chat-ui', 'builds-on', 'react-state', 'Each token is a state update'],
  ['streaming-chat-ui', 'builds-on', 'fetching-data', 'A fetch whose body arrives in pieces'],
  ['streaming-chat-ui', 'related', 'xss', 'Model output rendered as Markdown must be sanitised'],
  ['accessibility', 'builds-on', 'html', 'Most of it is using the right element'],
  ['effect-runs-twice', 'builds-on', 'use-effect', 'StrictMode deliberately re-runs effects'],
  ['effect-runs-twice', 'related', 'idempotency', 'Effects that are safe to repeat are the goal'],
  ['devtools', 'related', 'http', 'The Network tab shows every request and response'],
  ['devtools', 'related', 'debugging', 'The frontend half of the debugging toolkit'],
  ['react-2013', 'example-of', 'react', ''],

  // ---------------------------------------------------------------- Flask & Python backend
  ['flask', 'builds-on', 'http', 'Flask turns HTTP requests into function calls'],
  ['flask', 'builds-on', 'client-server', 'It is the server half'],
  ['flask', 'builds-on', 'virtual-environments', 'Installed into a project environment'],
  ['flask-routes', 'builds-on', 'flask', 'URLs mapped to functions'],
  ['flask-routes', 'builds-on', 'python-decorators', '@app.route is a decorator'],
  ['flask-routes', 'builds-on', 'http-methods', 'Each route declares which methods it accepts'],
  ['flask-request-response', 'builds-on', 'flask', 'What a view reads and returns'],
  ['flask-request-response', 'builds-on', 'json', 'request.get_json() in, dicts out as JSON'],
  ['flask-app-factory', 'builds-on', 'flask-routes', 'Blueprints group routes'],
  ['flask-app-factory', 'related', 'testing', 'A factory gives each test its own app'],
  ['wsgi-gunicorn', 'builds-on', 'flask', 'How Flask runs in production'],
  ['wsgi-gunicorn', 'builds-on', 'concurrency', 'Workers are processes; threads share them'],
  ['wsgi-gunicorn', 'builds-on', 'littles-law', 'Concurrent requests = arrival rate × duration'],
  ['calling-http-apis', 'builds-on', 'http', 'Your server becomes the client'],
  ['calling-http-apis', 'related', 'idempotency', 'Retries are only safe for idempotent calls'],
  ['sqlalchemy', 'builds-on', 'relational-model', 'Maps tables to classes and rows to objects'],
  ['sqlalchemy', 'builds-on', 'python-type-hints', 'SQLAlchemy 2.0 builds columns from Mapped[...] hints'],
  ['sqlalchemy', 'builds-on', 'transactions-acid', 'The session is a unit of work in one transaction'],
  ['authentication', 'builds-on', 'cookies', 'Session logins ride on cookies'],
  ['authentication', 'builds-on', 'password-hashing', 'Passwords are checked against slow hashes'],
  ['oauth', 'builds-on', 'authentication', 'Outsourcing the “who are you” to Google or GitHub'],
  ['oauth', 'builds-on', 'jwt', 'The ID token is a JWT'],
  ['oauth', 'related', 'mcp', 'Remote MCP servers connect to services with OAuth'],
  ['jwt', 'builds-on', 'base64', 'Three base64url parts'],
  ['jwt', 'builds-on', 'hash-functions', 'The signature is an HMAC or public-key signature'],
  ['jwt', 'tension', 'cookies', 'Stateless tokens vs revocable sessions'],
  ['password-hashing', 'builds-on', 'hash-functions', 'Hashing, made deliberately slow and salted'],
  ['password-hashing', 'related', 'big-o', 'Each extra character multiplies the search space'],
  ['input-validation', 'builds-on', 'python-type-hints', 'Pydantic turns type hints into validators'],
  ['input-validation', 'related', 'structured-output', 'The same schemas validate what models return'],
  ['input-validation', 'related', 'owasp-top-ten', 'Mass assignment and oversized input are classic holes'],
  ['flask-errors', 'builds-on', 'status-codes', 'Exceptions become the right status code'],
  ['flask-errors', 'related', 'logging-monitoring', 'Log the traceback, return a clean message'],
  ['background-jobs', 'builds-on', 'concurrency', 'Work moves to separate worker processes'],
  ['background-jobs', 'builds-on', 'idempotency', 'Jobs run at least once, so they must be safe to repeat'],
  ['background-jobs', 'related', 'isolation-levels', 'SKIP LOCKED turns a table into a job queue'],
  ['redis', 'related', 'caching', 'Its most common job'],
  ['redis', 'related', 'hash-maps', 'A networked hash map, with extras'],
  ['redis', 'related', 'background-jobs', 'The usual broker for RQ and Celery'],
  ['flask-streaming', 'builds-on', 'python-generators', 'A generator yields each event'],
  ['flask-streaming', 'builds-on', 'sse-websockets', 'Sends Server-Sent Events'],
  ['flask-streaming', 'builds-on', 'llm-api', 'Relays a streamed model reply'],
  ['flask-streaming', 'related', 'wsgi-gunicorn', 'Each open stream holds a worker'],
  ['flask-streaming', 'related', 'reverse-proxy', 'Proxy buffering silently breaks streaming'],
  ['rate-limiting', 'builds-on', 'status-codes', 'Answers 429 Too Many Requests'],
  ['rate-limiting', 'related', 'token-cost', 'The guard between a script loop and your API bill'],
  ['rate-limiting', 'related', 'redis', 'Shared counters across workers'],
  ['flask-vs-fastapi', 'builds-on', 'flask', 'What you have'],
  ['flask-vs-fastapi', 'builds-on', 'async-await', 'The main difference is async-first'],
  ['project-layout', 'builds-on', 'flask-app-factory', 'The backend half'],
  ['project-layout', 'builds-on', 'vite', 'The frontend half'],
  ['project-layout', 'builds-on', 'docker-compose', 'Postgres and Redis for development'],
  ['project-layout', 'builds-on', 'env-vars', '.env and .env.example'],
  ['python-generators', 'related', 'big-o', 'Constant memory instead of O(n)'],

  // ---------------------------------------------------------------- Postgres & data
  ['postgres', 'builds-on', 'relational-model', 'A relational database, extended'],
  ['keys-constraints', 'builds-on', 'relational-model', 'Keys are how tables relate'],
  ['normalization', 'builds-on', 'keys-constraints', 'Splitting tables means foreign keys between them'],
  ['column-types', 'builds-on', 'postgres', 'Postgres’s rich type system'],
  ['column-types', 'related', 'floating-point', 'Why money is never a float'],
  ['column-types', 'related', 'time-and-timezones', 'timestamptz stores instants in UTC'],
  ['column-types', 'related', 'hash-functions', 'Random UUIDs and the birthday bound'],
  ['indexes', 'builds-on', 'trees-graphs', 'A B-tree is a balanced tree of pages'],
  ['indexes', 'builds-on', 'binary-search', 'Each page is binary-searched'],
  ['indexes', 'builds-on', 'big-o', 'O(log n) lookups instead of O(n) scans'],
  ['explain-analyze', 'builds-on', 'indexes', 'The first thing a plan tells you is whether an index was used'],
  ['transactions-acid', 'builds-on', 'relational-model', 'The guarantee that made databases trustworthy'],
  ['isolation-levels', 'builds-on', 'transactions-acid', 'The “I” in ACID, in detail'],
  ['isolation-levels', 'builds-on', 'concurrency', 'Races between concurrent requests'],
  ['mvcc-vacuum', 'builds-on', 'transactions-acid', 'How Postgres gives each transaction its snapshot'],
  ['mvcc-vacuum', 'explains', 'isolation-levels', 'Snapshots are what isolation levels choose between'],
  ['connection-pooling', 'builds-on', 'postgres', 'Each connection is a server process'],
  ['connection-pooling', 'builds-on', 'littles-law', 'Pool size = queries/s × hold time'],
  ['connection-pooling', 'related', 'transactions-acid', 'Long transactions hold connections'],
  ['n-plus-one', 'builds-on', 'sqlalchemy', 'Lazy loading in an ORM causes it'],
  ['n-plus-one', 'builds-on', 'latency-bandwidth', 'Each query pays a round trip'],
  ['pagination', 'builds-on', 'indexes', 'Keyset pagination rides an index'],
  ['pagination', 'related', 'base64', 'Cursors are usually base64-encoded sort keys'],
  ['upsert-returning', 'builds-on', 'keys-constraints', 'ON CONFLICT needs a unique constraint'],
  ['upsert-returning', 'explains', 'idempotency', 'The Postgres tool for safe retries'],
  ['jsonb', 'builds-on', 'json', 'JSON stored in a parsed, indexable binary form'],
  ['jsonb', 'tension', 'normalization', 'Flexibility against structure'],
  ['full-text-search', 'builds-on', 'indexes', 'GIN indexes make it fast'],
  ['pgvector', 'builds-on', 'postgres', 'An extension — Postgres’s extensibility at work'],
  ['pgvector', 'builds-on', 'embeddings', 'It stores and searches embedding vectors'],
  ['pgvector', 'builds-on', 'cosine-similarity', 'Its <=> operator is cosine distance'],
  ['pgvector', 'builds-on', 'vector-search', 'HNSW and IVFFlat are approximate nearest-neighbour indexes'],
  ['sql-injection', 'builds-on', 'relational-model', 'The attack targets SQL text'],
  ['sql-injection', 'same-idea', 'prompt-injection', 'Untrusted data read as instructions — but prompts have no parameterisation'],
  ['sql-injection', 'same-idea', 'xss', 'The same mistake in the browser'],
  ['schema-migrations', 'builds-on', 'sqlalchemy', 'Alembic compares models to the database'],
  ['schema-migrations', 'related', 'git', 'A chain of versions, committed with the code'],
  ['backups', 'builds-on', 'postgres', 'pg_dump and WAL archiving'],
  ['backups', 'related', 'availability-nines', 'Recovery time is part of availability'],
  ['postgres-origins', 'example-of', 'postgres', ''],
  ['gitlab-2017', 'example-of', 'backups', ''],

  // ---------------------------------------------------------------- AI & ML foundations
  ['loss-functions', 'builds-on', 'machine-learning', 'The loss is the part of the recipe that defines “better”'],
  ['gradient-descent', 'builds-on', 'machine-learning', 'The optimiser is how the learning actually happens'],
  ['linear-regression', 'builds-on', 'vectors-dot-product', 'The prediction is a dot product plus a bias'],
  ['linear-regression', 'builds-on', 'loss-functions', 'Least squares minimises mean squared error'],
  ['linear-regression', 'example-of', 'machine-learning', ''],
  ['matrix-multiplication', 'builds-on', 'vectors-dot-product', 'A grid of dot products'],
  ['gradient-descent', 'builds-on', 'loss-functions', 'It minimises the loss'],
  ['softmax', 'builds-on', 'vectors-dot-product', 'Turns a vector of scores into probabilities'],
  ['cross-entropy', 'builds-on', 'softmax', 'The loss on softmax probabilities'],
  ['cross-entropy', 'special-case-of', 'loss-functions', 'The loss for choosing among options'],
  ['neural-networks', 'builds-on', 'matrix-multiplication', 'Each layer is a matrix multiply'],
  ['neural-networks', 'builds-on', 'activation-functions', 'The nonlinearity that makes depth worthwhile'],
  ['neural-networks', 'builds-on', 'linear-regression', 'A network is stacked linear models with bends in between'],
  ['backpropagation', 'builds-on', 'neural-networks', 'How every weight in every layer gets its gradient'],
  ['backpropagation', 'builds-on', 'gradient-descent', 'Supplies the gradients gradient descent needs'],
  ['overfitting', 'builds-on', 'machine-learning', 'The central danger of learning from examples'],
  ['overfitting', 'related', 'evals', 'Tuning prompts on your eval set overfits it the same way'],
  ['decision-trees-boosting', 'builds-on', 'machine-learning', 'Learning from examples without neurons'],
  ['decision-trees-boosting', 'related', 'trees-graphs', 'Each model is literally a tree of questions'],
  ['embeddings', 'builds-on', 'vectors-dot-product', 'An embedding is a vector'],
  ['embeddings', 'builds-on', 'neural-networks', 'Produced by a trained network'],
  ['cosine-similarity', 'builds-on', 'vectors-dot-product', 'The dot product divided by both lengths'],
  ['cosine-similarity', 'builds-on', 'embeddings', 'How embeddings are compared'],
  ['tokenization', 'related', 'bits-bytes-utf8', 'BPE starts from UTF-8 bytes — why Indian scripts cost more tokens'],
  ['strawberry-question', 'builds-on', 'tokenization', 'The model sees tokens, not letters'],
  ['strawberry-question', 'related', 'tool-use', 'A one-line code tool gets it right every time'],
  ['attention', 'builds-on', 'softmax', 'Scores become weights through a softmax'],
  ['attention', 'builds-on', 'matrix-multiplication', 'QKᵀ and the weighted sum of V are matmuls'],
  ['attention', 'builds-on', 'embeddings', 'Queries, keys and values are projections of token embeddings'],
  ['attention', 'related', 'big-o', 'Every token looks at every other: O(n²)'],
  ['transformer', 'builds-on', 'attention', 'The block’s first half'],
  ['transformer', 'builds-on', 'neural-networks', 'The block’s second half is an MLP'],
  ['transformer', 'builds-on', 'backpropagation', 'Residual connections exist so gradients flow through depth'],
  ['positional-encoding', 'builds-on', 'transformer', 'Order has to be added in'],
  ['positional-encoding', 'related', 'context-window', 'RoPE scaling is how contexts get stretched'],
  ['next-token-prediction', 'builds-on', 'transformer', 'The architecture being trained'],
  ['next-token-prediction', 'builds-on', 'cross-entropy', 'The loss it minimises'],
  ['next-token-prediction', 'builds-on', 'tokenization', 'Predicts tokens, not words'],
  ['sampling-temperature', 'builds-on', 'softmax', 'Temperature divides the logits before the softmax'],
  ['sampling-temperature', 'builds-on', 'next-token-prediction', 'How a distribution becomes a chosen token'],
  ['parameter-count', 'builds-on', 'transformer', 'Counting what’s inside each block'],
  ['parameter-count', 'related', 'model-memory', 'Parameters × bytes = the memory you need'],
  ['training-compute', 'builds-on', 'parameter-count', 'FLOPs scale with parameters'],
  ['training-compute', 'builds-on', 'matrix-multiplication', '2 FLOPs per parameter per token come from matmuls'],
  ['training-compute', 'builds-on', 'backpropagation', 'The backward pass is why it’s 6, not 2'],
  ['scaling-laws', 'builds-on', 'training-compute', 'Compute budget C ≈ 6ND'],
  ['scaling-laws', 'builds-on', 'cross-entropy', 'The loss being predicted'],
  ['fine-tuning', 'builds-on', 'next-token-prediction', 'Continues training a pretrained model'],
  ['fine-tuning', 'builds-on', 'gradient-descent', 'More gradient steps, on your data'],
  ['lora', 'special-case-of', 'fine-tuning', 'Fine-tuning a thin slice of new parameters'],
  ['lora', 'builds-on', 'matrix-multiplication', 'A low-rank update is a thin matrix times a wide one'],
  ['lora', 'related', 'quantization', 'QLoRA trains adapters on a 4-bit base'],
  ['rlhf', 'builds-on', 'fine-tuning', 'Post-training, after supervised fine-tuning'],
  ['rlhf', 'explains', 'llms', 'How a document predictor becomes an assistant'],
  ['reasoning-models', 'builds-on', 'rlhf', 'Reinforcement learning, with verifiable rewards'],
  ['reasoning-models', 'related', 'token-cost', 'Thinking tokens are billed as output'],
  ['reasoning-models', 'related', 'llm-latency', 'Thinking happens before the first answer token'],
  ['gpus', 'explains', 'matrix-multiplication', 'Hardware built for exactly this operation'],
  ['gpus', 'related', 'tokens-per-second', 'Bandwidth, not FLOPs, sets single-user generation speed'],
  ['mixture-of-experts', 'builds-on', 'transformer', 'Replaces each block’s MLP with routed experts'],
  ['mixture-of-experts', 'related', 'tokens-per-second', 'Only active experts are read per token — fast for its size'],
  ['distillation', 'builds-on', 'fine-tuning', 'Fine-tuning on a teacher’s outputs'],
  ['distillation', 'related', 'open-weight-families', 'Why small open models punch above their size'],
  ['diffusion-models', 'builds-on', 'neural-networks', 'A network trained to predict noise'],
  ['diffusion-models', 'tension', 'next-token-prediction', 'Refine everything in parallel vs one token at a time'],
  ['perceptron-1958', 'example-of', 'neural-networks', ''],
  ['alexnet-2012', 'example-of', 'gpus', ''],
  ['word2vec-2013', 'example-of', 'embeddings', ''],
  ['attention-paper-2017', 'example-of', 'transformer', ''],

  // ---------------------------------------------------------------- building with LLMs
  ['llms', 'builds-on', 'next-token-prediction', 'Pretraining is where the ability comes from'],
  ['llms', 'builds-on', 'transformer', 'The architecture under every one'],
  ['llm-api', 'builds-on', 'llms', 'Calling one from code'],
  ['llm-api', 'builds-on', 'apis', 'An HTTPS API with JSON in and out'],
  ['llm-api', 'related', 'env-vars', 'The API key lives in the environment, on the server'],
  ['token-cost', 'builds-on', 'tokenization', 'You pay per token'],
  ['token-cost', 'builds-on', 'llm-api', 'Every response reports its usage'],
  ['context-window', 'builds-on', 'tokenization', 'Measured in tokens'],
  ['context-window', 'builds-on', 'attention', 'Attention over n tokens is what gets expensive'],
  ['context-window', 'related', 'kv-cache', 'Locally, context length is paid for in KV-cache memory'],
  ['conversation-memory', 'builds-on', 'llm-api', 'The API is stateless'],
  ['conversation-memory', 'builds-on', 'context-window', 'History must fit'],
  ['conversation-memory', 'related', 'big-o', 'Resending history makes total cost quadratic'],
  ['prompt-engineering', 'builds-on', 'llm-api', 'The prompt is the program'],
  ['structured-output', 'builds-on', 'json', 'The output is JSON'],
  ['structured-output', 'builds-on', 'prompt-engineering', 'A schema is part of the instructions'],
  ['tool-use', 'builds-on', 'llm-api', 'Tool definitions go in the request; tool calls come back'],
  ['tool-use', 'builds-on', 'structured-output', 'Tool arguments are JSON matching a schema'],
  ['agents', 'builds-on', 'tool-use', 'An agent is tool use in a loop'],
  ['agents', 'related', 'idempotency', 'Retried steps repeat tool calls'],
  ['mcp', 'builds-on', 'tool-use', 'A standard way to offer tools to any AI app'],
  ['mcp', 'related', 'agents', 'Where agents get their tools'],
  ['rag', 'builds-on', 'embeddings', 'Retrieval by meaning'],
  ['rag', 'builds-on', 'vector-search', 'Find the nearest chunks'],
  ['rag', 'builds-on', 'prompt-engineering', 'Retrieved chunks go into the prompt'],
  ['chunking', 'builds-on', 'rag', 'The first step of indexing'],
  ['chunking', 'related', 'tokenization', 'Chunk sizes are measured in tokens'],
  ['vector-search', 'builds-on', 'cosine-similarity', 'Nearest means most similar'],
  ['vector-search', 'related', 'big-o', 'Brute force is O(n); ANN indexes trade recall for speed'],
  ['vector-search', 'related', 'trees-graphs', 'HNSW is a graph you hop through'],
  ['hybrid-search', 'builds-on', 'vector-search', 'The meaning half'],
  ['hybrid-search', 'builds-on', 'full-text-search', 'The keyword half'],
  ['hybrid-search', 'builds-on', 'rag', 'Retrieval that actually works'],
  ['evals', 'builds-on', 'llms', 'Measuring a probabilistic component'],
  ['evals', 'related', 'testing', 'Tests check correctness; evals check quality'],
  ['llm-as-judge', 'builds-on', 'evals', 'Grading at scale'],
  ['hallucination', 'builds-on', 'next-token-prediction', 'Plausible continuations aren’t always true'],
  ['hallucination', 'builds-on', 'loss-functions', 'The loss rewards plausibility, not truth'],
  ['rag', 'explains', 'hallucination', 'Grounding answers in sources is the main defence'],
  ['prompt-injection', 'builds-on', 'prompt-engineering', 'Instructions and data share one channel'],
  ['prompt-injection', 'related', 'agents', 'Agents that read untrusted content and can act are the risk'],
  ['prompt-injection', 'related', 'xss', 'Model output shown as HTML can carry the attack further'],
  ['llm-latency', 'builds-on', 'next-token-prediction', 'Output is generated one token at a time'],
  ['llm-latency', 'builds-on', 'latency-bandwidth', 'Network time before the model even starts'],
  ['llm-latency', 'related', 'sse-websockets', 'Streaming hides decode time from users'],
  ['prompt-caching', 'builds-on', 'kv-cache', 'It is the KV cache, kept between requests'],
  ['prompt-caching', 'special-case-of', 'caching', 'Caching a model’s work on a shared prefix'],
  ['prompt-caching', 'related', 'token-cost', 'The biggest free cost lever'],
  ['prompt-caching', 'related', 'conversation-memory', 'Each chat turn’s prompt starts with the last one'],
  ['llm-observability', 'builds-on', 'llm-api', 'Log every call’s request, usage and response'],
  ['llm-observability', 'builds-on', 'logging-monitoring', 'Ordinary logging, with tokens and cost'],
  ['llm-observability', 'related', 'jsonb', 'Raw requests and responses fit a JSONB column'],
  ['choosing-a-model', 'builds-on', 'evals', 'The eval decides'],
  ['choosing-a-model', 'related', 'local-llms', 'Hosted vs local is one of the axes'],
  ['choosing-a-model', 'related', 'token-cost', 'Cost per request at your volume'],
  ['prompt-rag-or-finetune', 'builds-on', 'rag', 'Option two'],
  ['prompt-rag-or-finetune', 'builds-on', 'fine-tuning', 'Option three'],
  ['prompt-rag-or-finetune', 'builds-on', 'prompt-engineering', 'Option one, always first'],
  ['llm-frameworks', 'related', 'rag', 'LlamaIndex packages the RAG pipeline'],
  ['llm-frameworks', 'related', 'agents', 'LangGraph models agents as state machines'],
  ['multimodal-input', 'builds-on', 'llm-api', 'Images and PDFs as content blocks'],
  ['multimodal-input', 'builds-on', 'base64', 'Files travel base64-encoded inside JSON'],
  ['multimodal-input', 'related', 'chunking', 'Convert PDF pages to clean text before chunking'],
  ['rag-walkthrough', 'example-of', 'rag', ''],
  ['rag-walkthrough', 'builds-on', 'pgvector', 'Vectors live next to the rows'],
  ['rag-walkthrough', 'builds-on', 'background-jobs', 'Ingestion runs in a worker'],
  ['rag-walkthrough', 'builds-on', 'flask-streaming', 'The answer streams back'],
  ['rag-walkthrough', 'builds-on', 'hybrid-search', 'Retrieval with vectors and keywords'],
  ['gpt3-2020', 'example-of', 'prompt-engineering', ''],
  ['chatgpt-2022', 'example-of', 'rlhf', ''],

  // ---------------------------------------------------------------- local AI
  ['local-llms', 'builds-on', 'llms', 'The same models, on your own hardware'],
  ['ollama', 'builds-on', 'local-llms', 'The easiest way in'],
  ['ollama', 'builds-on', 'llama-cpp', 'Built on llama.cpp'],
  ['ollama', 'builds-on', 'ports-localhost', 'A server on localhost:11434'],
  ['llama-cpp', 'builds-on', 'gguf', 'Loads GGUF files'],
  ['llama-cpp', 'builds-on', 'quantization', 'Made 4-bit local inference practical'],
  ['gguf', 'builds-on', 'quantization', 'Stores quantised tensors'],
  ['gguf', 'builds-on', 'tokenization', 'Carries the tokenizer with the weights'],
  ['quantization', 'builds-on', 'floating-point', 'Fewer bits per number than floats'],
  ['quantization', 'builds-on', 'parameter-count', 'Bits per weight × parameters = size'],
  ['model-memory', 'builds-on', 'quantization', 'Weights = parameters × bits ÷ 8'],
  ['model-memory', 'builds-on', 'kv-cache', 'Plus memory for the context'],
  ['kv-cache', 'builds-on', 'attention', 'Stores every earlier token’s keys and values'],
  ['kv-cache', 'related', 'caching', 'Memoisation inside the model'],
  ['tokens-per-second', 'builds-on', 'matrix-multiplication', 'One-token matmuls are memory-bound'],
  ['tokens-per-second', 'builds-on', 'model-memory', 'Every active byte is read once per token'],
  ['tokens-per-second', 'related', 'amdahls-law', 'Speed up generation and prompt processing becomes the bottleneck'],
  ['open-weight-families', 'builds-on', 'local-llms', 'What you can download'],
  ['open-weight-families', 'related', 'mixture-of-experts', 'Many of the best local models are MoE'],
  ['model-names', 'builds-on', 'open-weight-families', 'Family and version come first'],
  ['model-names', 'builds-on', 'quantization', 'Q4_K_M and friends at the end'],
  ['model-names', 'builds-on', 'mixture-of-experts', 'A3B means 3 billion active'],
  ['local-embeddings', 'builds-on', 'embeddings', 'Small embedding models run on a CPU'],
  ['local-embeddings', 'related', 'bits-bytes-utf8', 'Multilingual models matter for Indian-language text'],
  ['openai-compatible-apis', 'builds-on', 'llm-api', 'One request shape many servers speak'],
  ['openai-compatible-apis', 'related', 'ollama', 'Ollama serves it at /v1'],
  ['serving-vllm', 'builds-on', 'tokens-per-second', 'Batching exploits memory-bound generation'],
  ['serving-vllm', 'builds-on', 'kv-cache', 'PagedAttention packs many users’ caches'],
  ['serving-vllm', 'related', 'littles-law', 'Concurrent sequences = arrival rate × generation time'],
  ['local-hardware', 'builds-on', 'gpus', 'Memory and bandwidth decide what runs'],
  ['local-hardware', 'builds-on', 'model-memory', 'Will it fit?'],
  ['local-hardware', 'related', 'wsl', 'CUDA works inside WSL on Windows'],
  ['speculative-decoding', 'builds-on', 'tokens-per-second', 'Checking k tokens costs about the same as generating one'],
  ['speculative-decoding', 'related', 'distillation', 'The draft is a small model from the same family'],
  ['local-chat-apps', 'related', 'ollama', 'Front ends for the same local models'],
  ['flask-ollama-walkthrough', 'builds-on', 'ollama', 'Calls its REST API'],
  ['flask-ollama-walkthrough', 'builds-on', 'flask-streaming', 'Relays the stream as SSE'],
  ['flask-ollama-walkthrough', 'builds-on', 'local-embeddings', 'Embeddings for RAG, locally'],
  ['flask-ollama-walkthrough', 'related', 'docker-compose', 'host.docker.internal reaches Ollama from a container'],
  ['llama-leak-2023', 'example-of', 'local-llms', ''],
  ['llama-leak-2023', 'related', 'llama-cpp', 'llama.cpp appeared a week after the weights leaked'],
  ['deepseek-r1-2025', 'example-of', 'reasoning-models', ''],
  ['deepseek-r1-2025', 'related', 'mixture-of-experts', 'Built on a 671B-parameter MoE'],

  // ---------------------------------------------------------------- tools & shipping
  ['wsl', 'builds-on', 'terminal', 'A Linux shell on Windows'],
  ['ports-localhost', 'builds-on', 'tcp-ip', 'A port picks the program on the machine'],
  ['git', 'builds-on', 'terminal', 'Driven from the command line'],
  ['git', 'builds-on', 'hash-functions', 'Every commit is named by its hash'],
  ['git-branching', 'builds-on', 'git', 'Branches are labels on commits'],
  ['git-branching', 'related', 'trees-graphs', 'History is a directed acyclic graph'],
  ['github-prs', 'builds-on', 'git-branching', 'A pull request proposes merging a branch'],
  ['env-vars', 'builds-on', 'terminal', 'Set in the shell or a .env file'],
  ['secrets', 'builds-on', 'env-vars', 'Secrets come from the environment'],
  ['secrets', 'related', 'git', 'Committed once, in history forever'],
  ['docker', 'builds-on', 'terminal', 'Built and run from the command line'],
  ['docker', 'builds-on', 'ports-localhost', 'Port mapping and 0.0.0.0'],
  ['docker-compose', 'builds-on', 'docker', 'Several containers, one file'],
  ['testing', 'builds-on', 'flask-app-factory', 'Fixtures build a fresh app per test'],
  ['ci-cd', 'builds-on', 'testing', 'Runs the tests on every push'],
  ['ci-cd', 'builds-on', 'github-prs', 'Checks show on each pull request'],
  ['deployment', 'builds-on', 'wsgi-gunicorn', 'The backend process'],
  ['deployment', 'builds-on', 'env-vars', 'Config and secrets come from the platform'],
  ['deployment', 'builds-on', 'dns', 'A domain pointing at your server'],
  ['deployment', 'related', 'ci-cd', 'Merging to main can deploy automatically'],
  ['reverse-proxy', 'builds-on', 'tls-https', 'Terminates HTTPS'],
  ['reverse-proxy', 'builds-on', 'deployment', 'The front door on a server'],
  ['reverse-proxy', 'related', 'cors', 'One origin for frontend and API — no CORS needed'],
  ['logging-monitoring', 'related', 'debugging', 'Production debugging starts with the logs'],
  ['availability-nines', 'related', 'deployment', 'What “up” means, in numbers'],
  ['availability-nines', 'related', 'llm-api', 'Every hosted model is another dependency in the chain'],
  ['debugging', 'related', 'binary-search', 'Halving the problem, including git bisect'],
  ['linters-formatters', 'related', 'ci-cd', 'The same checks run in CI'],
  ['ai-coding-assistants', 'builds-on', 'agents', 'Coding agents are agents with file and shell tools'],
  ['ai-coding-assistants', 'related', 'testing', 'Tests are how an agent — and you — know the change works'],
  ['object-storage', 'related', 'background-jobs', 'Uploads kick off processing jobs'],
  ['object-storage', 'related', 'hash-functions', 'Key files by content hash to deduplicate'],
  ['git-2005', 'example-of', 'git', ''],
  ['knight-capital-2012', 'example-of', 'deployment', ''],
  ['crowdstrike-2024', 'example-of', 'availability-nines', ''],
  ['crowdstrike-2024', 'related', 'ci-cd', 'Staged rollouts are a deploy-pipeline feature'],
  ['left-pad-2016', 'example-of', 'npm', ''],
  ['xz-backdoor-2024', 'related', 'left-pad-2016', 'Two faces of the dependency supply chain'],

  // ---------------------------------------------------------------- CS fundamentals
  ['hash-maps', 'builds-on', 'hash-functions', 'Keys become array positions through a hash'],
  ['hash-maps', 'builds-on', 'big-o', 'O(1) on average'],
  ['binary-search', 'builds-on', 'big-o', 'The classic O(log n)'],
  ['recursion', 'related', 'trees-graphs', 'Trees are defined recursively'],
  ['concurrency', 'related', 'amdahls-law', 'Parallelism is capped by the serial part'],
  ['async-await', 'builds-on', 'event-loop', 'Syntax over an event loop'],
  ['async-await', 'builds-on', 'concurrency', 'Concurrency without threads'],
  ['event-loop', 'related', 'concurrency', 'One thread, many waits'],
  ['floating-point', 'builds-on', 'bits-bytes-utf8', 'Numbers as bit patterns'],
  ['hash-functions', 'builds-on', 'bits-bytes-utf8', 'Bytes in, fixed-size fingerprint out'],
  ['caching', 'related', 'latency-numbers', 'Caches exist because the numbers differ by orders of magnitude'],
  ['littles-law', 'related', 'caching', 'Faster responses mean fewer requests in flight'],
  ['base64', 'builds-on', 'bits-bytes-utf8', 'Bytes rewritten as safe text characters'],
  ['regex', 'related', 'bits-bytes-utf8', 'Patterns over text'],
  ['time-and-timezones', 'related', 'floating-point', 'Another representation with a hard limit'],
  ['heartbleed-2014', 'example-of', 'tls-https', ''],
  ['heartbleed-2014', 'related', 'input-validation', 'Never trust a length the client sends'],
  ['log4shell-2021', 'related', 'prompt-injection', 'Data treated as instructions — the pattern prompt injection repeats'],
  ['log4shell-2021', 'related', 'logging-monitoring', 'A logging library was the attack surface'],
  ['javascript-1995', 'example-of', 'javascript', ''],
  ['web-invented-1989', 'example-of', 'http', ''],
  ['web-invented-1989', 'related', 'urls', 'URLs were one of its three inventions'],

  // ---------------------------------------------------------------- stories and ideas
  ['turing-1950', 'related', 'evals', 'From “does it seem intelligent?” to “does it get this right?”'],
  ['dartmouth-1956', 'related', 'ai-winters', 'The optimism that set up the first winter'],
  ['perceptron-1958', 'related', 'ai-winters', 'Minsky and Papert’s critique helped bring the first one'],
  ['ai-winters', 'related', 'bitter-lesson-2019', 'Each revival came from methods that scaled'],
  ['alexnet-2012', 'related', 'activation-functions', 'ReLU was one of its key ingredients'],
  ['alexnet-2012', 'related', 'scaling-laws', 'More data and compute beat cleverness — later made quantitative'],
  ['word2vec-2013', 'related', 'cosine-similarity', 'Analogies are measured by cosine similarity'],
  ['attention-paper-2017', 'related', 'positional-encoding', 'Introduced sinusoidal position encodings'],
  ['bitter-lesson-2019', 'related', 'scaling-laws', 'General methods plus compute keep winning'],
  ['gpt3-2020', 'related', 'scaling-laws', 'In-context learning emerged with scale'],
  ['chatgpt-2022', 'related', 'llms', 'The moment LLMs became everyone’s business'],
  ['deepseek-r1-2025', 'related', 'distillation', 'Released small distilled versions for local use'],
  ['react-2013', 'related', 'react-rendering', 'The virtual DOM made re-rendering cheap'],
  ['javascript-1995', 'related', 'floating-point', 'All JavaScript numbers are float64'],
  ['postgres-origins', 'related', 'pgvector', 'Extensibility from 1986 made pgvector possible'],
  ['gitlab-2017', 'related', 'terminal', 'A command run in the wrong terminal'],
  ['knight-capital-2012', 'related', 'rate-limiting', 'Automatic spending needs kill switches and limits'],
];
