// [from, kind, to, note?]. "builds-on" / "derived-from" point from a topic to what you need first.

export const FOUNDATION_LINKS = [
  // ---------------------------------------------------------------- maths, internally
  ['infinite-series', 'builds-on', 'calculus'],
  ['generating-functions', 'builds-on', 'infinite-series'],
  ['eigenvalues', 'builds-on', 'linear-algebra'],
  ['differential-equations', 'builds-on', 'calculus'],
  ['vector-calculus', 'builds-on', 'calculus'],
  ['fourier-analysis', 'builds-on', 'complex-numbers'],
  ['fourier-analysis', 'builds-on', 'infinite-series'],
  ['fourier-analysis', 'related', 'linear-algebra', 'Functions as vectors; waves as a basis'],
  ['complex-analysis', 'builds-on', 'complex-numbers'],
  ['complex-analysis', 'builds-on', 'infinite-series'],
  ['riemann-zeta', 'builds-on', 'infinite-series'],
  ['riemann-zeta', 'builds-on', 'complex-analysis', 'Analytic continuation to s = −1'],
  ['normal-subgroups', 'builds-on', 'group-theory'],
  ['finite-simple-groups', 'builds-on', 'normal-subgroups'],
  ['representation-theory', 'builds-on', 'group-theory'],
  ['representation-theory', 'builds-on', 'linear-algebra'],
  ['example-s3-characters', 'example-of', 'representation-theory'],
  ['lie-algebras', 'builds-on', 'group-theory'],
  ['lie-algebras', 'builds-on', 'linear-algebra'],
  ['lattices', 'builds-on', 'linear-algebra'],
  ['lattices', 'builds-on', 'generating-functions', 'Theta series'],
  ['tori-elliptic-curves', 'builds-on', 'lattices'],
  ['tori-elliptic-curves', 'builds-on', 'complex-numbers'],
  ['modular-forms', 'builds-on', 'complex-analysis'],
  ['modular-forms', 'builds-on', 'tori-elliptic-curves', 'SL(2,ℤ) = changes of torus basis'],
  ['modular-forms', 'builds-on', 'group-theory'],
  ['eisenstein-discriminant', 'builds-on', 'modular-forms'],
  ['eisenstein-discriminant', 'builds-on', 'generating-functions'],
  ['example-j-from-e4', 'example-of', 'eisenstein-discriminant'],
  ['example-j-from-e4', 'example-of', 'j-invariant'],
  ['hauptmodul', 'builds-on', 'modular-forms'],
  ['tensors', 'builds-on', 'linear-algebra'],
  ['tensors', 'builds-on', 'calculus'],
  ['manifolds', 'builds-on', 'calculus'],
  ['manifolds', 'builds-on', 'linear-algebra'],
  ['riemannian-geometry', 'builds-on', 'manifolds'],
  ['riemannian-geometry', 'builds-on', 'tensors'],

  // ---------------------------------------------------------------- classical & statistical physics
  ['newtonian-mechanics', 'builds-on', 'calculus'],
  ['newtonian-gravity', 'builds-on', 'newtonian-mechanics'],
  ['newtonian-gravity', 'builds-on', 'vector-calculus', 'Force as the gradient of a potential'],
  ['waves-normal-modes', 'builds-on', 'differential-equations'],
  ['waves-normal-modes', 'builds-on', 'fourier-analysis'],
  ['waves-normal-modes', 'builds-on', 'newtonian-mechanics'],
  ['dispersion-relations', 'builds-on', 'waves-normal-modes'],
  ['lagrangian-mechanics', 'builds-on', 'newtonian-mechanics'],
  ['hamiltonian-mechanics', 'builds-on', 'lagrangian-mechanics'],
  ['noether-theorem', 'builds-on', 'lagrangian-mechanics'],
  ['noether-theorem', 'related', 'lie-algebras', 'Continuous symmetries are Lie groups'],
  ['maxwell-light', 'builds-on', 'vector-calculus'],
  ['maxwell-light', 'builds-on', 'waves-normal-modes'],
  ['statistical-mechanics', 'builds-on', 'thermodynamics'],
  ['statistical-mechanics', 'builds-on', 'probability'],
  ['statistical-mechanics', 'builds-on', 'hamiltonian-mechanics'],
  ['density-of-states', 'builds-on', 'statistical-mechanics'],
  ['density-of-states', 'builds-on', 'wave-particle-duality', 'Standing matter waves in a box'],
  ['fluid-dynamics', 'builds-on', 'newtonian-mechanics'],
  ['fluid-dynamics', 'builds-on', 'vector-calculus'],

  // ---------------------------------------------------------------- quantum, internally
  ['wave-particle-duality', 'builds-on', 'waves-normal-modes'],
  ['hilbert-space', 'builds-on', 'linear-algebra'],
  ['hilbert-space', 'builds-on', 'complex-numbers'],
  ['observables-operators', 'builds-on', 'hilbert-space'],
  ['observables-operators', 'builds-on', 'eigenvalues'],
  ['observables-operators', 'builds-on', 'hamiltonian-mechanics', 'Poisson brackets → commutators'],
  ['uncertainty-principle', 'derived-from', 'observables-operators'],
  ['uncertainty-principle', 'related', 'fourier-analysis', 'Narrow in x means broad in p'],
  ['uncertainty-principle', 'builds-on', 'probability'],
  ['quantum-harmonic-oscillator', 'builds-on', 'observables-operators'],
  ['quantum-harmonic-oscillator', 'builds-on', 'differential-equations'],
  ['example-trap-oscillator', 'example-of', 'quantum-harmonic-oscillator'],
  ['spin', 'builds-on', 'observables-operators'],
  ['spin', 'builds-on', 'lie-algebras', 'su(2)'],
  ['spin', 'related', 'representation-theory'],
  ['identical-particles', 'builds-on', 'spin'],
  ['identical-particles', 'builds-on', 'hilbert-space'],
  ['entanglement', 'builds-on', 'hilbert-space', 'Tensor products'],
  ['entanglement', 'related', 'speed-of-light', 'Correlations, but no faster-than-light signals'],
  ['decoherence', 'builds-on', 'entanglement'],
  ['decoherence', 'related', 'superposition'],
  ['second-quantization', 'builds-on', 'quantum-harmonic-oscillator'],
  ['second-quantization', 'builds-on', 'identical-particles'],
  ['scattering-length', 'builds-on', 'schrodinger-equation'],
  ['quasiparticles', 'builds-on', 'second-quantization'],
  ['quasiparticles', 'builds-on', 'dispersion-relations'],
  ['spontaneous-symmetry-breaking', 'builds-on', 'noether-theorem'],
  ['spontaneous-symmetry-breaking', 'related', 'quasiparticles', 'Goldstone modes are gapless quasiparticles'],
  ['laser-cooling', 'builds-on', 'maxwell-light'],
  ['laser-cooling', 'builds-on', 'wave-particle-duality', 'Photon momentum kicks'],
  ['laser-cooling', 'builds-on', 'thermodynamics'],
  ['interferometry', 'builds-on', 'wave-particle-duality'],
  ['interferometry', 'builds-on', 'superposition'],
  ['quantum-field-theory', 'builds-on', 'second-quantization'],
  ['quantum-field-theory', 'builds-on', 'lagrangian-mechanics'],
  ['quantum-field-theory', 'builds-on', 'minkowski-spacetime'],
  ['regularization', 'builds-on', 'infinite-series'],
  ['regularization', 'related', 'riemann-zeta'],
  ['regularization', 'related', 'quantum-field-theory', 'Where infinities first had to be tamed'],
  ['example-casimir', 'example-of', 'regularization'],
  ['example-casimir', 'related', 'quantum-harmonic-oscillator', 'Zero-point energy of field modes'],

  // ---------------------------------------------------------------- relativity, internally
  ['principle-of-relativity', 'builds-on', 'newtonian-mechanics'],
  ['lorentz-transformations', 'derived-from', 'principle-of-relativity'],
  ['lorentz-transformations', 'builds-on', 'speed-of-light'],
  ['example-velocity-addition', 'example-of', 'lorentz-transformations'],
  ['minkowski-spacetime', 'builds-on', 'lorentz-transformations'],
  ['four-momentum', 'builds-on', 'minkowski-spacetime'],
  ['four-momentum', 'builds-on', 'tensors'],
  ['equivalence-principle', 'builds-on', 'newtonian-gravity'],
  ['equivalence-principle', 'builds-on', 'principle-of-relativity'],
  ['geodesics', 'builds-on', 'riemannian-geometry'],
  ['geodesics', 'builds-on', 'equivalence-principle'],
  ['geodesics', 'related', 'lagrangian-mechanics', 'Extremize proper time'],
  ['stress-energy-tensor', 'builds-on', 'tensors'],
  ['stress-energy-tensor', 'builds-on', 'four-momentum'],
  ['newtonian-limit', 'builds-on', 'einstein-field-equations'],
  ['newtonian-limit', 'builds-on', 'newtonian-gravity'],
  ['gravitational-redshift', 'same-idea', 'gravitational-time-dilation', 'Wave crests are clock ticks'],
  ['gravitational-redshift', 'builds-on', 'equivalence-principle'],
  ['black-holes', 'builds-on', 'schwarzschild-metric'],
  ['atomic-clocks', 'builds-on', 'wave-particle-duality', 'E = hf'],
  ['atomic-clocks', 'related', 'laser-cooling'],
  ['quantum-gravity-problem', 'builds-on', 'einstein-field-equations'],
  ['quantum-gravity-problem', 'builds-on', 'quantum-field-theory'],
  ['quantum-gravity-problem', 'related', 'black-holes'],

  // ---------------------------------------------------------------- strings, internally
  ['classical-string', 'builds-on', 'lagrangian-mechanics'],
  ['classical-string', 'builds-on', 'minkowski-spacetime'],
  ['classical-string', 'builds-on', 'waves-normal-modes'],
  ['light-cone-quantization', 'builds-on', 'classical-string'],
  ['light-cone-quantization', 'builds-on', 'quantum-harmonic-oscillator'],
  ['conformal-symmetry', 'builds-on', 'complex-analysis'],
  ['conformal-symmetry', 'builds-on', 'lie-algebras'],
  ['conformal-field-theory', 'builds-on', 'conformal-symmetry'],
  ['conformal-field-theory', 'builds-on', 'quantum-field-theory'],
  ['operator-product-expansion', 'part-of', 'conformal-field-theory'],
  ['operator-product-expansion', 'builds-on', 'complex-analysis', 'Residues extract modes'],
  ['torus-partition-function', 'builds-on', 'conformal-field-theory'],
  ['torus-partition-function', 'builds-on', 'modular-forms'],
  ['torus-partition-function', 'builds-on', 'statistical-mechanics', 'Same Tr e^{−βH}'],
  ['example-24-oscillators', 'example-of', 'generating-functions'],
  ['example-24-oscillators', 'related', 'critical-dimension'],
  ['example-24-oscillators', 'related', 'eisenstein-discriminant', '1/η²⁴ = 1/Δ'],
  ['anomalies', 'builds-on', 'noether-theorem'],
  ['anomalies', 'builds-on', 'quantum-field-theory'],
  ['anomalies', 'builds-on', 'regularization'],
  ['ghosts-no-ghost', 'builds-on', 'virasoro-algebra'],
  ['ghosts-no-ghost', 'builds-on', 'anomalies'],
  ['ghosts-no-ghost', 'related', 'light-cone-quantization', 'Same physical spectrum at D = 26'],
  ['compactification', 'builds-on', 'lattices'],
  ['compactification', 'builds-on', 'fourier-analysis', 'Momentum quantization on a circle'],
  ['compactification', 'builds-on', 'bosonic-string'],
  ['lattice-voa', 'builds-on', 'vertex-operator-algebra'],
  ['lattice-voa', 'builds-on', 'lattices'],
  ['lattice-voa', 'builds-on', 'compactification'],
  ['lattice-voa', 'builds-on', 'second-quantization', 'Oscillator Fock space'],
  ['example-leech-to-j', 'example-of', 'lattice-voa'],
  ['example-leech-to-j', 'example-of', 'moonshine-module'],
  ['orbifolds', 'builds-on', 'group-theory'],
  ['orbifolds', 'builds-on', 'torus-partition-function', 'Twisted sectors restore modular invariance'],
  ['golay-m24', 'builds-on', 'finite-simple-groups'],
  ['golay-m24', 'builds-on', 'linear-algebra', 'A 12-dimensional subspace of 𝔽₂²⁴'],
  ['borcherds-algebras', 'builds-on', 'lie-algebras'],
  ['borcherds-algebras', 'builds-on', 'ghosts-no-ghost'],
  ['borcherds-algebras', 'builds-on', 'lattices'],
  ['borcherds-algebras', 'explains', 'monstrous-moonshine', 'Key step in Borcherds’ 1992 proof'],
  ['superstrings', 'builds-on', 'bosonic-string'],
  ['superstrings', 'builds-on', 'spin', 'Worldsheet fermions'],
  ['mathieu-umbral-moonshine', 'builds-on', 'monstrous-moonshine'],
  ['mathieu-umbral-moonshine', 'builds-on', 'golay-m24'],
  ['mathieu-umbral-moonshine', 'related', 'superstrings', 'K3 compactifications'],
  ['ads-cft', 'builds-on', 'conformal-field-theory'],
  ['ads-cft', 'builds-on', 'einstein-field-equations'],
  ['ads-cft', 'related', 'black-holes'],

  // ---------------------------------------------------------------- your original topics → their foundations
  // String theory & dimensional symmetry
  ['monster-group', 'builds-on', 'finite-simple-groups'],
  ['monster-group', 'builds-on', 'representation-theory'],
  ['order-of-the-monster', 'builds-on', 'group-theory'],
  ['j-invariant', 'builds-on', 'modular-forms'],
  ['j-invariant', 'builds-on', 'tori-elliptic-curves', 'j tells tori apart'],
  ['j-invariant', 'builds-on', 'eisenstein-discriminant', 'j = E₄³/Δ'],
  ['monstrous-moonshine', 'builds-on', 'hauptmodul'],
  ['monstrous-moonshine', 'builds-on', 'representation-theory', 'Traces tr(g | Vₙ)'],
  ['monstrous-moonshine', 'builds-on', 'generating-functions'],
  ['vertex-operator-algebra', 'builds-on', 'conformal-field-theory'],
  ['vertex-operator-algebra', 'builds-on', 'operator-product-expansion'],
  ['vertex-operator-algebra', 'builds-on', 'complex-analysis', 'Formal Laurent series'],
  ['virasoro-algebra', 'builds-on', 'lie-algebras'],
  ['virasoro-algebra', 'builds-on', 'conformal-symmetry', 'Central extension of the Witt algebra'],
  ['virasoro-algebra', 'builds-on', 'anomalies'],
  ['leech-lattice', 'builds-on', 'lattices'],
  ['leech-lattice', 'builds-on', 'golay-m24', 'Constructed from the Golay code'],
  ['bosonic-string', 'builds-on', 'classical-string'],
  ['bosonic-string', 'builds-on', 'light-cone-quantization'],
  ['bosonic-string', 'builds-on', 'four-momentum', 'Mass spectrum'],
  ['critical-dimension', 'builds-on', 'light-cone-quantization'],
  ['critical-dimension', 'builds-on', 'quantum-harmonic-oscillator', 'Zero-point energies'],
  ['critical-dimension', 'builds-on', 'riemann-zeta', 'ζ(−1) = −1/12'],
  ['critical-dimension', 'builds-on', 'regularization'],
  ['example-zeta-regularization', 'example-of', 'regularization'],
  ['moonshine-module', 'builds-on', 'lattice-voa'],
  ['moonshine-module', 'builds-on', 'orbifolds'],
  ['moonshine-module', 'builds-on', 'torus-partition-function', 'Why c = 24 gives j'],
  ['question-monster-universe', 'related', 'ads-cft'],
  ['question-monster-universe', 'related', 'mathieu-umbral-moonshine'],
  ['question-monster-universe', 'related', 'quantum-gravity-problem'],

  // Quantum mechanics & extreme states of matter
  ['superposition', 'builds-on', 'hilbert-space'],
  ['superposition', 'builds-on', 'waves-normal-modes', 'Interference'],
  ['schrodinger-equation', 'builds-on', 'observables-operators'],
  ['schrodinger-equation', 'builds-on', 'wave-particle-duality'],
  ['schrodinger-equation', 'builds-on', 'differential-equations'],
  ['born-rule', 'builds-on', 'probability'],
  ['born-rule', 'builds-on', 'hilbert-space'],
  ['bose-einstein-statistics', 'builds-on', 'statistical-mechanics'],
  ['bose-einstein-statistics', 'builds-on', 'identical-particles'],
  ['bose-einstein-condensate', 'builds-on', 'wave-particle-duality', 'Thermal de Broglie wavelength'],
  ['bose-einstein-condensate', 'builds-on', 'second-quantization'],
  ['bose-einstein-condensate', 'builds-on', 'laser-cooling', 'How they are made'],
  ['bose-einstein-condensate', 'related', 'spontaneous-symmetry-breaking', 'The condensate picks a phase'],
  ['bec-critical-temperature', 'builds-on', 'density-of-states'],
  ['example-tc-derivation', 'example-of', 'bec-critical-temperature'],
  ['example-tc-derivation', 'example-of', 'density-of-states'],
  ['example-tc-derivation', 'related', 'riemann-zeta'],
  ['bec-critical-temperature', 'builds-on', 'riemann-zeta', 'ζ(3/2) ≈ 2.612'],
  ['gross-pitaevskii', 'builds-on', 'scattering-length'],
  ['gross-pitaevskii', 'builds-on', 'second-quantization', 'Mean-field limit'],
  ['superfluidity', 'builds-on', 'fluid-dynamics'],
  ['superfluidity', 'builds-on', 'quasiparticles'],
  ['superfluidity', 'related', 'spontaneous-symmetry-breaking'],
  ['landau-criterion', 'builds-on', 'dispersion-relations'],
  ['landau-criterion', 'builds-on', 'newtonian-mechanics', 'Energy and momentum conservation'],
  ['landau-criterion', 'builds-on', 'quasiparticles'],
  ['bogoliubov-dispersion', 'builds-on', 'quasiparticles'],
  ['bogoliubov-dispersion', 'related', 'spontaneous-symmetry-breaking', 'The phonon is the Goldstone mode'],
  ['quantized-circulation', 'builds-on', 'vector-calculus', 'Stokes’ theorem'],
  ['quantized-circulation', 'builds-on', 'complex-numbers', 'Phase winds by 2πn'],
  ['quantized-circulation', 'related', 'fluid-dynamics'],

  // Relativity & spacetime mechanics
  ['speed-of-light', 'builds-on', 'maxwell-light'],
  ['speed-of-light', 'builds-on', 'principle-of-relativity'],
  ['sr-time-dilation', 'derived-from', 'lorentz-transformations'],
  ['example-muon', 'related', 'four-momentum', 'E ≈ 1.67 GeV'],
  ['gravitational-time-dilation', 'builds-on', 'equivalence-principle'],
  ['gravitational-time-dilation', 'builds-on', 'minkowski-spacetime', 'Proper time'],
  ['gravitational-time-dilation', 'builds-on', 'newtonian-gravity', 'The potential Φ'],
  ['gravitational-time-dilation', 'related', 'newtonian-limit', 'Where 1 + Φ/c² comes from'],
  ['schwarzschild-metric', 'builds-on', 'riemannian-geometry'],
  ['einstein-field-equations', 'builds-on', 'riemannian-geometry'],
  ['einstein-field-equations', 'builds-on', 'stress-energy-tensor'],
  ['einstein-field-equations', 'builds-on', 'equivalence-principle'],
  ['einstein-field-equations', 'builds-on', 'newtonian-gravity'],
  ['pound-rebka', 'example-of', 'gravitational-redshift'],
  ['example-gps', 'related', 'atomic-clocks'],
  ['clocks-superposition-gravity', 'builds-on', 'interferometry'],
  ['clocks-superposition-gravity', 'builds-on', 'atomic-clocks'],
  ['clocks-superposition-gravity', 'builds-on', 'decoherence', 'Which-path information'],
  ['clocks-superposition-gravity', 'builds-on', 'minkowski-spacetime', 'Proper time'],
  ['clocks-superposition-gravity', 'related', 'quantum-gravity-problem'],

  // Miscellany
  ['why-24', 'related', 'torus-partition-function'],
  ['why-24', 'related', 'example-24-oscillators'],
  ['why-24', 'related', 'eisenstein-discriminant'],
  ['why-24', 'related', 'example-leech-to-j'],
  ['why-24', 'related', 'golay-m24'],
];
