import { AREA, entry, md } from '../helpers.js';

const A = AREA.QUANTUM;

export const QUANTUM = [
  entry('wave-particle-duality', 'equation', A, 'curious', 'Wave–Particle Duality & de Broglie Wavelength', {
    summary: 'Light comes in particles, and matter behaves like waves. Every particle of momentum p has wavelength h/p.',
    latex: md`\lambda = \frac{h}{p}, \qquad E = hf = \hbar\omega, \qquad \lambda_T = \frac{h}{\sqrt{2\pi m k_B T}}`,
    variables: [
      [md`h`, 'Planck constant, 6.62607015 × 10⁻³⁴ J·s (ħ = h/2π)'],
      [md`p`, 'Momentum'],
      [md`\lambda_T`, 'Thermal de Broglie wavelength of a particle at temperature T'],
    ],
    tags: ['foundations', 'waves'],
    body: md`
      - Einstein (1905): light energy comes in quanta $E = hf$ (photoelectric effect).
      - de Broglie (1924): matter has wavelength $h/p$. Confirmed by electron diffraction (Davisson–Germer, 1927).

      **Why cold means quantum:** as $T$ drops, momentum drops and $\lambda_T$ grows. When it reaches the spacing between atoms, their wavefunctions overlap and identical-particle effects take over:
      - Rubidium-87 at 400 nK: $\lambda_T \approx 0.30\ \mu\text{m}$, and at $n = 10^{20}\ \text{m}^{-3}$ that gives $n\lambda_T^3 \approx 2.61$ — the [[Bose–Einstein Condensate]] threshold.
      - Helium-4 at its lambda point (2.17 K): $\lambda_T \approx 0.59$ nm, larger than the 0.36 nm atomic spacing — hence [[Superfluidity]].
    `,
  }),

  entry('hilbert-space', 'concept', A, 'curious', 'Hilbert Space & Dirac Notation', {
    summary: 'Quantum states are unit vectors in a complex vector space with an inner product. Kets, bras and brackets are the notation.',
    latex: md`\braket{\phi|\psi} = \braket{\psi|\phi}^*, \qquad \braket{\psi|\psi} = 1, \qquad \sum_i \ket{i}\bra{i} = \hat{1}`,
    variables: [
      [md`\ket{\psi}`, 'Ket: a state vector'],
      [md`\bra{\phi}`, 'Bra: the dual (conjugate) vector'],
      [md`\braket{\phi|\psi}`, 'Inner product: the amplitude to find ψ in state φ'],
    ],
    tags: ['foundations', 'linear algebra'],
    body: md`
      - A **Hilbert space** is a complex [[Vector Spaces & Linear Maps|vector space]] with an inner product, complete enough for infinite sums to make sense.
      - A qubit lives in $\mathbb C^2$; a particle on a line lives in the space of square-integrable wavefunctions $\psi(x) = \braket{x|\psi}$.
      - **Completeness** $\sum_i \ket{i}\bra{i} = \hat 1$ lets you expand any state in a basis: $\ket\psi = \sum_i \ket{i}\braket{i|\psi}$ — the coefficients are the $c_i$ of [[Superposition]].
      - Two systems combine by the **tensor product**, which is where [[Entanglement]] lives.
    `,
    sources: ['Susskind & Friedman — Quantum Mechanics: The Theoretical Minimum', 'Griffiths & Schroeter — Introduction to Quantum Mechanics'],
  }),

  entry('observables-operators', 'concept', A, 'curious', 'Observables, Operators & Commutators', {
    summary: 'Measurable quantities are Hermitian operators. Their eigenvalues are the possible results; operators that don’t commute can’t both be sharp.',
    latex: md`\hat A\ket{a} = a\ket{a}, \qquad \langle A\rangle = \bra{\psi}\hat A\ket{\psi}, \qquad [\hat x, \hat p] = i\hbar`,
    variables: [
      [md`\hat A = \hat A^\dagger`, 'A Hermitian operator (observable)'],
      [md`a`, 'An eigenvalue: a possible measurement result'],
      [md`[\hat A,\hat B] = \hat A\hat B - \hat B\hat A`, 'Commutator'],
    ],
    tags: ['foundations', 'measurement'],
    body: md`
      **The postulates in one place:**
      1. States are unit vectors ([[Hilbert Space & Dirac Notation]]).
      2. Observables are Hermitian operators; results are eigenvalues ([[Eigenvalues & Eigenvectors]]).
      3. Probabilities follow the [[Born Rule]].
      4. Time evolution is generated by the Hamiltonian ([[Schrödinger Equation]]).

      **Commutators** are the quantum version of Poisson brackets ([[Hamiltonian Mechanics & Poisson Brackets]]). They drive the [[Heisenberg Uncertainty Principle]], the ladder operators of the [[Quantum Harmonic Oscillator]], and — in string theory — the [[Virasoro Algebra]].
    `,
  }),

  entry('uncertainty-principle', 'equation', A, 'curious', 'Heisenberg Uncertainty Principle', {
    summary: 'Position and momentum can’t both be sharp: the product of their spreads is at least ħ/2.',
    latex: md`\sigma_x\,\sigma_p \ge \frac{\hbar}{2}, \qquad \sigma_A\,\sigma_B \ge \tfrac12\left|\langle[\hat A,\hat B]\rangle\right|`,
    variables: [
      [md`\sigma_x,\ \sigma_p`, 'Standard deviations of position and momentum'],
    ],
    tags: ['foundations', 'measurement'],
    body: md`
      Not a statement about clumsy measurement: it is a property of the state. A wave localized in space needs many wavelengths to build it ([[Fourier Series & Transforms]]), so it can’t have a single momentum.

      **Consequences you’ll meet:**
      - **Zero-point energy:** a particle confined to a trap can’t sit still at the bottom, so the [[Quantum Harmonic Oscillator]] has ground energy $\tfrac12\hbar\omega$. Summed over a string’s modes, this is the energy in the [[Critical Dimension of the Bosonic String]].
      - A condensate’s size sets a minimum momentum spread — visible when it is released and expands.
    `,
  }),

  entry('quantum-harmonic-oscillator', 'equation', A, 'curious', 'Quantum Harmonic Oscillator', {
    summary: 'The most important system in physics: evenly spaced energy levels, ladder operators, and a zero-point energy. Fields and strings are made of these.',
    latex: md`\hat H = \hbar\omega\left(a^\dagger a + \tfrac12\right), \qquad [a, a^\dagger] = 1, \qquad E_n = \hbar\omega\left(n + \tfrac12\right)`,
    variables: [
      [md`a,\ a^\dagger`, 'Lowering and raising (annihilation and creation) operators'],
      [md`n = 0, 1, 2, \dots`, 'Number of quanta'],
      [md`\tfrac12\hbar\omega`, 'Zero-point energy'],
    ],
    tags: ['foundations', 'oscillators', 'strings'],
    body: md`
      With $a = \sqrt{\frac{m\omega}{2\hbar}}\left(\hat x + \frac{i\hat p}{m\omega}\right)$ the Hamiltonian $\frac{\hat p^2}{2m} + \frac12 m\omega^2\hat x^2$ becomes the form above. Then $a^\dagger\ket{n} = \sqrt{n+1}\ket{n+1}$: each $a^\dagger$ adds one quantum $\hbar\omega$.

      **Why it’s everywhere:**
      - Any system near a stable minimum is approximately an oscillator.
      - A free field is infinitely many oscillators, one per mode; "$n$ quanta in a mode" is "$n$ particles" — [[Second Quantization & Fock Space]], [[Quantum Field Theory]].
      - A string is a tower of oscillators $\alpha^i_{-n}$ with frequencies $n$; their zero-point energies $\sum n/2$ give the [[Critical Dimension of the Bosonic String]] and the [[Casimir Effect]].
      - Atoms in a magnetic or optical trap sit in a 3D harmonic potential ([[Ground-state size of an atom in a trap]]).
    `,
  }),

  entry('example-trap-oscillator', 'example', A, 'curious', 'Ground-state size of an atom in a trap', {
    summary: 'A rubidium atom in a 100 Hz harmonic trap has a ground-state size of about one micrometre.',
    tags: ['oscillators', 'ultracold atoms'],
    body: md`
      The oscillator length sets the size of the ground state:
      $$a_{\text{ho}} = \sqrt{\frac{\hbar}{m\omega}}$$

      Rubidium-87: $m = 1.443\times10^{-25}$ kg. Trap frequency $f = 100$ Hz, so $\omega = 2\pi f = 628\ \text{s}^{-1}$.

      $$a_{\text{ho}} = \sqrt{\frac{1.055\times10^{-34}}{1.443\times10^{-25}\times 628}} \approx 1.08\times10^{-6}\ \text{m}$$

      About $1\ \mu\text{m}$. Level spacing $\hbar\omega/k_B \approx 4.8$ nK — comparable to condensate temperatures, which is why trap quantization matters in real experiments. (Repulsive interactions make real condensates several times larger than $a_{\text{ho}}$.)
    `,
  }),

  entry('spin', 'concept', A, 'curious', 'Spin & Angular Momentum', {
    summary: 'Particles carry intrinsic angular momentum in half-integer or integer units of ħ. Spin decides whether a particle is a boson or a fermion.',
    latex: md`\hat S_z\ket{\pm} = \pm\frac{\hbar}{2}\ket{\pm}, \qquad [\hat S_x, \hat S_y] = i\hbar\,\hat S_z, \qquad \hat S^2 = \hbar^2 s(s+1)`,
    variables: [
      [md`s`, 'Spin quantum number: 0, 1/2, 1, 3/2, …'],
      [md`\ket{\pm}`, 'Spin up / spin down along z'],
    ],
    tags: ['foundations', 'symmetry'],
    body: md`
      - Stern–Gerlach (1922): silver atoms in a non-uniform magnetic field split into **two** beams — angular momentum is quantized, and comes in halves.
      - The spin operators satisfy the $\mathfrak{su}(2)$ algebra ([[Lie Groups & Lie Algebras]]); spin states are its [[Representation Theory & Characters|representations]], of dimension $2s+1$.
      - A spin-½ particle is the physical qubit; the qubit calculations in [[Measuring a qubit in two bases]] apply directly.
      - A rotation by $2\pi$ multiplies a spin-½ state by $-1$.

      **Integer spin → boson, half-integer → fermion:** [[Identical Particles: Bosons & Fermions]].
    `,
  }),

  entry('identical-particles', 'theory', A, 'curious', 'Identical Particles: Bosons & Fermions', {
    summary: 'Swapping two identical particles leaves the state unchanged (bosons) or flips its sign (fermions). Bosons can pile into one state; fermions can’t.',
    latex: md`\psi(\mathbf x_2, \mathbf x_1) = \pm\,\psi(\mathbf x_1, \mathbf x_2)`,
    variables: [
      [md`+`, 'Bosons (integer spin): photons, helium-4, rubidium-87'],
      [md`-`, 'Fermions (half-integer spin): electrons, protons, helium-3'],
    ],
    tags: ['foundations', 'bosons', 'statistics'],
    body: md`
      - **Pauli exclusion:** for fermions, putting both in the same state gives $\psi = -\psi = 0$. For bosons nothing forbids it — in fact it is enhanced.
      - **Spin–statistics theorem** (Pauli, 1940): relativistic quantum field theory forces integer spin ↔ symmetric, half-integer ↔ antisymmetric.
      - **Composite particles:** count the fermions inside. Helium-4 has 2 protons + 2 neutrons + 2 electrons = 6 → boson. Helium-3 has 5 → fermion. Rubidium-87 has 37 + 50 + 37 = 124 → boson.

      This is why helium-4 becomes superfluid at 2.17 K by condensing, while helium-3 must first form pairs and only goes superfluid near a millikelvin. It leads directly to the [[Bose–Einstein Distribution]].
    `,
  }),

  entry('entanglement', 'concept', A, 'curious', 'Entanglement', {
    summary: 'A joint state of two systems that can’t be written as “this state for A, that state for B”. Measurement outcomes are correlated more strongly than any classical model allows.',
    latex: md`\ket{\Phi^+} = \frac{\ket{0}_A\ket{0}_B + \ket{1}_A\ket{1}_B}{\sqrt2} \;\neq\; \ket{\alpha}_A \otimes \ket{\beta}_B`,
    variables: [
      [md`\otimes`, 'Tensor product: how two systems’ state spaces combine'],
    ],
    tags: ['foundations', 'nonlocality'],
    body: md`
      - Measure A and B in the same basis: results always agree, though each alone is a 50/50 coin.
      - Bell (1964) showed the correlations in *other* bases violate an inequality every local hidden-variable theory obeys. Experiments (Aspect 1982, loophole-free tests 2015) confirm quantum mechanics; Nobel Prize 2022 for Aspect, Clauser and Zeilinger.
      - **No signalling:** A’s results alone look random whatever B does, so entanglement can’t send messages faster than the [[Speed of Light]].
      - When a system becomes entangled with its environment, its own superposition looks classical — [[Measurement, Density Matrices & Decoherence]].
    `,
  }),

  entry('decoherence', 'concept', A, 'curious', 'Measurement, Density Matrices & Decoherence', {
    summary: 'Why we don’t see cats in superposition: entangling with the environment kills the interference terms, fast.',
    latex: md`\rho = \ket{\psi}\bra{\psi}, \qquad \rho_{\text{sys}} = \operatorname{Tr}_{\text{env}}\,\rho_{\text{total}}, \qquad \rho_{01}(t) = \rho_{01}(0)\,e^{-t/\tau_D}`,
    variables: [
      [md`\rho`, 'Density matrix — describes pure and mixed states'],
      [md`\operatorname{Tr}_{\text{env}}`, 'Partial trace: ignore the environment'],
      [md`\rho_{01}`, 'Off-diagonal element (coherence) between two branches'],
      [md`\tau_D`, 'Decoherence time'],
    ],
    tags: ['measurement', 'foundations'],
    body: md`
      For $\ket\psi = c_0\ket0 + c_1\ket1$, the diagonal of $\rho$ holds probabilities $|c_0|^2, |c_1|^2$; the off-diagonal $c_0c_1^*$ holds the phase that produces interference.

      When each branch leaves a different mark on the environment (a scattered photon, a different clock reading…), tracing out the environment suppresses $\rho_{01}$. The system then behaves like a classical mixture.

      - Decoherence explains why interference disappears; interpretations still disagree on why one outcome is observed.
      - **Which-path information destroys interference.** That is the mechanism in the proposal to put a clock in two places at once: [[Clocks, Superposition and Gravity]].
    `,
  }),

  entry('second-quantization', 'concept', A, 'curious', 'Second Quantization & Fock Space', {
    summary: 'Describe many identical particles by how many occupy each mode, with operators that create and destroy them.',
    latex: md`\ket{n_1, n_2, \dots}, \qquad [a_i, a_j^\dagger] = \delta_{ij}, \qquad \hat\psi(\mathbf r) = \sum_i \phi_i(\mathbf r)\,a_i, \qquad \hat H = \sum_i \varepsilon_i\,a_i^\dagger a_i + \frac{g}{2}\int \hat\psi^\dagger\hat\psi^\dagger\hat\psi\hat\psi\,d^3r`,
    variables: [
      [md`n_i`, 'Number of particles in mode i'],
      [md`a_i^\dagger,\ a_i`, 'Create / destroy a particle in mode i (bosons: commutators)'],
      [md`\hat\psi(\mathbf r)`, 'Field operator: destroys a particle at r'],
    ],
    tags: ['many-body', 'foundations'],
    body: md`
      Instead of a wavefunction of $N$ coordinates, specify occupation numbers. Every mode is a [[Quantum Harmonic Oscillator]] where "quanta" are particles. Symmetry for bosons is automatic ([[Identical Particles: Bosons & Fermions]]).

      **For condensates:** below $T_c$ the ground mode has $n_0 \sim N$. Replace $a_0$ by the number $\sqrt{N_0}$ and the field operator by a classical field $\psi(\mathbf r)$ — that gives the [[Gross–Pitaevskii Equation]]. Keeping the next-order fluctuations gives the [[Bogoliubov Dispersion]].

      **For fields and strings:** the same Fock-space construction builds particles in [[Quantum Field Theory]] and the state space of the string.
    `,
  }),

  entry('scattering-length', 'concept', A, 'curious', 'Low-Energy Scattering & Scattering Length', {
    summary: 'At ultracold temperatures all the details of how two atoms collide collapse into one number, the scattering length a.',
    latex: md`\sigma = 8\pi a_s^2 \ (\text{identical bosons}), \qquad g = \frac{4\pi\hbar^2 a_s}{m}, \qquad a_s(B) = a_{\text{bg}}\left(1 - \frac{\Delta}{B - B_0}\right)`,
    variables: [
      [md`a_s`, 's-wave scattering length (positive = effectively repulsive)'],
      [md`g`, 'Strength of the equivalent contact interaction'],
      [md`B_0,\ \Delta`, 'Position and width of a Feshbach resonance in magnetic field'],
    ],
    tags: ['ultracold atoms', 'interactions'],
    body: md`
      When the de Broglie wavelength is far larger than the range of the interatomic potential, only the spherically symmetric (s-wave) part of scattering survives. Its effect is the same as a hard sphere of radius $a_s$, or equivalently a contact potential $g\,\delta(\mathbf r)$.

      - Rubidium-87: $a_s \approx 5.3$ nm. Sodium-23: $a_s \approx 2.75$ nm.
      - **Feshbach resonances** let experimenters tune $a_s$ with a magnetic field — even make it negative (attractive) or huge.

      The contact strength $g$ is the nonlinearity in the [[Gross–Pitaevskii Equation]] and sets the sound speed in the [[Bogoliubov Dispersion]].
    `,
  }),

  entry('quasiparticles', 'concept', A, 'curious', 'Quasiparticles: Phonons & Rotons', {
    summary: 'Collective excitations of many particles that behave like particles themselves, with their own energy–momentum relation.',
    tags: ['excitations', 'many-body', 'helium'],
    body: md`
      A sound wave in a quantum fluid is quantized into **phonons**, each with energy $\hbar\omega$ and momentum $\hbar k$. They are not atoms; they are patterns of motion shared by many atoms.

      **Helium-4’s spectrum** (Landau 1941; measured by neutron scattering, Henshaw and Woods 1961):
      - Low momentum: phonons, $\varepsilon \approx c\,p$ with $c \approx 238$ m/s.
      - A minimum near $p_0/\hbar \approx 1.9\ \text{\AA}^{-1}$ with gap $\Delta/k_B \approx 8.6$ K: **rotons**.

      **Weakly interacting gas:** the [[Bogoliubov Dispersion]] — phonons at low momentum, free atoms at high momentum.

      The shape of $\varepsilon(p)$ is what the [[Landau Criterion]] tests: friction requires creating quasiparticles, and below $v_c$ you can’t. See also [[Dispersion Relations, Phase & Group Velocity]].
    `,
  }),

  entry('spontaneous-symmetry-breaking', 'concept', A, 'curious', 'Spontaneous Symmetry Breaking & Goldstone Modes', {
    summary: 'The laws are symmetric but the ground state isn’t. A condensate picks a phase — and the price is a gapless sound mode.',
    latex: md`\psi \to e^{i\alpha}\psi \text{ is a symmetry of } H, \quad\text{but}\quad \langle\hat\psi\rangle = \sqrt{n}\,e^{i\theta} \neq 0`,
    variables: [
      [md`\langle\hat\psi\rangle`, 'Order parameter: nonzero only in the broken phase'],
      [md`\theta`, 'The chosen phase'],
    ],
    tags: ['symmetry', 'macroscopic quantum'],
    body: md`
      A pencil balanced on its tip is rotationally symmetric; once it falls it points one way. The equations kept the symmetry, the state didn’t.

      - **Condensates and superfluids** break the $U(1)$ phase symmetry whose [[Noether’s Theorem|Noether charge]] is particle number. The order parameter is the macroscopic wavefunction of the [[Bose–Einstein Condensate]].
      - **Goldstone’s theorem:** breaking a continuous symmetry produces a gapless excitation — slowly twisting $\theta$ costs almost no energy. In a superfluid that is the phonon of the [[Bogoliubov Dispersion]].
      - A phase gradient is a flow, $\mathbf v_s = \frac{\hbar}{m}\nabla\theta$, which is why the broken phase can flow without friction ([[Superfluidity]]).
      - Magnets, crystals and the Higgs mechanism are other examples.
    `,
  }),

  entry('laser-cooling', 'concept', A, 'curious', 'Laser Cooling & Atom Traps', {
    summary: 'Using photon kicks to slow atoms from room temperature to microkelvin, then evaporating the hottest ones to reach nanokelvin.',
    latex: md`T_D = \frac{\hbar\Gamma}{2k_B}`,
    variables: [
      [md`T_D`, 'Doppler cooling limit'],
      [md`\Gamma`, 'Natural linewidth of the atomic transition'],
    ],
    tags: ['ultracold atoms', 'experiments'],
    body: md`
      **Doppler cooling:** tune a laser slightly below resonance. An atom moving toward the beam sees it Doppler-shifted into resonance, absorbs photons and gets kicked backwards. Beams from all six directions make an "optical molasses".

      - Doppler limit for rubidium-87 ($\Gamma = 2\pi\times 6.07$ MHz): $T_D \approx 146\ \mu\text{K}$. Polarization-gradient (sub-Doppler) cooling goes lower. Nobel Prize 1997: Chu, Cohen-Tannoudji, Phillips.
      - **Magneto-optical trap (MOT)** adds a magnetic field gradient so the light force also pushes atoms to the centre.
      - **Evaporative cooling:** hold the atoms in a magnetic or optical trap and let the most energetic ones escape. The rest rethermalize colder — the final step to a [[Bose–Einstein Condensate]].

      The same cold atoms are the ticking element in modern optical [[Atomic Clocks]].
    `,
  }),

  entry('interferometry', 'concept', A, 'curious', 'Matter-Wave Interferometry', {
    summary: 'Split a particle’s wavefunction, send the parts along different paths, recombine them, and read the phase difference. Extremely sensitive to gravity and time.',
    latex: md`\Delta\varphi = \frac{1}{\hbar}\int \Delta V\,dt, \qquad \Delta\varphi_{\text{grav}} = \frac{m g A}{\hbar v}`,
    variables: [
      [md`\Delta\varphi`, 'Phase difference between the two paths'],
      [md`A`, 'Area enclosed by the paths (in a vertical plane)'],
      [md`v`, 'Particle speed'],
    ],
    tags: ['interference', 'gravity', 'experiments'],
    body: md`
      Each path accumulates phase $\frac1\hbar\int(\text{energy})\,dt$. If one arm is higher by $H$ for time $T = L/v$, the extra potential energy $mgH$ gives $\Delta\varphi = mgHT/\hbar = mgA/(\hbar v)$.

      **Numbers:** thermal neutrons ($\lambda = 1.42\ \text{\AA}$, $v \approx 2790$ m/s) around a $10\ \text{cm}^2$ loop: $\Delta\varphi \approx 56$ rad — many full fringes. This is the scale of the COW experiment (1975), the first observation of gravity acting on a quantum [[Superposition]].

      Today atom interferometers measure $g$ to parts per billion. Adding a clock to each arm is the next step: [[Clocks, Superposition and Gravity]].
    `,
  }),

  entry('quantum-field-theory', 'concept', A, 'curious', 'Quantum Field Theory', {
    summary: 'Quantum mechanics plus special relativity. Fields are the fundamental objects; particles are their quantized excitations.',
    latex: md`\hat\phi(x) = \int \frac{d^3p}{(2\pi)^3}\frac{1}{\sqrt{2E_{\mathbf p}}}\left(a_{\mathbf p}\,e^{-ip\cdot x} + a^\dagger_{\mathbf p}\,e^{ip\cdot x}\right), \qquad [a_{\mathbf p}, a^\dagger_{\mathbf q}] = (2\pi)^3\delta^3(\mathbf p - \mathbf q)`,
    variables: [
      [md`\hat\phi(x)`, 'Field operator at spacetime point x'],
      [md`a^\dagger_{\mathbf p}`, 'Creates a particle with momentum p'],
      [md`E_{\mathbf p} = \sqrt{\mathbf p^2 + m^2}`, 'Relativistic energy (units ħ = c = 1)'],
    ],
    tags: ['qft', 'bridge'],
    body: md`
      **Why fields:** relativity lets energy turn into mass ($E = mc^2$), so particle number can change. A fixed-$N$ wavefunction can’t describe that; a field whose excitations come and go can.

      - Each momentum mode is a [[Quantum Harmonic Oscillator]]; particles are its quanta ([[Second Quantization & Fock Space]]).
      - Built from a Lorentz-invariant Lagrangian ([[Lagrangian Mechanics & Least Action]], [[Minkowski Spacetime, Light Cones & Proper Time]]).
      - Predicts antiparticles and the spin–statistics connection.
      - Infinities from summing over all modes need [[Regularization & Renormalization]].
      - Symmetries broken by quantization: [[Quantum Anomalies & the Central Charge]].

      A 2D QFT with conformal symmetry is a [[2D Conformal Field Theory]] — the language of string worldsheets.
    `,
    sources: ['A. Zee — Quantum Field Theory in a Nutshell', 'Tom Lancaster & Stephen Blundell — Quantum Field Theory for the Gifted Amateur'],
  }),

  entry('regularization', 'concept', A, 'curious', 'Regularization & Renormalization', {
    summary: 'Taming infinite sums in physics: introduce a cutoff, separate the part that depends on it, and keep the finite physical remainder.',
    latex: md`\sum_{n=1}^{\infty} n\,e^{-\varepsilon n} = \frac{1}{\varepsilon^2} - \frac{1}{12} + O(\varepsilon^2)`,
    variables: [
      [md`\varepsilon`, 'Regulator (cutoff); physical answers must not depend on it'],
    ],
    tags: ['qft', 'series', 'infinities'],
    body: md`
      **The recipe:**
      1. **Regularize:** make the divergent quantity finite with a cutoff (smooth damping, lattice spacing, dimensional or zeta regularization).
      2. **Isolate** terms that blow up as the cutoff is removed.
      3. **Renormalize:** absorb them into parameters you measure anyway (a cosmological constant, a mass, a charge).
      4. The **cutoff-independent** remainder is the prediction.

      **Two places it gives real numbers:**
      - Zero-point energy of string oscillators → $-\tfrac1{12}$ per direction → $D = 26$ ([[Critical Dimension of the Bosonic String]], [[Regularizing 1 + 2 + 3 + ⋯]]).
      - Zero-point energy of the electromagnetic field between two plates → a measurable force ([[Casimir Effect]]).

      Different regulators agree on the finite part — which is why $\zeta(-1) = -\tfrac1{12}$ ([[Riemann Zeta Function]]) gives the right answer.
    `,
  }),

  entry('example-tc-derivation', 'example', A, 'curious', 'Deriving T_c from the density of states', {
    summary: 'Count how many atoms the excited states can hold at μ = 0. When that falls below N, the rest must condense — and out drops nλ³ = ζ(3/2).',
    tags: ['statistical mechanics', 'ultracold atoms'],
    body: md`
      **Step 1 — atoms in excited states.** Use the [[Bose–Einstein Distribution]] with the largest allowed chemical potential, $\mu = 0$, and the [[Density of States]]:
      $N_{\text{ex}} = \int_0^\infty \frac{g(\varepsilon)\,d\varepsilon}{e^{\varepsilon/k_BT} - 1} = \frac{V}{4\pi^2}\left(\frac{2m}{\hbar^2}\right)^{3/2}(k_BT)^{3/2}\int_0^\infty\frac{\sqrt x\,dx}{e^x - 1}$

      **Step 2 — the integral.** Expand $\frac{1}{e^x-1} = \sum_{k\ge1} e^{-kx}$ and integrate term by term:
      $\int_0^\infty \frac{\sqrt x\,dx}{e^x - 1} = \Gamma(\tfrac32)\,\zeta(\tfrac32) = \frac{\sqrt\pi}{2}\times 2.612$
      — the [[Riemann Zeta Function]] appears.

      **Step 3 — tidy up.** The constants combine to
      $N_{\text{ex}} = V\left(\frac{m k_B T}{2\pi\hbar^2}\right)^{3/2}\zeta(\tfrac32) = \frac{V}{\lambda_T^3}\,\zeta(\tfrac32)$

      **Step 4 — the transition.** $N_{\text{ex}}$ shrinks as $T^{3/2}$. It equals the total $N$ when $n\lambda_T^3 = \zeta(3/2)$; solving for $T$ gives the [[BEC Critical Temperature]]. Below it, $N_0 = N - N_{\text{ex}}$, so $N_0/N = 1 - (T/T_c)^{3/2}$.

      The ground state was lost in step 1 because $g(0) = 0$ — the integral simply can’t see it. That blind spot is where the condensate hides.
    `,
  }),

  entry('example-casimir', 'example', A, 'curious', 'Casimir Effect', {
    summary: 'Two uncharged metal plates in vacuum attract, because they restrict which zero-point field modes fit between them.',
    latex: md`\frac{F}{A} = -\frac{\pi^2\hbar c}{240\,a^4}`,
    variables: [
      [md`a`, 'Separation between the plates'],
      [md`F/A`, 'Attractive pressure'],
    ],
    tags: ['qft', 'zero-point energy', 'experiments'],
    body: md`
      Between the plates only modes with $n$ half-wavelengths fit; outside, all modes exist. Each mode has zero-point energy $\tfrac12\hbar\omega$ ([[Quantum Harmonic Oscillator]]). Both totals are infinite, but their **difference** — computed with the same regularization as $1 + 2 + 3 + \cdots$ — is finite and depends on $a$. Casimir, 1948.

      **Numbers:**
      - $a = 1\ \mu\text{m}$: $\;F/A = \dfrac{\pi^2 (1.055\times10^{-34})(3.00\times10^8)}{240\times(10^{-6})^4} \approx 1.3\times10^{-3}$ Pa.
      - $a = 10$ nm: about $1.3\times10^{5}$ Pa — roughly atmospheric pressure. Relevant for micro-machines.

      Measured by Lamoreaux (1997) and Mohideen and Roy (1998), in agreement with theory.
    `,
  }),
];
