import { AREA, entry, md } from '../helpers.js';

const A = AREA.STRING;

export const STRINGS = [
  entry('classical-string', 'equation', A, 'curious', 'Relativistic String & Nambu–Goto Action', {
    summary: 'A string moving through spacetime minimizes the area of the surface it sweeps out. Its vibrations obey a wave equation.',
    latex: md`S = -T\int d\tau\,d\sigma\,\sqrt{-\det\left(\partial_a X^\mu\,\partial_b X_\mu\right)}, \qquad T = \frac{1}{2\pi\alpha'}`,
    variables: [
      [md`X^\mu(\tau,\sigma)`, 'Position in spacetime of the point σ on the string at worldsheet time τ'],
      [md`T`, 'String tension (units ħ = c = 1)'],
      [md`\alpha'`, 'Regge slope; √α′ is the string length scale'],
    ],
    tags: ['strings', 'action'],
    body: md`
      A point particle’s action is the length (proper time) of its worldline. A string’s action is the **area** of its worldsheet — the natural next step ([[Lagrangian Mechanics & Least Action]]).

      - The equivalent **Polyakov action** introduces a worldsheet metric; it makes quantization easier and reveals 2D conformal symmetry.
      - In a convenient gauge the equations of motion become the 2D wave equation $\partial_\tau^2 X^\mu = \partial_\sigma^2 X^\mu$, solved by a sum of normal modes $\alpha^\mu_n$ ([[Waves, Interference & Normal Modes]]).
      - Open strings have endpoints; closed strings are loops with left- and right-moving waves.

      Quantizing those modes: [[Light-Cone Quantization]] → [[Bosonic String]].
    `,
    sources: ['Barton Zwiebach — A First Course in String Theory, chapters 6–7'],
  }),

  entry('light-cone-quantization', 'concept', A, 'curious', 'Light-Cone Quantization', {
    summary: 'Choose coordinates along the light cone so that only the D − 2 transverse directions of the string carry real oscillations. Then quantize those as harmonic oscillators.',
    latex: md`X^\pm = \frac{X^0 \pm X^{D-1}}{\sqrt2}, \qquad [\alpha^i_m, \alpha^j_n] = m\,\delta^{ij}\,\delta_{m+n,0}, \qquad i,j = 1,\dots,D-2`,
    variables: [
      [md`X^+`, 'Light-cone time, set proportional to worldsheet time τ'],
      [md`\alpha^i_n`, 'Oscillator modes in transverse direction i (n < 0 create, n > 0 destroy)'],
    ],
    tags: ['strings', 'quantization'],
    body: md`
      Reparametrization symmetry of the string means not all $X^\mu$ are physical. Fixing $X^+$ to worldsheet time and solving for $X^-$ leaves only the **transverse** $X^i$, each a tower of [[Quantum Harmonic Oscillator|harmonic oscillators]] with $\alpha_{-n} \propto a_n^\dagger$.

      - No negative-norm states appear — but Lorentz invariance is no longer manifest.
      - Demanding it back forces the total zero-point energy to be $-1$, i.e. $D - 2 = 24$: [[Critical Dimension of the Bosonic String]].
      - Level $N$ counts oscillator excitations; the number of states at each level is generated by $\prod_n (1-q^n)^{-24}$ ([[Counting states of 24 string oscillators]]).
    `,
  }),

  entry('conformal-symmetry', 'concept', A, 'curious', 'Conformal Symmetry in Two Dimensions', {
    summary: 'Transformations that preserve angles. In two dimensions every holomorphic map is one, so the symmetry is infinite-dimensional.',
    latex: md`z \to f(z), \qquad \ell_n = -z^{n+1}\partial_z, \qquad [\ell_m, \ell_n] = (m-n)\,\ell_{m+n}`,
    variables: [
      [md`z = \sigma^1 + i\sigma^2`, 'Complex coordinate on the (Euclidean) worldsheet'],
      [md`\ell_n`, 'Generators of infinitesimal conformal maps — the Witt algebra'],
    ],
    tags: ['cft', 'symmetry'],
    body: md`
      In $d > 2$ dimensions conformal transformations form a finite group (translations, rotations, dilations, special conformal). In $d = 2$ any holomorphic function is angle-preserving ([[Complex Analysis & Laurent Series]]), giving infinitely many generators $\ell_n$.

      - $\ell_{-1}, \ell_0, \ell_1$ generate the global Möbius transformations $z \to \frac{az+b}{cz+d}$.
      - The $\ell_n$ satisfy the **Witt algebra** — an infinite-dimensional [[Lie Groups & Lie Algebras|Lie algebra]].
      - In the quantum theory it gains a central term and becomes the [[Virasoro Algebra]] (see [[Quantum Anomalies & the Central Charge]]).

      Why strings care: after gauge fixing, the Polyakov string is a 2D theory with exactly this symmetry.
    `,
  }),

  entry('conformal-field-theory', 'concept', A, 'curious', '2D Conformal Field Theory', {
    summary: 'Quantum field theories in two dimensions with conformal symmetry. They describe string worldsheets and critical phenomena, and are often exactly solvable.',
    latex: md`T(z) = \sum_{n\in\mathbb Z} L_n\,z^{-n-2}, \qquad L_0\ket{h} = h\ket{h}, \qquad L_{n>0}\ket{h} = 0`,
    variables: [
      [md`T(z)`, 'Holomorphic stress–energy tensor'],
      [md`L_n`, 'Its modes: Virasoro generators'],
      [md`\ket{h}`, 'Primary state of conformal weight h'],
    ],
    tags: ['cft', 'qft'],
    body: md`
      **Key ideas:**
      - **Radial quantization:** treat $|z|$ as time; circles around the origin are equal-time slices, and $L_0$ acts as the Hamiltonian.
      - **State–operator correspondence:** every state $\ket{a}$ equals a field inserted at $z = 0$ acting on the vacuum. This is the axiom a [[Vertex Operator Algebra]] formalizes.
      - **Primaries and descendants:** primary states are annihilated by $L_{n>0}$; $L_{-n}$ build descendants. Representations of the [[Virasoro Algebra]].
      - **Central charge $c$** counts degrees of freedom: a free boson has $c = 1$.
      - **Operator products** are captured by the [[Operator Product Expansion]].
      - On a torus the theory has a partition function that must be modular invariant: [[Torus Partition Function & Modular Invariance]].

      Built on [[Quantum Field Theory]] plus [[Conformal Symmetry in Two Dimensions]].
    `,
    sources: ['Di Francesco, Mathieu & Sénéchal — Conformal Field Theory', 'Ralph Blumenhagen & Erik Plauschinn — Introduction to Conformal Field Theory'],
  }),

  entry('operator-product-expansion', 'equation', A, 'curious', 'Operator Product Expansion', {
    summary: 'When two fields approach each other, their product becomes a sum of single fields with singular coefficients. In 2D CFT this encodes the whole algebra.',
    latex: md`T(z)\,T(w) \sim \frac{c/2}{(z-w)^4} + \frac{2\,T(w)}{(z-w)^2} + \frac{\partial T(w)}{z-w}, \qquad T(z)\,\phi(w) \sim \frac{h\,\phi(w)}{(z-w)^2} + \frac{\partial\phi(w)}{z-w}`,
    variables: [
      [md`\sim`, 'Equal up to terms that stay finite as z → w'],
      [md`\phi`, 'A primary field of weight h'],
      [md`c`, 'Central charge'],
    ],
    tags: ['cft'],
    body: md`
      The singular part of the OPE, extracted with contour integrals and residues ([[Complex Analysis & Laurent Series]]), gives commutators of modes. From the $TT$ OPE above one derives exactly the [[Virasoro Algebra]] — the $(z-w)^{-4}$ term is the central charge.

      A [[Vertex Operator Algebra]] is essentially a consistent set of OPEs: $Y(a,z)\,Y(b,w)$ expands in $Y(a_{(n)}b, w)$. The **locality** axiom says fields commute up to these singularities.
    `,
  }),

  entry('torus-partition-function', 'equation', A, 'curious', 'Torus Partition Function & Modular Invariance', {
    summary: 'Put a 2D CFT on a torus and compute its partition function. Since the torus shape is only defined up to SL(2,ℤ), the answer must be modular invariant — the reason j and the number 24 appear.',
    latex: md`Z(\tau) = \operatorname{Tr}_{\mathcal H}\, q^{\,L_0 - c/24}\,\bar q^{\,\bar L_0 - \bar c/24}, \qquad q = e^{2\pi i\tau}, \qquad Z\!\left(\frac{a\tau+b}{c\tau+d}\right) = Z(\tau)`,
    variables: [
      [md`\tau`, 'Shape of the torus'],
      [md`-c/24`, 'Ground-state (Casimir) energy on a circle'],
      [md`\mathcal H`, 'Space of states'],
    ],
    tags: ['cft', 'modular forms', '24 dimensions', 'bridge'],
    body: md`
      **It is a thermal partition function:** $\operatorname{Tr}\,e^{-\beta H}$ ([[Boltzmann Distribution & Partition Function]]) for a theory on a circle, with $\beta$ and a twist combined into $\tau$. The torus is time-circle × space-circle, and swapping them ($\tau \to -1/\tau$) must give the same answer ([[Tori, Lattices in ℂ & Elliptic Curves]]).

      **Why $c = 24$ is special.** For a chiral theory $Z = q^{-c/24}\sum_n \dim V_n\,q^n$. Under $\tau \to \tau + 1$ the prefactor picks up a phase $e^{-2\pi i c/24}$, so exact invariance needs $c$ to be a multiple of 24. At $c = 24$:
      $$Z = q^{-1} + \dim V_1 + \dim V_2\,q + \cdots$$
      A modular function with a simple pole — a constant plus $j$ ([[Modular Group & Modular Forms]]). The [[Moonshine Module]] has $\dim V_1 = 0$, so $Z = j - 744$.

      Orbifolds must add twisted sectors precisely to keep $Z$ invariant ([[Orbifolds & Twisted Sectors]]).
    `,
  }),

  entry('example-24-oscillators', 'example', A, 'curious', 'Counting states of 24 string oscillators', {
    summary: 'The number of string states at each energy level is 1, 24, 324, 3200, 25650, … — the coefficients of 1/η(τ)²⁴.',
    tags: ['strings', 'counting', '24 dimensions'],
    body: md`
      Each of 24 transverse directions has oscillators $\alpha_{-1}, \alpha_{-2}, \dots$ adding energy $1, 2, \dots$. By [[Generating Functions & q-Series]]:

      $$\prod_{n\ge1}\frac{1}{(1-q^n)^{24}} = 1 + 24q + 324q^2 + 3200q^3 + 25650q^4 + 176256q^5 + \cdots$$

      **Check level 1:** one $\alpha^i_{-1}$ in any of 24 directions → 24 states. For the open string this level is massless: 24 polarizations of a massless vector in 26 dimensions, the photon-like state that forced $D = 26$.

      **Check level 2:** either $\alpha^i_{-2}$ (24 ways) or $\alpha^i_{-1}\alpha^j_{-1}$ ($\binom{24}{2} + 24 = 300$ ways) → 324.

      **Link to modular forms:** multiply by $q^{-1}$ (the zero-point energy $-24/24$) and you get $1/\eta^{24} = 1/\Delta$ ([[Eisenstein Series, η and the Discriminant]]) — the same series used in [[Computing 744 and 196884 from E₄ and Δ]].
    `,
  }),

  entry('anomalies', 'concept', A, 'curious', 'Quantum Anomalies & the Central Charge', {
    summary: 'A symmetry of the classical theory that can’t survive quantization. In string theory the conformal anomaly must cancel, which fixes the dimension of spacetime.',
    latex: md`\langle T^a{}_a\rangle \propto c\,R, \qquad c_{\text{total}} = c_{\text{matter}} + c_{\text{ghost}} = D - 26 \stackrel{!}{=} 0`,
    variables: [
      [md`T^a{}_a`, 'Trace of the worldsheet stress tensor (zero classically)'],
      [md`R`, 'Curvature of the worldsheet'],
      [md`c_{\text{ghost}} = -26`, 'Contribution of the Faddeev–Popov ghosts'],
    ],
    tags: ['qft', 'strings', 'anomalies'],
    body: md`
      Classically the string worldsheet theory is Weyl (scale) invariant: its stress tensor is traceless. Quantum mechanically, regularizing products of fields at the same point ([[Regularization & Renormalization]]) produces a trace proportional to the **central charge**. The same number appears as the $c/12$ term in the [[Virasoro Algebra]].

      - A consistent string needs total $c = 0$, so matter must supply $c = 26$: 26 free bosons, or 2 bosons plus a $c = 24$ theory like the [[Moonshine Module]].
      - Other famous anomalies: the chiral anomaly (explains $\pi^0 \to \gamma\gamma$); gauge anomaly cancellation constrains the Standard Model and fixed the superstring gauge groups.

      Anomalies are broken [[Noether’s Theorem|Noether symmetries]] with a precise, calculable coefficient.
    `,
  }),

  entry('ghosts-no-ghost', 'theory', A, 'curious', 'Ghosts, BRST & the No-Ghost Theorem', {
    summary: 'Gauge fixing the string introduces unphysical “ghost” fields. The no-ghost theorem says that at D = 26 all remaining physical states have positive norm.',
    tags: ['strings', 'gauge symmetry'],
    body: md`
      - **Covariant quantization** keeps all $D$ directions, including time, whose oscillators create **negative-norm** states — probabilities below zero, unphysical.
      - **Faddeev–Popov ghosts** $b, c$ (with $c_{\text{ghost}} = -26$) appear when fixing the worldsheet gauge. **BRST symmetry** picks out physical states as a cohomology.
      - **No-ghost theorem** (Brower; Goddard and Thorn, 1972): for $D = 26$ the physical states have non-negative norm and match the light-cone spectrum ([[Light-Cone Quantization]]). For $D > 26$ it fails.

      **Why it matters for moonshine:** Borcherds replaced 24 of the 26 free bosons by the [[Moonshine Module]] and used the no-ghost theorem to show the physical states form a Lie algebra on which the Monster acts — [[Borcherds–Kac–Moody Algebras & the Monster Lie Algebra]].
    `,
  }),

  entry('compactification', 'concept', A, 'curious', 'Compactification on a Torus', {
    summary: 'Curl some dimensions up into a small torus. Momentum along them becomes quantized, strings can wind around them, and the allowed charges form a lattice.',
    latex: md`X \sim X + 2\pi R, \qquad p = \frac{n}{R}, \qquad w = \frac{m R}{\alpha'}, \qquad \mathbb R^d / \Lambda`,
    variables: [
      [md`R`, 'Radius of the compact circle'],
      [md`n`, 'Momentum quantum number'],
      [md`m`, 'Winding number (strings only)'],
      [md`\Lambda`, 'Lattice defining a d-dimensional torus'],
    ],
    tags: ['strings', 'lattices', 'dimensions'],
    body: md`
      - **Momentum quantization:** a wavefunction on a circle must be periodic, so $p = n/R$ ([[Fourier Series & Transforms]]).
      - **Winding:** a closed string can wrap $m$ times, costing energy proportional to $R$.
      - **T-duality:** swapping $n \leftrightarrow m$ and $R \leftrightarrow \alpha'/R$ gives the same physics.
      - For a torus $\mathbb R^d/\Lambda$, momentum and winding charges combine into a lattice. Consistency of the chiral theory needs it to be **even unimodular** ([[Lattices & Theta Functions]]).

      With $\Lambda$ = [[Leech Lattice]] and $d = 24$, the 24 transverse directions of the bosonic string are all curled up — the starting point of [[Lattice Vertex Algebras]].
    `,
  }),

  entry('lattice-voa', 'equation', A, 'curious', 'Lattice Vertex Algebras', {
    summary: 'Free bosons on a torus ℝᵈ/Λ form a vertex algebra with central charge d. Its graded dimension is the lattice theta function divided by η(τ)ᵈ.',
    latex: md`V_\Lambda = \mathcal F^{\otimes d} \otimes \mathbb C[\Lambda], \qquad q^{-d/24}\sum_n \dim (V_\Lambda)_n\,q^n = \frac{\theta_\Lambda(\tau)}{\eta(\tau)^d}, \qquad \dim (V_\Lambda)_1 = d + \#\{\mathbf v : \mathbf v\cdot\mathbf v = 2\}`,
    variables: [
      [md`\mathcal F`, 'Fock space of one free boson’s oscillators'],
      [md`\mathbb C[\Lambda]`, 'One momentum state e^v for each lattice vector v'],
      [md`d`, 'Rank of the lattice = central charge'],
    ],
    tags: ['vertex algebras', 'lattices', 'cft'],
    body: md`
      A state is a momentum $e^{\mathbf v}$ ($\mathbf v \in \Lambda$, weight $\mathbf v\cdot\mathbf v/2$) dressed with oscillators $\alpha^i_{-n}$ ([[Second Quantization & Fock Space]]). Counting both gives theta function × oscillator series.

      - **$E_8$ lattice ($d = 8$):** 240 roots, so $\dim V_1 = 248$ — the dimension of the Lie algebra $E_8$. The weight-1 space of a lattice VOA is always a Lie algebra.
      - **Leech lattice ($d = 24$):** no roots, so $\dim V_1 = 24$ only. Its character is $\theta_{\text{Leech}}/\eta^{24} = q^{-1} + 24 + 196884\,q + \cdots$.

      Removing those last 24 states is the job of the orbifold: [[From the Leech lattice to j − 744]].

      Builds on [[Vertex Operator Algebra]], [[Lattices & Theta Functions]], [[Compactification on a Torus]].
    `,
  }),

  entry('example-leech-to-j', 'example', A, 'curious', 'From the Leech lattice to j − 744', {
    summary: 'The Leech lattice VOA counts q⁻¹ + 24 + 196884q + …; the ℤ₂ orbifold removes the 24 and reshuffles level 2 into 300 + 98280 + 98304 = 196884.',
    tags: ['moonshine', 'lattices', 'vertex algebras'],
    body: md`
      **Step 1 — Leech theta function.** No vectors of length² 2, and 196,560 of length² 4:
      $$\theta_{\text{Leech}} = 1 + 196560\,q^2 + 16773120\,q^3 + \cdots = E_4^3 - 720\,\Delta$$

      **Step 2 — divide by $\eta^{24} = \Delta$** ([[Lattice Vertex Algebras]]):
      $$\frac{\theta_{\text{Leech}}}{\Delta} = j - 720 = q^{-1} + 24 + 196884\,q + 21493760\,q^2 + \cdots$$

      **Step 3 — orbifold by $X \to -X$** ([[Orbifolds & Twisted Sectors]]). Keep states invariant under the reflection, add the twisted sector:
      - Level 1: the 24 states $\alpha^i_{-1}$ are odd → removed. $\dim V^\natural_1 = 0$.
      - Level 2, untwisted: $\alpha^i_{-1}\alpha^j_{-1}$ gives $300$; the $196560$ states $e^{\mathbf v}$ pair up as $e^{\mathbf v} + e^{-\mathbf v}$, giving $98280$.
      - Level 2, twisted sector: $2^{12} \times 24 = 98304$.
      - Total: $300 + 98280 + 98304 = 196884$ ✓

      **Result:** graded dimension $q^{-1} + 0 + 196884\,q + \cdots = j - 744$, the [[Moonshine Module]] — and its symmetry group turns out to be the Monster.
    `,
  }),

  entry('orbifolds', 'concept', A, 'curious', 'Orbifolds & Twisted Sectors', {
    summary: 'Divide a space (or a CFT) by a symmetry group. Keep the invariant states, and add “twisted” states that close only up to the symmetry.',
    latex: md`\mathcal H_{\text{orb}} = \left(\mathcal H_{\text{untw}}\right)^{G} \oplus \left(\mathcal H_{\text{tw}}\right)^{G}, \qquad X(\sigma + 2\pi) = g\cdot X(\sigma)`,
    variables: [
      [md`G`, 'Symmetry group being divided out (for moonshine: ℤ₂, X → −X)'],
      [md`(\cdot)^G`, 'The G-invariant part'],
    ],
    tags: ['strings', 'cft', 'symmetry'],
    body: md`
      **Geometry:** $\mathbb R/\mathbb Z_2$ (fold the line at 0) is a half-line with a fixed point. Orbifolds are spaces with such singular points.

      **In a CFT:**
      1. **Project** onto states invariant under $G$ ([[Groups & Symmetry]]).
      2. **Twisted sectors:** closed strings that come back to themselves only up to $g$. On the torus these are forced by modular invariance — $\tau \to -1/\tau$ turns a projection in "time" into a twist in "space" ([[Torus Partition Function & Modular Invariance]]).

      For $\mathbb Z_2$ acting on 24 bosons, twisted boundary conditions make the modes half-integer ($\alpha_{-1/2}, \alpha_{-3/2}, \dots$), and the zero modes form a $2^{12} = 4096$-dimensional representation. That is where the $98304 = 4096\times 24$ comes from in [[From the Leech lattice to j − 744]].
    `,
  }),

  entry('golay-m24', 'concept', A, 'curious', 'Golay Code & the Mathieu Group M₂₄', {
    summary: 'A perfect error-correcting code on 24 bits whose symmetry group is the sporadic group M₂₄. The Leech lattice is built from it.',
    latex: md`\mathcal G_{24} \subset \mathbb F_2^{24}: \ \dim = 12,\ \text{min weight } 8, \qquad |M_{24}| = 244\,823\,040`,
    variables: [
      [md`\mathbb F_2^{24}`, 'All 24-bit strings'],
      [md`\mathcal G_{24}`, 'Extended binary Golay code: 4096 codewords'],
    ],
    tags: ['sporadic groups', 'codes', '24 dimensions'],
    body: md`
      - $2^{12} = 4096$ codewords; any two differ in at least 8 bits, so it corrects 3-bit errors. Weights are 0, 8, 12, 16, 24; the 759 codewords of weight 8 are the **octads**. Used by Voyager 1 and 2 (1979–81) to send colour images.
      - Its symmetry group $M_{24}$ is one of the five Mathieu groups — the first sporadic groups found (1861–73) ([[Classification of Finite Simple Groups]]).

      **To the Leech lattice:** take vectors in $\mathbb Z^{24}$ whose coordinates mod 2 form a Golay codeword (with extra parity conditions), scale, and add one "glue" vector. Symmetries of the code extend to the lattice, whose full symmetry group is the Conway group $Co_0$ ([[Leech Lattice]]).

      $M_{24}$ reappears in string theory on K3 surfaces: [[Mathieu & Umbral Moonshine]].
    `,
  }),

  entry('borcherds-algebras', 'concept', A, 'curious', 'Borcherds–Kac–Moody Algebras & the Monster Lie Algebra', {
    summary: 'Infinite-dimensional Lie algebras with imaginary simple roots. The Monster Lie algebra, built from a 26-dimensional string, was Borcherds’ key to proving moonshine.',
    latex: md`p^{-1}\prod_{m>0,\ n\in\mathbb Z}\left(1 - p^m q^n\right)^{c(mn)} = j(p) - j(q)`,
    variables: [
      [md`c(k)`, 'Coefficients of J(q) = j(q) − 744 = Σ c(k) qᵏ'],
      [md`p,\ q`, 'Two independent formal variables'],
    ],
    tags: ['lie algebras', 'moonshine'],
    body: md`
      **Construction:** take the [[Moonshine Module]] ($c = 24$) and the vertex algebra of a 2D Lorentzian lattice $II_{1,1}$ ($c = 2$). Together: $c = 26$, a bosonic string. Its physical states, by the [[Ghosts, BRST & the No-Ghost Theorem|no-ghost theorem]], form the **Monster Lie algebra** $\mathfrak m$, graded by $II_{1,1}$, with the Monster acting on it.

      **The denominator identity** above expresses $\mathfrak m$’s structure as an infinite product. Twisting it by each Monster element $g$ gives identities that force every McKay–Thompson series $T_g$ to be a [[Genus-Zero Groups & Hauptmoduln|Hauptmodul]] — the Conway–Norton conjecture ([[Monstrous Moonshine]]).

      Kac–Moody algebras (1968) generalize finite [[Lie Groups & Lie Algebras|Lie algebras]] with Cartan matrices; Borcherds (1988) allowed imaginary simple roots.
    `,
    sources: ['Richard Borcherds — Monstrous moonshine and monstrous Lie superalgebras, Invent. Math. 109 (1992)'],
  }),

  entry('superstrings', 'concept', A, 'curious', 'Superstring Theory', {
    summary: 'Add worldsheet fermions to the bosonic string: the tachyon disappears, spacetime fermions appear, and the critical dimension drops to 10.',
    latex: md`c = D\left(1 + \tfrac12\right) = \tfrac32 D, \qquad c_{\text{ghost}} + c_{\text{superghost}} = -26 + 11 = -15 \;\Longrightarrow\; D = 10`,
    variables: [
      [md`1 + \tfrac12`, 'Central charge of one boson plus its fermion partner'],
    ],
    tags: ['strings', 'supersymmetry'],
    body: md`
      - **Supersymmetry on the worldsheet** pairs each $X^\mu$ with a fermion $\psi^\mu$.
      - **GSO projection** removes the tachyon and yields spacetime supersymmetry.
      - **Five consistent theories:** Type I, IIA, IIB, heterotic $SO(32)$, heterotic $E_8\times E_8$ — all related by dualities. The heterotic gauge groups come from the even unimodular lattices in 16 dimensions ([[Lattices & Theta Functions]]).
      - Six extra dimensions are compactified; the simplest non-trivial choices include K3 surfaces and Calabi–Yau spaces.

      Improves on the [[Bosonic String]]; the setting for [[Mathieu & Umbral Moonshine]].
    `,
    sources: ['Becker, Becker & Schwarz — String Theory and M-Theory'],
  }),

  entry('mathieu-umbral-moonshine', 'theory', A, 'curious', 'Mathieu & Umbral Moonshine', {
    summary: 'Moonshine beyond the Monster: the sporadic group M₂₄ appears in strings compactified on K3 surfaces, and 23 more moonshines are tied to Niemeier lattices.',
    tags: ['moonshine', 'strings', 'open question'],
    body: md`
      **Mathieu moonshine** (Eguchi, Ooguri, Tachikawa, 2010). The elliptic genus of a K3 surface, expanded in characters of the $N=4$ superconformal algebra, has multiplicities $90, 462, 1540, \dots$ — and these are dimensions of representations of $M_{24}$ ($90 = 45 + 45$, $462 = 231 + 231$, $1540 = 770 + 770$). Gannon proved in 2012 that an $M_{24}$ module exists; **no known K3 sigma model has $M_{24}$ symmetry**, so the underlying structure is still unknown.

      **Umbral moonshine** (Cheng, Duncan, Harvey, 2012): one moonshine for each of the 23 Niemeier lattices with roots, with mock modular forms instead of modular functions. Proved by Duncan, Griffin and Ono (2015).

      These live in superstring compactifications ([[Superstring Theory]]), closer to realistic physics than the 26-dimensional setting of [[Monstrous Moonshine]]. See [[Golay Code & the Mathieu Group M₂₄]].
    `,
  }),

  entry('ads-cft', 'theory', A, 'curious', 'Anti-de Sitter Space & AdS/CFT', {
    summary: 'Quantum gravity in a negatively curved spacetime can be exactly equivalent to an ordinary quantum field theory on its boundary. Witten’s Monster proposal is a 3D example.',
    latex: md`c = \frac{3\,\ell}{2\,G_3}, \qquad c = 24k \ \text{(Witten’s extremal CFTs)}`,
    variables: [
      [md`\ell`, 'AdS radius of curvature'],
      [md`G_3`, 'Newton’s constant in three dimensions'],
      [md`c`, 'Central charge of the boundary 2D CFT (Brown–Henneaux, 1986)'],
    ],
    tags: ['quantum gravity', 'holography', 'cft'],
    body: md`
      **Anti-de Sitter space** is the maximally symmetric spacetime with negative cosmological constant. Its boundary is at infinite distance, but light reaches it in finite time.

      **Holography** (Maldacena, 1997): string theory on $AdS_5 \times S^5$ equals a 4D gauge theory on the boundary. Gravity in the bulk ↔ a non-gravitational [[Quantum Field Theory]] on the boundary. Black holes in the bulk ↔ thermal states on the boundary.

      **In three dimensions:** Brown and Henneaux showed the asymptotic symmetries of $AdS_3$ form two copies of the [[Virasoro Algebra]] with $c = 3\ell/2G_3$. Witten (2007) proposed that pure 3D gravity at $c = 24k$ is dual to an "extremal" CFT; for $k = 1$ that would be the [[Moonshine Module]], with [[Black Holes & Event Horizons|BTZ black holes]] counted by the coefficients of $j$. Open — see [[Does the Monster describe our universe?]]

      Builds on [[2D Conformal Field Theory]] and the [[Einstein Field Equations]].
    `,
  }),
];
