// [from, kind, to, why]. builds-on / derived-from / part-of mark basics.

export const EXPANSION_LINKS = [
  // ---------------------------------------------------------------- maths
  ['octonions', 'builds-on', 'complex-numbers', 'The next steps after ℂ: quaternions, then octonions'],
  ['octonions', 'related', 'lie-algebras', 'Their symmetry group G₂ is the smallest exceptional Lie group'],
  ['e8', 'builds-on', 'lie-algebras', 'The largest exceptional simple Lie algebra'],
  ['e8', 'builds-on', 'lattices', 'Its roots form the unique even unimodular lattice in 8D'],
  ['e8', 'related', 'eisenstein-discriminant', 'The theta function of the E₈ lattice is exactly E₄'],
  ['e8', 'related', 'lattice-voa', 'Its lattice VOA’s weight-1 space is the 248-dimensional E₈ algebra'],
  ['e8', 'related', 'superstrings', 'The heterotic string’s E₈ × E₈ gauge group'],
  ['e8', 'related', 'octonions', 'E₈ can be built from the octonions'],
  ['e8', 'related', 'conformal-field-theory', 'An E₈ field theory described a real magnet at its critical point'],
  ['sphere-packing', 'builds-on', 'lattices', 'Lattices are the natural candidates for dense packings'],
  ['sphere-packing', 'builds-on', 'modular-forms', 'Viazovska’s proof is built from modular forms'],
  ['sphere-packing', 'related', 'e8', 'The densest packing in 8 dimensions'],
  ['sphere-packing', 'related', 'leech-lattice', 'The densest packing in 24 dimensions'],
  ['why-24', 'related', 'sphere-packing', 'Packing was solved in 8 and 24 dimensions — and nowhere else above 3'],
  ['riemann-hypothesis', 'builds-on', 'riemann-zeta', 'A claim about exactly where ζ vanishes'],
  ['riemann-hypothesis', 'related', 'eigenvalues', 'Are the zeros the eigenvalues of some quantum Hamiltonian?'],
  ['modularity-fermat', 'builds-on', 'modular-forms', 'Every elliptic curve comes from a modular form'],
  ['modularity-fermat', 'builds-on', 'tori-elliptic-curves', 'A counterexample would give a forbidden elliptic curve'],
  ['ramanujan-tau', 'builds-on', 'eisenstein-discriminant', 'τ(n) are the coefficients of Δ'],
  ['ramanujan-tau', 'related', 'example-24-oscillators', '1/Δ counts string states; Δ itself gives τ(n)'],
  ['ramanujan-tau', 'related', 'why-24', 'Δ = η²⁴'],
  ['knot-theory', 'builds-on', 'topology-winding', 'Telling knots apart is a topology problem'],
  ['knot-theory', 'builds-on', 'quantum-field-theory', 'Knot invariants computed by a topological QFT'],
  ['knot-theory', 'related', 'quantum-hall-effect', 'Chern–Simons theory also describes anyons'],
  ['topology-winding', 'builds-on', 'vector-calculus', 'A winding number is a loop integral of a gradient'],
  ['topology-winding', 'explains', 'quantized-circulation', 'Why circulation comes in whole units'],
  ['topology-winding', 'related', 'complex-numbers', 'Winding once is e^{iθ} going all the way round'],

  // ---------------------------------------------------------------- strings & dimensions
  ['kaluza-klein', 'builds-on', 'einstein-field-equations', 'Einstein’s equations in five dimensions'],
  ['kaluza-klein', 'builds-on', 'compactification', 'The fifth dimension is a tiny circle'],
  ['kaluza-klein', 'related', 'maxwell-light', 'Maxwell’s equations fall out of 5D gravity'],
  ['kaluza-klein', 'related', 'gauge-symmetry', 'Rotating the hidden circle is the electromagnetic gauge symmetry'],
  ['calabi-yau', 'builds-on', 'riemannian-geometry', 'Curved spaces with zero Ricci curvature'],
  ['calabi-yau', 'builds-on', 'manifolds', 'Six-dimensional complex manifolds'],
  ['calabi-yau', 'related', 'superstrings', 'Where superstrings hide their six extra dimensions'],
  ['calabi-yau', 'related', 'mathieu-umbral-moonshine', 'The K3 surface is the two-dimensional Calabi–Yau'],
  ['calabi-yau', 'related', 'standard-model', 'Topology could fix the number of particle generations'],
  ['calabi-yau', 'related', 'kaluza-klein', 'Kaluza–Klein with six hidden dimensions instead of one'],
  ['t-duality', 'builds-on', 'compactification', 'Momentum and winding trade places'],
  ['t-duality', 'related', 'd-branes', 'D-branes were found by T-dualizing open strings'],
  ['d-branes', 'builds-on', 'superstrings', 'Extended objects in string theory'],
  ['d-branes', 'explains', 'holographic-principle', 'Strominger–Vafa counted black hole microstates with branes'],
  ['d-branes', 'related', 'ads-cft', 'AdS/CFT came from looking at D3-branes two ways'],
  ['d-branes', 'related', 'gauge-symmetry', 'Strings stretched between branes carry gauge forces'],
  ['holographic-principle', 'builds-on', 'black-holes', 'The entropy of an event horizon'],
  ['holographic-principle', 'builds-on', 'thermodynamics', 'Entropy counts microstates'],
  ['holographic-principle', 'derived-from', 'hawking-radiation', 'Hawking’s temperature fixes the factor 1/4'],
  ['holographic-principle', 'related', 'ads-cft', 'Holography made precise'],
  ['supersymmetry', 'builds-on', 'identical-particles', 'A symmetry that swaps bosons and fermions'],
  ['supersymmetry', 'builds-on', 'minkowski-spacetime', 'It extends the symmetries of spacetime'],
  ['supersymmetry', 'related', 'superstrings', 'Worldsheet supersymmetry removes the tachyon'],
  ['supersymmetry', 'related', 'vacuum-energy-problem', 'Boson and fermion zero-point energies cancel'],
  ['supersymmetry', 'related', 'higgs-mechanism', 'Would explain why the Higgs is so light'],

  // ---------------------------------------------------------------- quantum
  ['quantum-tunneling', 'builds-on', 'schrodinger-equation', 'Decaying waves leak through the barrier'],
  ['hydrogen-atom', 'builds-on', 'schrodinger-equation', 'Solve it with the Coulomb potential'],
  ['hydrogen-atom', 'related', 'spin', 'Orbitals are labelled by angular momentum; spin splits the lines'],
  ['hydrogen-atom', 'related', 'atomic-clocks', 'Its 21 cm line ticks in hydrogen masers'],
  ['hydrogen-atom', 'related', 'dirac-equation', 'Fine structure needs the Dirac equation'],
  ['hydrogen-atom', 'related', 'wave-particle-duality', 'Each jump between levels emits a photon of energy hf'],
  ['fermi-dirac', 'builds-on', 'statistical-mechanics', 'Same derivation as Bose–Einstein, at most one per state'],
  ['fermi-dirac', 'builds-on', 'identical-particles', 'Only for fermions'],
  ['fermi-dirac', 'related', 'bose-einstein-statistics', 'Flip −1 to +1 and everything changes'],
  ['stimulated-emission', 'builds-on', 'second-quantization', 'The n + 1 comes from creation operators'],
  ['stimulated-emission', 'builds-on', 'identical-particles', 'Only bosons get the enhancement'],
  ['stimulated-emission', 'related', 'bose-einstein-condensate', 'A condensate let out is an atom laser'],
  ['stimulated-emission', 'related', 'laser-cooling', 'Lasers are what make condensates possible'],
  ['stimulated-emission', 'related', 'planck-blackbody', 'Einstein needed it to derive Planck’s law'],
  ['path-integral', 'builds-on', 'lagrangian-mechanics', 'Every path weighted by e^{iS/ħ}'],
  ['path-integral', 'builds-on', 'superposition', 'Amplitudes for all paths add up'],
  ['path-integral', 'related', 'schrodinger-equation', 'Equivalent to it for ordinary quantum mechanics'],
  ['path-integral', 'related', 'quantum-field-theory', 'Feynman diagrams come from expanding it'],
  ['path-integral', 'related', 'torus-partition-function', 'Strings sum over worldsheets — tori included'],
  ['path-integral', 'same-idea', 'statistical-mechanics', 'In imaginary time it becomes a partition function'],
  ['dirac-equation', 'builds-on', 'four-momentum', 'Built to respect E² = (pc)² + (mc²)²'],
  ['dirac-equation', 'builds-on', 'schrodinger-equation', 'First order in time, like Schrödinger’s'],
  ['dirac-equation', 'explains', 'spin', 'Spin ½ and g = 2 come out automatically'],
  ['dirac-equation', 'related', 'quantum-field-theory', 'Antiparticles only fully make sense as fields'],
  ['gauge-symmetry', 'builds-on', 'noether-theorem', 'Make a global symmetry local'],
  ['gauge-symmetry', 'builds-on', 'maxwell-light', 'Electromagnetism is the simplest gauge theory'],
  ['gauge-symmetry', 'builds-on', 'lie-algebras', 'SU(2) and SU(3) give the weak and strong forces'],
  ['gauge-symmetry', 'related', 'ghosts-no-ghost', 'Gauge redundancy is why ghosts are needed'],
  ['higgs-mechanism', 'builds-on', 'spontaneous-symmetry-breaking', 'The universe picks a point on the Mexican hat'],
  ['higgs-mechanism', 'builds-on', 'gauge-symmetry', 'The gauge boson swallows the Goldstone mode and gets mass'],
  ['higgs-mechanism', 'same-idea', 'superconductivity', 'The Meissner effect is a Higgs mechanism for the photon'],
  ['higgs-mechanism', 'part-of', 'standard-model', 'How W, Z, quarks and leptons get mass'],
  ['standard-model', 'builds-on', 'gauge-symmetry', 'Its forces are gauge fields'],
  ['standard-model', 'builds-on', 'quantum-field-theory', 'A quantum field theory of every known particle'],
  ['standard-model', 'related', 'anomalies', 'Anomalies cancel between quarks and leptons'],
  ['standard-model', 'tension', 'einstein-field-equations', 'Our two best theories refuse to combine'],
  ['bell-chsh', 'builds-on', 'entanglement', 'A test of entangled correlations'],
  ['bell-chsh', 'builds-on', 'probability', 'Averages of ±1 outcomes'],
  ['bell-chsh', 'related', 'measurement-problem', 'Rules out answers that exist before you look (locally)'],
  ['bell-chsh', 'related', 'quantum-computing', 'Certifies quantum randomness and secure keys'],
  ['measurement-problem', 'builds-on', 'superposition', 'Superpositions never pick one result on their own'],
  ['measurement-problem', 'builds-on', 'decoherence', 'Decoherence explains part of it, not all'],
  ['measurement-problem', 'related', 'born-rule', 'Where do the probabilities come from?'],
  ['measurement-problem', 'related', 'clocks-superposition-gravity', 'Gravity-induced collapse could be tested with superposed masses'],
  ['quantum-computing', 'builds-on', 'superposition', '2ⁿ amplitudes at once'],
  ['quantum-computing', 'builds-on', 'entanglement', 'Useful many-qubit states are entangled'],
  ['quantum-computing', 'tension', 'decoherence', 'Decoherence is the enemy'],
  ['quantum-computing', 'related', 'example-qubit', 'The basic unit'],
  ['quantum-computing', 'related', 'josephson-effect', 'Superconducting qubits are Josephson circuits'],
  ['quantum-computing', 'related', 'landauer-principle', 'Reversible computing avoids the erasure cost'],
  ['superconductivity', 'builds-on', 'quasiparticles', 'Phonons glue electrons into Cooper pairs'],
  ['superconductivity', 'builds-on', 'fermi-dirac', 'Pairing happens among electrons near the Fermi energy'],
  ['superconductivity', 'same-idea', 'superfluidity', 'Zero resistance is zero viscosity for charged pairs'],
  ['superconductivity', 'related', 'quantized-circulation', 'Flux quantized in h/2e, like circulation in h/m'],
  ['superconductivity', 'related', 'identical-particles', 'Two fermions make a boson'],
  ['josephson-effect', 'builds-on', 'superconductivity', 'A direct readout of the superconducting phase'],
  ['josephson-effect', 'builds-on', 'quantum-tunneling', 'Cooper pairs tunnel across the barrier'],
  ['quantum-hall-effect', 'builds-on', 'topology-winding', 'The plateaus are topological (Chern) numbers'],
  ['quantum-hall-effect', 'builds-on', 'fermi-dirac', 'Electrons filling Landau levels'],
  ['quantum-hall-effect', 'related', 'identical-particles', 'Its anyons are neither bosons nor fermions'],
  ['quantum-hall-effect', 'related', 'quantum-computing', 'Braiding anyons could protect qubits from noise'],
  ['degeneracy-pressure', 'builds-on', 'fermi-dirac', 'Stacked-up fermions push back'],
  ['degeneracy-pressure', 'builds-on', 'four-momentum', 'Relativistic electrons weaken the pressure — hence the limit'],
  ['degeneracy-pressure', 'builds-on', 'newtonian-gravity', 'Quantum pressure against gravity'],
  ['neutron-stars', 'builds-on', 'degeneracy-pressure', 'What happens past the Chandrasekhar limit'],
  ['neutron-stars', 'related', 'superfluidity', 'A neutron superfluid inside'],
  ['neutron-stars', 'related', 'quantized-circulation', 'Pulsar glitches: vortices unpinning'],
  ['neutron-stars', 'related', 'gravitational-time-dilation', 'Surface clocks tick at about 81% speed'],
  ['neutron-stars', 'related', 'black-holes', 'A little heavier, and they collapse'],
  ['neutron-stars', 'related', 'gravitational-waves', 'Binary pulsars and merging neutron stars'],
  ['vacuum-energy-problem', 'builds-on', 'quantum-harmonic-oscillator', 'Zero-point energy of every mode of every field'],
  ['vacuum-energy-problem', 'builds-on', 'expanding-universe', 'The observed dark energy is tiny'],
  ['vacuum-energy-problem', 'related', 'example-casimir', 'Differences in vacuum energy are real and measurable'],
  ['vacuum-energy-problem', 'related', 'regularization', 'The cutoff decides how bad the mismatch is'],
  ['vacuum-energy-problem', 'related', 'quantum-gravity-problem', 'Probably needs quantum gravity to resolve'],

  // ---------------------------------------------------------------- classical physics
  ['planck-blackbody', 'builds-on', 'bose-einstein-statistics', 'A photon gas: Bose–Einstein with μ = 0'],
  ['planck-blackbody', 'builds-on', 'wave-particle-duality', 'Energy comes in quanta hf'],
  ['planck-blackbody', 'related', 'quantum-harmonic-oscillator', 'Each mode of light is an oscillator'],
  ['rayleigh-scattering', 'builds-on', 'maxwell-light', 'Electrons shaken by light re-radiate'],
  ['rayleigh-scattering', 'related', 'planck-blackbody', 'The Sun’s spectrum is part of why the sky isn’t violet'],
  ['landauer-principle', 'builds-on', 'thermodynamics', 'The second law, applied to memory'],
  ['landauer-principle', 'builds-on', 'statistical-mechanics', 'Entropy counts states — including memory states'],
  ['landauer-principle', 'related', 'holographic-principle', 'Entropy as information, all the way to black holes'],

  // ---------------------------------------------------------------- relativity & cosmos
  ['gravitational-waves', 'builds-on', 'einstein-field-equations', 'Wave solutions of the field equations'],
  ['gravitational-waves', 'related', 'waves-normal-modes', 'Detected with laser interferometers'],
  ['gravitational-waves', 'related', 'speed-of-light', 'GW170817: they travel at exactly c'],
  ['gravitational-waves', 'related', 'black-holes', 'The first detection: two black holes merging'],
  ['hawking-radiation', 'builds-on', 'black-holes', 'Quantum fields near a horizon'],
  ['hawking-radiation', 'builds-on', 'quantum-field-theory', 'Quantum field theory on curved spacetime'],
  ['hawking-radiation', 'builds-on', 'planck-blackbody', 'The spectrum is thermal'],
  ['hawking-radiation', 'related', 'quantum-gravity-problem', 'The black hole information paradox'],
  ['expanding-universe', 'builds-on', 'einstein-field-equations', 'Friedmann’s solution for a uniform universe'],
  ['expanding-universe', 'related', 'degeneracy-pressure', 'Exploding white dwarfs revealed the acceleration'],
  ['cmb', 'builds-on', 'planck-blackbody', 'The most perfect blackbody spectrum ever measured'],
  ['cmb', 'builds-on', 'expanding-universe', 'Stretched about 1,100 times by expansion'],
  ['cmb', 'related', 'hydrogen-atom', 'Released when the first hydrogen atoms formed'],
  ['er-epr', 'builds-on', 'entanglement', 'EPR: the entanglement half'],
  ['er-epr', 'builds-on', 'schwarzschild-metric', 'ER: the Einstein–Rosen bridge inside it'],
  ['er-epr', 'related', 'ads-cft', 'Entanglement builds connected geometry in AdS/CFT'],
  ['er-epr', 'related', 'hawking-radiation', 'A possible way out of the information paradox'],
  ['gravitational-lensing', 'builds-on', 'geodesics', 'Light follows geodesics too'],
  ['gravitational-lensing', 'builds-on', 'schwarzschild-metric', 'Bending around a point mass'],
  ['gravitational-lensing', 'related', 'black-holes', 'The photon ring in black hole images'],
  ['example-mercury-perihelion', 'example-of', 'geodesics', 'Orbits in the Schwarzschild metric slowly rotate'],
  ['example-mercury-perihelion', 'example-of', 'schwarzschild-metric', '43″ per century from 6πGM/(c²a(1 − e²))'],
  ['example-hafele-keating', 'example-of', 'sr-time-dilation', 'Flying east loses time'],
  ['example-hafele-keating', 'example-of', 'gravitational-time-dilation', 'Flying high gains time'],
  ['example-hafele-keating', 'related', 'atomic-clocks', 'Four caesium clocks on commercial flights'],
  ['arrow-of-time', 'builds-on', 'thermodynamics', 'Entropy only goes up'],
  ['arrow-of-time', 'related', 'cmb', 'The early universe started in a low-entropy state'],
  ['arrow-of-time', 'related', 'landauer-principle', 'Memories cost entropy to erase'],
  ['arrow-of-time', 'related', 'holographic-principle', 'Black holes: the highest-entropy objects'],
  ['arrow-of-time', 'related', 'measurement-problem', 'Measurement looks irreversible too'],
];
