// [from, kind, to, note]. "builds-on" and "derived-from" point from a topic to what you need first;
// "A part-of B" means A comes first. Every link except "example of" says why it's interesting.

export const LINKS = [
  // ---------------------------------------------------------------- maths of money
  ['compound-interest', 'builds-on', 'time-value-of-money', 'Compounding is the time value of money run forwards, year after year'],
  ['compound-interest', 'builds-on', 'exponential-growth', 'A fixed percentage each period is exponential growth'],
  ['present-value', 'builds-on', 'compound-interest', 'Discounting is compounding run backwards'],
  ['present-value', 'builds-on', 'opportunity-cost', 'The discount rate is what the money could have earned elsewhere'],
  ['rule-of-72', 'derived-from', 'compound-interest', 'Solve (1+r)^t = 2 and approximate'],
  ['rule-of-72', 'builds-on', 'logarithms', 'Doubling time is ln 2 ÷ ln(1 + r)'],
  ['continuous-compounding', 'derived-from', 'compound-interest', 'Let the number of compounding periods go to infinity'],
  ['continuous-compounding', 'related', 'exponential-growth', 'e is the base that makes growth rate and growth factor line up'],
  ['annuities', 'builds-on', 'present-value', 'An annuity is a sum of present values'],
  ['annuities', 'derived-from', 'geometric-series', 'The closed form is a geometric series summed'],
  ['logarithms', 'related', 'exponential-growth', 'Logs turn exponential curves into straight lines'],
  ['cagr', 'builds-on', 'compound-interest', 'CAGR is compound interest solved for the rate'],
  ['cagr', 'builds-on', 'logarithms', 'Taking the t-th root is dividing a log by t'],
  ['irr-xirr', 'builds-on', 'present-value', 'IRR is the discount rate that makes NPV zero'],
  ['irr-xirr', 'builds-on', 'cagr', 'CAGR is IRR when there is one deposit and one withdrawal'],
  ['correlation', 'builds-on', 'variance-sd', 'Correlation is covariance scaled by both standard deviations'],
  ['normal-distribution', 'builds-on', 'variance-sd', 'Two numbers, mean and σ, fix the whole bell curve'],
  ['law-of-large-numbers', 'builds-on', 'expected-value', 'Averages converge to the expected value'],
  ['law-of-large-numbers', 'builds-on', 'variance-sd', 'The wobble of an average shrinks like σ/√N'],
  ['central-limit-theorem', 'builds-on', 'law-of-large-numbers', 'The LLN says where the average goes; the CLT says what its wobble looks like'],
  ['central-limit-theorem', 'explains', 'normal-distribution', 'Why sums of many small shocks look like bell curves'],
  ['utility-risk-aversion', 'builds-on', 'expected-value', 'Expected utility replaces expected money'],
  ['utility-risk-aversion', 'builds-on', 'logarithms', 'Bernoulli’s utility is the log of wealth'],
  ['survivorship-bias', 'related', 'law-of-large-numbers', 'Averages mislead when the failures have quietly left the sample'],
  ['opportunity-cost', 'related', 'time-value-of-money', 'Waiting costs what the money could have done meanwhile'],
  ['geometric-series', 'related', 'exponential-growth', 'A geometric series is exponential growth, summed'],

  // ---------------------------------------------------------------- personal money
  ['sip', 'builds-on', 'annuities', 'A SIP is an annuity due: a payment at the start of every month'],
  ['sip', 'builds-on', 'compound-interest', 'Each instalment compounds for a different length of time'],
  ['sip', 'builds-on', 'mutual-funds', 'SIPs buy mutual fund units every month'],
  ['sip', 'related', 'irr-xirr', 'A SIP’s honest return is its XIRR, not its CAGR'],
  ['sip', 'related', 'market-timing', 'Automatic monthly buying removes the “when” decision'],
  ['ppf', 'builds-on', 'compound-interest', 'Yearly compounding at a government-set rate'],
  ['ppf', 'part-of', 'small-savings', 'The best known of the government’s small savings schemes'],
  ['ppf', 'related', 'section-80c', 'Deposits count towards the ₹1.5 lakh deduction (old regime)'],
  ['ppf', 'related', 'fixed-deposits', 'Tax-free PPF beats a taxable FD for anyone in a higher slab'],
  ['epf', 'builds-on', 'compound-interest', 'Contributions and interest compound over a whole career'],
  ['epf', 'related', 'ppf', 'Both are government-backed, long-term and tax-favoured; EPF is automatic'],
  ['epf', 'related', 'nps', 'The two pillars of salaried retirement saving in India'],
  ['nps', 'builds-on', 'annuities', 'At least 20% of the corpus must buy an annuity at 60'],
  ['nps', 'related', 'asset-allocation', 'You choose the equity share, or let it glide down with age'],
  ['nps', 'related', 'income-tax-regimes', 'Employer NPS is one of the few deductions left in the new regime'],
  ['fixed-deposits', 'builds-on', 'compound-interest', 'Banks usually compound FD interest quarterly'],
  ['fixed-deposits', 'builds-on', 'fisher-equation', 'After tax and inflation, an FD’s real return is often near zero'],
  ['fixed-deposits', 'related', 'bank-runs', 'DICGC cover of ₹5 lakh per bank exists because of bank runs'],
  ['fixed-deposits', 'related', 'repo-rate', 'FD rates follow the repo rate with a lag'],
  ['small-savings', 'related', 'government-securities', 'Rates are meant to track G-sec yields plus a spread'],
  ['small-savings', 'related', 'fixed-deposits', 'Government-backed alternatives to bank deposits, often at higher rates'],
  ['elss', 'builds-on', 'section-80c', 'The only equity option inside the 80C limit'],
  ['elss', 'builds-on', 'mutual-funds', 'An equity mutual fund with a three-year lock-in'],
  ['elss', 'related', 'index-funds', 'In the new regime an index fund does the same job cheaper'],
  ['insurance-pooling', 'builds-on', 'law-of-large-numbers', 'Pooling makes the average claim predictable'],
  ['insurance-pooling', 'builds-on', 'utility-risk-aversion', 'Paying more than the expected loss is rational when utility is curved'],
  ['term-insurance', 'builds-on', 'insurance-pooling', 'Rare deaths spread across many policyholders keep premiums low'],
  ['term-insurance', 'builds-on', 'present-value', 'The cover needed is the present value of the income it replaces'],
  ['health-insurance', 'builds-on', 'insurance-pooling', 'Super top-ups are cheap because big claims are rare'],
  ['endowment-ulip', 'builds-on', 'irr-xirr', 'IRR reveals what a “guaranteed maturity amount” is really worth'],
  ['endowment-ulip', 'related', 'term-insurance', 'Buy term and invest the rest usually beats the bundled policy'],
  ['emi', 'derived-from', 'annuities', 'The EMI is the annuity formula solved for the payment'],
  ['home-loans', 'builds-on', 'emi', 'Prepayment works because early EMIs are mostly interest'],
  ['home-loans', 'related', 'repo-rate', 'Floating home-loan rates are linked to the repo rate'],
  ['home-loans', 'related', 'leverage', 'A home loan is leverage on a single, illiquid asset'],
  ['rent-vs-buy', 'builds-on', 'opportunity-cost', 'Owning costs what the money tied up in the flat could have earned'],
  ['rent-vs-buy', 'builds-on', 'home-loans', 'The loan rate sets most of the cost of owning'],
  ['rent-vs-buy', 'related', 'real-estate-reits', 'Rental yield is the same number from the investor’s side'],
  ['credit-card-debt', 'builds-on', 'compound-interest', 'Monthly compounding turns 3.6% a month into over 50% a year'],
  ['credit-card-debt', 'related', 'credit-score', 'Missed card payments are the fastest way to wreck a score'],
  ['credit-card-debt', 'related', 'investor-biases', 'Mental accounting: holding an FD at 7% while paying 40% on a card'],
  ['credit-score', 'related', 'emi', 'A better score means a lower rate and a smaller EMI'],
  ['section-80c', 'part-of', 'income-tax-regimes', 'The biggest deduction in the old regime — and absent from the new'],
  ['capital-gains-tax', 'related', 'income-tax-regimes', 'Capital gains sit outside the slabs, at their own rates'],
  ['capital-gains-tax', 'related', 'debt-funds', 'Debt fund gains are now taxed at slab rates, like FD interest'],
  ['capital-gains-tax', 'related', 'dividends-buybacks', 'From April 2026 buybacks are taxed as capital gains'],
  ['retirement-corpus', 'builds-on', 'annuities', 'The corpus is the present value of a stream of withdrawals'],
  ['retirement-corpus', 'builds-on', 'fisher-equation', 'Rising withdrawals mean only the real return helps'],
  ['retirement-corpus', 'builds-on', 'inflation', 'Today’s spending must be inflated to the retirement date'],
  ['retirement-corpus', 'related', 'sip', 'The SIP needed is the corpus run backwards'],
  ['safe-withdrawal-rate', 'builds-on', 'annuities', 'How long a pot lasts is an annuity question'],
  ['safe-withdrawal-rate', 'related', 'retirement-corpus', 'The same problem from the other end: given a pot, what can you spend?'],
  ['safe-withdrawal-rate', 'related', 'volatility-drag', 'Sequence risk: the same average returns in a different order can drain the pot'],
  ['safe-withdrawal-rate', 'related', 'monte-carlo', 'Simulating thousands of return paths is how withdrawal rates are stress-tested'],
  ['financial-independence', 'builds-on', 'safe-withdrawal-rate', 'The target pot is spending divided by the withdrawal rate'],
  ['financial-independence', 'builds-on', 'budgeting', 'Savings rate, not salary, sets the timeline'],
  ['lifestyle-inflation', 'related', 'budgeting', 'Spending rises to meet income unless savings go first'],
  ['lifestyle-inflation', 'related', 'financial-independence', 'Every rupee of lifestyle raises the pot you need'],
  ['lifestyle-inflation', 'related', 'inflation', 'Your personal inflation includes your own upgrades'],
  ['emergency-fund', 'related', 'debt-funds', 'Liquid and overnight funds are natural homes for it'],
  ['emergency-fund', 'related', 'credit-card-debt', 'Without a buffer, shocks land on a card at 40%+'],
  ['asset-allocation', 'builds-on', 'diversification', 'Mixing asset classes cuts risk more than picking more stocks'],
  ['asset-allocation', 'builds-on', 'risk-return', 'The equity share sets both expected return and the depth of crashes'],
  ['asset-allocation', 'related', 'investor-biases', 'Rebalancing rules beat buying and selling on feel'],
  ['gold', 'related', 'exchange-rates', 'Gold is priced in dollars, so a weaker rupee lifts rupee gold'],
  ['gold', 'related', 'asset-allocation', 'A small slice often rises when stocks fall'],
  ['gold', 'related', 'gold-standard', 'Why gold still feels like “real” money'],
  ['real-estate-reits', 'builds-on', 'present-value', 'A building is worth its rents, discounted'],
  ['real-estate-reits', 'related', 'interest-rates', 'Property and REIT prices tend to fall when rates rise'],
  ['budgeting', 'related', 'sip', 'Automate savings on salary day and budget the rest'],

  // ---------------------------------------------------------------- markets
  ['stocks', 'builds-on', 'present-value', 'A share is worth its future cash flows brought back to today'],
  ['stocks', 'related', 'risk-return', 'Owners are paid last, so they must expect the most'],
  ['stock-exchanges', 'related', 'stocks', 'Where shares change hands'],
  ['stock-exchanges', 'related', 'market-liquidity', 'The order book is where the bid-ask spread lives'],
  ['market-cap', 'builds-on', 'stocks', 'Price per share times the number of shares'],
  ['stock-indices', 'builds-on', 'market-cap', 'Nifty and Sensex are weighted by free-float market cap'],
  ['stock-indices', 'related', 'survivorship-bias', 'Indices quietly swap losers for winners'],
  ['stock-indices', 'related', 'cagr', 'Nifty’s 1,000 to 26,000 is about 12% a year'],
  ['mutual-funds', 'builds-on', 'stocks', 'Most funds are baskets of stocks, bonds or both'],
  ['mutual-funds', 'related', 'diversification', 'A fund gives a small investor a diversified portfolio'],
  ['index-funds', 'builds-on', 'stock-indices', 'An index fund simply holds the index'],
  ['index-funds', 'builds-on', 'mutual-funds', 'A mutual fund (or ETF) that doesn’t pick stocks'],
  ['expense-ratio', 'builds-on', 'compound-interest', 'A yearly fee compounds into a large share of the final pot'],
  ['expense-ratio', 'builds-on', 'mutual-funds', 'Every fund takes its fee from the NAV daily'],
  ['active-vs-passive', 'builds-on', 'index-funds', 'The passive side of the debate'],
  ['active-vs-passive', 'builds-on', 'expense-ratio', 'Costs are the one certain difference between them'],
  ['active-vs-passive', 'related', 'survivorship-bias', 'Closed funds vanish from averages unless you correct for them'],
  ['bonds', 'builds-on', 'time-value-of-money', 'A bond is a promise of dated payments'],
  ['bond-pricing', 'builds-on', 'bonds', 'Pricing the coupons and face value'],
  ['bond-pricing', 'builds-on', 'annuities', 'The coupons are an annuity; the face value is one more discounted payment'],
  ['bond-pricing', 'related', 'irr-xirr', 'Yield to maturity is a bond’s IRR'],
  ['yield-curve', 'builds-on', 'bond-pricing', 'Yields at each maturity, side by side'],
  ['yield-curve', 'related', 'business-cycle', 'An inverted curve has often come before recessions'],
  ['government-securities', 'special-case-of', 'bonds', 'Bonds with no rupee default risk'],
  ['government-securities', 'related', 'capm', 'Their yield is the risk-free rate every model starts from'],
  ['credit-risk', 'builds-on', 'bonds', 'The chance a bond’s promises aren’t kept'],
  ['credit-risk', 'related', 'expected-value', 'A credit spread pays for expected default losses plus a premium'],
  ['debt-funds', 'builds-on', 'bond-pricing', 'Duration decides how much a debt fund swings with rates'],
  ['debt-funds', 'builds-on', 'credit-risk', 'Credit quality decides what can go permanently wrong'],
  ['debt-funds', 'builds-on', 'mutual-funds', 'Mutual funds that hold bonds instead of stocks'],
  ['risk-return', 'builds-on', 'variance-sd', 'Risk is usually measured as the spread of returns'],
  ['risk-return', 'builds-on', 'expected-value', 'Return means expected return'],
  ['diversification', 'builds-on', 'correlation', 'It only works when assets don’t move in lockstep'],
  ['diversification', 'builds-on', 'variance-sd', 'Portfolio variance has a cross term that correlation can shrink'],
  ['diversification', 'related', 'law-of-large-numbers', 'Many independent bets average out; correlated ones don’t'],
  ['modern-portfolio-theory', 'builds-on', 'diversification', 'Markowitz turned diversification into an optimisation'],
  ['modern-portfolio-theory', 'builds-on', 'risk-return', 'The efficient frontier is the best risk–return trade-off available'],
  ['capm', 'builds-on', 'modern-portfolio-theory', 'Add a risk-free asset to Markowitz and everyone holds the market'],
  ['capm', 'builds-on', 'correlation', 'Beta is covariance with the market, scaled'],
  ['sharpe-ratio', 'builds-on', 'risk-return', 'Return earned per unit of risk taken'],
  ['sharpe-ratio', 'related', 'capm', 'The tangency portfolio is the one with the highest Sharpe ratio'],
  ['efficient-market-hypothesis', 'builds-on', 'random-walk', 'If prices reflect all information, only surprises move them — a random walk'],
  ['behavioural-finance', 'tension', 'efficient-market-hypothesis', 'Predictable errors vs prices that already know everything'],
  ['prospect-theory', 'builds-on', 'utility-risk-aversion', 'Replaces utility of wealth with value of gains and losses'],
  ['prospect-theory', 'part-of', 'behavioural-finance', 'The founding theory of behavioural finance'],
  ['investor-biases', 'part-of', 'behavioural-finance', 'The catalogue of predictable mistakes'],
  ['investor-biases', 'related', 'prospect-theory', 'The disposition effect comes straight from loss aversion'],
  ['pe-ratio', 'builds-on', 'stocks', 'Price compared with each share’s slice of profit'],
  ['pe-ratio', 'related', 'gordon-growth', 'A fair P/E is roughly payout ÷ (r − g)'],
  ['gordon-growth', 'derived-from', 'geometric-series', 'An infinite geometric series with ratio (1+g)/(1+r)'],
  ['gordon-growth', 'builds-on', 'present-value', 'Every future dividend, discounted'],
  ['dcf', 'builds-on', 'present-value', 'Value is future cash, discounted'],
  ['dcf', 'builds-on', 'gordon-growth', 'The terminal value is a Gordon growth formula'],
  ['dcf', 'builds-on', 'cash-flow-statement', 'DCF values free cash flow, not accounting profit'],
  ['dcf', 'builds-on', 'wacc', 'The discount rate is the cost of capital'],
  ['dividends-buybacks', 'related', 'stocks', 'The two ways cash comes back to shareholders'],
  ['dividends-buybacks', 'related', 'roe-dupont', 'Retained profit is worth keeping only if ROE beats your alternatives'],
  ['ipos', 'builds-on', 'stocks', 'The first public sale of a company’s shares'],
  ['ipos', 'related', 'investor-biases', 'Herding and FOMO fill IPO order books'],
  ['sebi', 'related', 'stock-exchanges', 'The regulator of exchanges, brokers and listed companies'],
  ['sebi', 'related', 'mutual-funds', 'SEBI sets fund categories, direct plans and cost caps'],
  ['short-selling', 'related', 'efficient-market-hypothesis', 'Without shorts, prices only hear from optimists'],
  ['short-selling', 'related', 'leverage', 'Short positions need margin and can face unlimited losses'],
  ['market-liquidity', 'related', 'debt-funds', 'Bond markets can freeze, as in March 2020'],
  ['international-investing', 'builds-on', 'diversification', 'Other economies don’t move in lockstep with India'],
  ['international-investing', 'builds-on', 'exchange-rates', 'A falling rupee adds to foreign returns'],
  ['international-investing', 'related', 'investor-biases', 'Home bias: India is about 4% of world markets'],
  ['factor-investing', 'builds-on', 'capm', 'Factors are the returns CAPM’s beta fails to explain'],
  ['factor-investing', 'tension', 'efficient-market-hypothesis', 'Persistent premiums: hidden risks or lasting mistakes?'],
  ['factor-investing', 'related', 'index-funds', 'Smart-beta funds package factors as indices'],
  ['market-timing', 'related', 'efficient-market-hypothesis', 'If prices are hard to predict, so are the best days to be in'],
  ['market-timing', 'related', 'investor-biases', 'Selling in fear and buying in greed is the behaviour gap'],
  ['equity-premium-puzzle', 'builds-on', 'risk-return', 'Why is the reward for equity risk so large?'],
  ['equity-premium-puzzle', 'builds-on', 'utility-risk-aversion', 'Standard risk aversion can’t explain it'],
  ['equity-premium-puzzle', 'related', 'prospect-theory', 'Myopic loss aversion is one candidate answer'],
  ['equity-premium-puzzle', 'related', 'ergodicity', 'Time-average growth changes what compensation for risk should be'],
  ['crypto', 'builds-on', 'what-is-money', 'Judged against money’s three jobs'],
  ['crypto', 'related', 'bubbles', 'Several 70–80% crashes: the bubble script, repeated'],
  ['crypto', 'related', 'gold-standard', 'A fixed supply as a vote against fiat money'],

  // ---------------------------------------------------------------- businesses & accounts
  ['balance-sheet', 'builds-on', 'double-entry', 'Assets = liabilities + equity holds because every entry is doubled'],
  ['income-statement', 'builds-on', 'double-entry', 'Every sale and cost is recorded against a balance-sheet account'],
  ['cash-flow-statement', 'builds-on', 'income-statement', 'Starts from profit and adjusts for what isn’t cash'],
  ['cash-flow-statement', 'builds-on', 'balance-sheet', 'Changes in working capital come from the balance sheet'],
  ['leverage', 'builds-on', 'balance-sheet', 'Debt relative to equity is read off the balance sheet'],
  ['roe-dupont', 'builds-on', 'income-statement', 'Net profit on top'],
  ['roe-dupont', 'builds-on', 'balance-sheet', 'Equity and assets underneath'],
  ['roe-dupont', 'builds-on', 'leverage', 'The equity multiplier is leverage'],
  ['wacc', 'builds-on', 'capm', 'The cost of equity usually comes from CAPM'],
  ['wacc', 'related', 'leverage', 'More debt looks cheaper but makes equity riskier'],
  ['economic-moats', 'related', 'roe-dupont', 'A moat is what keeps ROCE high for decades'],
  ['economic-moats', 'related', 'pe-ratio', 'Durable returns justify higher multiples'],
  ['corporate-governance', 'related', 'cash-flow-statement', 'Profits that never become cash are the classic red flag'],
  ['corporate-governance', 'related', 'credit-risk', 'Weak governance often shows up first as a credit event'],
  ['double-entry', 'related', 'what-is-money', 'Bank money is an entry in a ledger: your asset, the bank’s liability'],

  // ---------------------------------------------------------------- quant
  ['random-walk', 'builds-on', 'variance-sd', 'Independent steps: variances add, so spread grows like √N'],
  ['random-walk', 'related', 'central-limit-theorem', 'The endpoint of a long walk is normally distributed'],
  ['brownian-motion', 'derived-from', 'random-walk', 'The limit of ever smaller, ever faster steps'],
  ['brownian-motion', 'builds-on', 'normal-distribution', 'Increments are normally distributed with variance equal to time'],
  ['log-returns', 'builds-on', 'logarithms', 'ln(new/old) turns multiplying returns into adding them'],
  ['log-returns', 'builds-on', 'continuous-compounding', 'A log return is the continuously compounded rate'],
  ['volatility', 'builds-on', 'variance-sd', 'Volatility is the standard deviation of returns'],
  ['volatility', 'builds-on', 'random-walk', 'The √time rule comes from the random walk'],
  ['volatility-drag', 'builds-on', 'volatility', 'The drag is about σ²/2 a year'],
  ['volatility-drag', 'builds-on', 'cagr', 'CAGR is the geometric mean; brochures quote the arithmetic one'],
  ['lognormal', 'builds-on', 'normal-distribution', 'The exponential of a normal variable'],
  ['lognormal', 'builds-on', 'log-returns', 'Normal log returns mean lognormal prices'],
  ['ito-lemma', 'builds-on', 'brownian-motion', '(dW)² = dt is what forces the extra term'],
  ['geometric-brownian-motion', 'builds-on', 'brownian-motion', 'Brownian shocks applied to percentage changes'],
  ['geometric-brownian-motion', 'builds-on', 'ito-lemma', 'Solving it needs Itô, which produces the μ − σ²/2 drift'],
  ['geometric-brownian-motion', 'builds-on', 'log-returns', 'The log of a GBM price is Brownian motion with drift'],
  ['geometric-brownian-motion', 'related', 'volatility-drag', 'The median path grows at μ − σ²/2: drag built into the model'],
  ['put-call-parity', 'builds-on', 'options', 'Relates the prices of calls and puts'],
  ['put-call-parity', 'derived-from', 'no-arbitrage', 'Two portfolios with the same payoff must cost the same'],
  ['binomial-model', 'builds-on', 'options', 'Prices an option over one up-or-down step'],
  ['binomial-model', 'builds-on', 'no-arbitrage', 'Replication plus no free lunch fixes the price'],
  ['risk-neutral-pricing', 'derived-from', 'binomial-model', 'The replication price looks like an expectation under made-up odds'],
  ['risk-neutral-pricing', 'builds-on', 'expected-value', 'Price = discounted expected payoff, under the risk-neutral measure'],
  ['black-scholes', 'builds-on', 'geometric-brownian-motion', 'Assumes the underlying follows GBM'],
  ['black-scholes', 'builds-on', 'risk-neutral-pricing', 'The formula is a risk-neutral expectation'],
  ['black-scholes', 'builds-on', 'options', 'Prices a European call or put'],
  ['black-scholes', 'derived-from', 'ito-lemma', 'Itô plus delta hedging gives the Black–Scholes equation'],
  ['binomial-model', 'related', 'black-scholes', 'Many small binomial steps converge to Black–Scholes'],
  ['black-scholes-heat', 'builds-on', 'black-scholes', 'The Black–Scholes equation, transformed'],
  ['black-scholes-heat', 'builds-on', 'brownian-motion', 'Heat and prices both diffuse because both random-walk'],
  ['greeks', 'builds-on', 'black-scholes', 'Each Greek is a derivative of the Black–Scholes price'],
  ['implied-volatility', 'builds-on', 'black-scholes', 'The σ that makes the formula match the market'],
  ['implied-volatility', 'builds-on', 'volatility', 'Volatility read from option prices instead of history'],
  ['implied-volatility', 'related', 'fat-tails', 'The smile is the market pricing in crashes the model ignores'],
  ['futures-forwards', 'builds-on', 'no-arbitrage', 'Cash-and-carry arbitrage pins the futures price'],
  ['futures-forwards', 'related', 'options', 'The two families of exchange-traded derivatives'],
  ['futures-forwards', 'related', 'leverage', 'Small margins mean big percentage swings'],
  ['fno-retail-losses', 'example-of', 'options'],
  ['fno-retail-losses', 'example-of', 'futures-forwards'],
  ['fno-retail-losses', 'related', 'sebi', 'SEBI’s own studies, and the curbs that followed'],
  ['fno-retail-losses', 'related', 'prospect-theory', 'Cheap out-of-the-money options exploit our love of long shots'],
  ['fno-retail-losses', 'related', 'gamblers-ruin', 'An edge smaller than costs is a negative edge'],
  ['kelly-criterion', 'builds-on', 'utility-risk-aversion', 'Kelly maximises log wealth — Bernoulli’s utility'],
  ['kelly-criterion', 'builds-on', 'expected-value', 'You need a positive edge to bet at all'],
  ['kelly-criterion', 'builds-on', 'logarithms', 'Growth over many bets is the average of log returns'],
  ['ergodicity', 'builds-on', 'expected-value', 'Separates the ensemble average from the time average'],
  ['ergodicity', 'builds-on', 'volatility-drag', 'The gap between the two averages is volatility drag'],
  ['ergodicity', 'same-idea', 'kelly-criterion', 'Maximising time-average growth gives Kelly betting'],
  ['ergodicity', 'related', 'utility-risk-aversion', 'Log utility falls out of the dynamics, not psychology'],
  ['ergodicity', 'related', 'insurance-pooling', 'Pooling raises everyone’s time-average growth'],
  ['fat-tails', 'builds-on', 'normal-distribution', 'Defined by how far reality departs from the bell curve'],
  ['fat-tails', 'tension', 'central-limit-theorem', 'The CLT’s bell curve needs independence and finite variance'],
  ['fat-tails', 'related', 'correlation', 'Correlations jump towards 1 in crashes'],
  ['value-at-risk', 'builds-on', 'normal-distribution', 'The standard VaR is a normal quantile'],
  ['value-at-risk', 'builds-on', 'volatility', 'Scaled by daily volatility and √horizon'],
  ['value-at-risk', 'tension', 'fat-tails', 'VaR says nothing about how bad the worst days are'],
  ['monte-carlo', 'builds-on', 'law-of-large-numbers', 'Averages over many simulated paths converge'],
  ['monte-carlo', 'related', 'risk-neutral-pricing', 'Price an option by averaging payoffs over simulated risk-neutral paths'],
  ['martingale', 'builds-on', 'expected-value', 'A martingale’s expected next value is its current value'],
  ['martingale', 'related', 'risk-neutral-pricing', 'Discounted prices are martingales under the risk-neutral measure'],
  ['martingale', 'related', 'fat-tails', 'Doubling strategies earn small steady gains and hide a ruinous tail'],
  ['gamblers-ruin', 'builds-on', 'random-walk', 'Your stake is a random walk with a wall at zero'],
  ['gamblers-ruin', 'related', 'kelly-criterion', 'Kelly sizing is how to bet with an edge without ruin'],
  ['econophysics', 'related', 'brownian-motion', 'Where finance and physics first met'],
  ['econophysics', 'related', 'fat-tails', 'Power-law tails are econophysics’ best-known finding'],
  ['econophysics', 'related', 'ergodicity', 'Statistical mechanics’ central assumption, tested on wealth'],

  // ---------------------------------------------------------------- economy
  ['inflation', 'builds-on', 'what-is-money', 'Inflation is money losing purchasing power'],
  ['inflation', 'related', 'rule-of-72', 'At 6% inflation prices double in about 12 years'],
  ['cpi', 'describes', 'inflation', 'The index behind the headline number'],
  ['fisher-equation', 'builds-on', 'inflation', 'Separates what money earns from what it buys'],
  ['fisher-equation', 'related', 'present-value', 'Discount real cash flows at real rates, nominal at nominal'],
  ['interest-rates', 'builds-on', 'time-value-of-money', 'An interest rate is the market price of time'],
  ['interest-rates', 'related', 'present-value', 'A higher rate shrinks every future rupee’s value today'],
  ['interest-rates', 'related', 'bond-pricing', 'Bond prices move opposite to yields'],
  ['repo-rate', 'builds-on', 'interest-rates', 'The anchor for every other rupee interest rate'],
  ['repo-rate', 'related', 'rbi', 'The RBI’s Monetary Policy Committee sets it'],
  ['repo-rate', 'related', 'emi', 'Changes reach floating-rate EMIs within about three months'],
  ['inflation-targeting', 'builds-on', 'inflation', 'The goal: 4% CPI inflation'],
  ['inflation-targeting', 'builds-on', 'repo-rate', 'The tool: the repo rate'],
  ['inflation-targeting', 'related', 'rbi', 'The RBI’s legal mandate since 2016'],
  ['inflation-targeting', 'related', 'cpi', 'The target is headline CPI'],
  ['money-creation', 'builds-on', 'what-is-money', 'Most money is bank deposits'],
  ['money-creation', 'builds-on', 'geometric-series', 'The textbook money multiplier is a geometric series'],
  ['money-creation', 'related', 'repo-rate', 'The RBI steers money growth through the price of reserves'],
  ['bank-runs', 'builds-on', 'money-creation', 'Banks lend long against deposits payable on demand'],
  ['bank-runs', 'related', 'rbi', 'The central bank as lender of last resort'],
  ['fiscal-deficit', 'builds-on', 'gdp', 'Deficits and debt are measured against GDP'],
  ['fiscal-deficit', 'builds-on', 'interest-rates', 'r − g decides whether debt snowballs'],
  ['fiscal-deficit', 'related', 'government-securities', 'The deficit is financed by issuing G-secs'],
  ['fiscal-deficit', 'related', 'capital-gains-tax', 'Budget day is when your tax rules change'],
  ['exchange-rates', 'builds-on', 'what-is-money', 'The price of one money in another'],
  ['exchange-rates', 'related', 'rbi', 'The RBI smooths the rupee from its forex reserves'],
  ['ppp', 'builds-on', 'exchange-rates', 'A long-run theory of where exchange rates should drift'],
  ['ppp', 'builds-on', 'inflation', 'The inflation gap sets the drift'],
  ['current-account', 'builds-on', 'exchange-rates', 'The deficit needs dollars, which moves the rupee'],
  ['current-account', 'builds-on', 'gdp', 'Net exports are part of GDP; the deficit is measured against it'],
  ['business-cycle', 'builds-on', 'gdp', 'Recessions are measured as falling real GDP'],
  ['business-cycle', 'related', 'leverage', 'Credit amplifies booms and busts'],
  ['phillips-curve', 'builds-on', 'inflation', 'Inflation on one axis'],
  ['phillips-curve', 'builds-on', 'business-cycle', 'Slack in the economy on the other'],
  ['phillips-curve', 'related', 'inflation-targeting', 'Anchored expectations keep the curve flat'],
  ['quantitative-easing', 'builds-on', 'money-creation', 'The central bank creates reserves to buy bonds'],
  ['quantitative-easing', 'builds-on', 'bond-pricing', 'Buying bonds pushes long yields down'],
  ['quantitative-easing', 'related', 'repo-rate', 'The tool used once policy rates hit zero'],
  ['gold-standard', 'builds-on', 'what-is-money', 'Money anchored to a commodity'],
  ['gold-standard', 'related', 'crash-1929', 'Countries that left gold early recovered from the Depression faster'],
  ['upi', 'related', 'what-is-money', 'New rails for moving bank money, not new money'],
  ['upi', 'related', 'economic-moats', 'Free, open rails drained some payment businesses’ moats'],
  ['gdp', 'related', 'stocks', 'Fast GDP growth doesn’t guarantee good stock returns'],

  // ---------------------------------------------------------------- crises & stories
  ['bubbles', 'related', 'investor-biases', 'Herding, FOMO and recency bias drive the euphoria stage'],
  ['bubbles', 'related', 'leverage', 'Credit is the fuel; forced deleveraging is the crash'],
  ['bubbles', 'tension', 'efficient-market-hypothesis', 'Can prices be so wrong for so long?'],
  ['bubbles', 'related', 'gordon-growth', 'A bubble is growth assumed to be nearly equal to the discount rate'],
  ['tulip-mania', 'example-of', 'bubbles'],
  ['tulip-mania', 'related', 'futures-forwards', 'Tavern trading in future bulbs was an informal futures market'],
  ['south-sea-bubble', 'example-of', 'bubbles'],
  ['south-sea-bubble', 'related', 'leverage', 'The company lent investors money to buy its own shares'],
  ['crash-1929', 'example-of', 'bubbles'],
  ['crash-1929', 'example-of', 'bank-runs'],
  ['crash-1929', 'related', 'leverage', 'Shares bought with 10% down meant margin calls all the way down'],
  ['bop-crisis-1991', 'example-of', 'current-account'],
  ['bop-crisis-1991', 'related', 'exchange-rates', 'Two-step devaluation of the rupee in July 1991'],
  ['bop-crisis-1991', 'related', 'gold', 'India literally flew its gold to London as collateral'],
  ['harshad-mehta-scam', 'example-of', 'bubbles'],
  ['harshad-mehta-scam', 'related', 'sebi', 'The scandal that gave SEBI statutory powers'],
  ['harshad-mehta-scam', 'related', 'stock-exchanges', 'Led to screen trading on the NSE and to demat'],
  ['harshad-mehta-scam', 'related', 'government-securities', 'The money came through the G-sec ready-forward market'],
  ['dotcom-bubble', 'example-of', 'bubbles'],
  ['dotcom-bubble', 'related', 'dcf', 'Real growth, impossible terminal values'],
  ['ltcm', 'example-of', 'leverage'],
  ['ltcm', 'example-of', 'fat-tails'],
  ['ltcm', 'related', 'black-scholes', 'Run by the Nobel laureates behind option pricing'],
  ['ltcm', 'related', 'no-arbitrage', 'Convergence trades that diverged: the limits of arbitrage'],
  ['gfc-2008', 'example-of', 'leverage'],
  ['gfc-2008', 'example-of', 'credit-risk'],
  ['gfc-2008', 'example-of', 'bank-runs'],
  ['gfc-2008', 'related', 'correlation', 'Mortgage defaults assumed independent turned out correlated'],
  ['gfc-2008', 'related', 'quantitative-easing', 'The response that defined the next decade'],
  ['gfc-2008', 'related', 'value-at-risk', 'Risk models calibrated on calm years'],
  ['satyam-scandal', 'example-of', 'corporate-governance'],
  ['satyam-scandal', 'related', 'double-entry', 'Fake revenue matched by fake cash kept the books balanced'],
  ['satyam-scandal', 'related', 'cash-flow-statement', 'Reported cash that earned almost no interest'],
  ['ilfs-debt-shock', 'example-of', 'credit-risk'],
  ['ilfs-debt-shock', 'example-of', 'debt-funds'],
  ['ilfs-debt-shock', 'related', 'market-liquidity', 'Franklin Templeton froze schemes it couldn’t sell out of'],
  ['yes-bank-rescue', 'example-of', 'bank-runs'],
  ['yes-bank-rescue', 'example-of', 'credit-risk'],
  ['yes-bank-rescue', 'related', 'fixed-deposits', 'Depositors were protected; AT1 bondholders were not'],
  ['demonetisation', 'example-of', 'what-is-money'],
  ['demonetisation', 'related', 'upi', 'The cash squeeze that made UPI a habit'],
  ['hyperinflation', 'example-of', 'inflation'],
  ['hyperinflation', 'related', 'gold-standard', 'Fiat money with no discipline at all'],
  ['hyperinflation', 'related', 'money-creation', 'Printing money to pay the government’s bills'],
  ['ponzi-schemes', 'example-of', 'exponential-growth'],
  ['ponzi-schemes', 'related', 'sharpe-ratio', 'Madoff’s returns were too smooth to be true'],
  ['ponzi-schemes', 'related', 'bubbles', 'Minsky’s last stage: debt serviced only by new money'],
  ['gamestop-squeeze', 'example-of', 'short-selling'],
  ['gamestop-squeeze', 'related', 'greeks', 'Option dealers’ hedging added a gamma squeeze'],
  ['covid-crash-2020', 'example-of', 'fat-tails'],
  ['covid-crash-2020', 'related', 'market-timing', 'The best rebound days came right after the worst days'],
  ['covid-crash-2020', 'related', 'emergency-fund', 'Crashes and layoffs arrive together'],
  ['covid-crash-2020', 'related', 'volatility', 'Volatility clusters: a 13% day in a month of wild days'],
  ['svb-collapse', 'example-of', 'bank-runs'],
  ['svb-collapse', 'example-of', 'bond-pricing'],
  ['svb-collapse', 'related', 'interest-rates', 'Rising rates silently erased the value of “safe” bonds'],
];
